# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Завершение аутентификации — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class CompletePaymentApiVersion(StrEnum):
    """CompletePaymentApiVersion values."""

    V1_0 = "v1.0"
