# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""[WIP] Платёж через форму банка — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class CreateInvoiceResponseDataPaymentOptionsAvailablePaymentMethods(StrEnum):
    """CreateInvoiceResponseDataPaymentOptionsAvailablePaymentMethods values."""

    CARD = "CARD"
    SBP = "SBP"


class CreateInvoiceApiVersion(StrEnum):
    """CreateInvoiceApiVersion values."""

    V1_0 = "v1.0"


class CreateInvoiceDataPaymentOptionsAvailablePaymentMethods(StrEnum):
    """CreateInvoiceDataPaymentOptionsAvailablePaymentMethods values."""

    CARD = "CARD"
    SBP = "SBP"


class GetInvoiceResponseDataPaymentOptionsAvailablePaymentMethods(StrEnum):
    """GetInvoiceResponseDataPaymentOptionsAvailablePaymentMethods values."""

    CARD = "CARD"
    SBP = "SBP"


class GetInvoiceApiVersion(StrEnum):
    """GetInvoiceApiVersion values."""

    V1_0 = "v1.0"


class CancelInvoiceResponseDataPaymentOptionsAvailablePaymentMethods(StrEnum):
    """CancelInvoiceResponseDataPaymentOptionsAvailablePaymentMethods values."""

    CARD = "CARD"
    SBP = "SBP"


class CancelInvoiceApiVersion(StrEnum):
    """CancelInvoiceApiVersion values."""

    V1_0 = "v1.0"
