# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с закрывающими документами — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class CreateClosingDocumentDataSecondSideType(StrEnum):
    """CreateClosingDocumentDataSecondSideType values."""

    IP = "ip"
    COMPANY = "company"
