# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сделки — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class ListDealV2ParamsFiltersStatus(StrEnum):
    """ListDealV2ParamsFiltersStatus values."""

    NEW = "new"
    CORRECTION = "correction"
    PARTIAL = "partial"
    IN_PROCESS = "in_process"
    CLOSED = "closed"
    REJECTED = "rejected"
    CANCELED_BY_PLATFORM = "canceled_by_platform"
    CANCELED_BY_SERVICE = "canceled_by_service"


class ListDealsV2ParamsFieldNames(StrEnum):
    """ListDealsV2ParamsFieldNames values."""

    AMOUNT = "amount"
    STATUS = "status"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    EXT_KEY = "ext_key"


class ListDealsV2ParamsFiltersStatus(StrEnum):
    """ListDealsV2ParamsFiltersStatus values."""

    NEW = "new"
    CORRECTION = "correction"
    PARTIAL = "partial"
    IN_PROCESS = "in_process"
    CLOSED = "closed"
    REJECTED = "rejected"
    CANCELED_BY_PLATFORM = "canceled_by_platform"
    CANCELED_BY_SERVICE = "canceled_by_service"
