# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с Экспресс кредитами — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class ActivationRefuseApiVersion(StrEnum):
    """ActivationRefuseApiVersion values."""

    V1_0 = "v1.0"


class ActivationRefuseDataResult(StrEnum):
    """ActivationRefuseDataResult values."""

    REJECT = "REJECT"
    ERROR = "ERROR"
    HOLD = "HOLD"


class LoansChangeApiVersion(StrEnum):
    """LoansChangeApiVersion values."""

    V1_0 = "v1.0"


class LoansChangeDataLoansInfoStatus(StrEnum):
    """LoansChangeDataLoansInfoStatus values."""

    AVAILABLE = "AVAILABLE"
    CREATED = "CREATED"
    CLOSED = "CLOSED"
    EXECUTED = "EXECUTED"


class OfferApiVersion(StrEnum):
    """OfferApiVersion values."""

    V1_0 = "v1.0"


class OfferDataOfferPayloadProductType(StrEnum):
    """OfferDataOfferPayloadProductType values."""

    TL_SME = "TL_SME"
