# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с выставлением счетов — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class CreateInvoiceDataContentInvoicePositionsNdsKind(StrEnum):
    """CreateInvoiceDataContentInvoicePositionsNdsKind values."""

    NDS_0 = "nds_0"
    NDS_5 = "nds_5"
    NDS_7 = "nds_7"
    NDS_10 = "nds_10"
    NDS_22 = "nds_22"
    WITHOUT_NDS = "without_nds"


class CreateInvoiceDataContentInvoicePositionsUnitCode(StrEnum):
    """CreateInvoiceDataContentInvoicePositionsUnitCode values."""

    SHT = "шт."
    TYS_SHT = "тыс.шт."
    KOMPL = "компл."
    PAR = "пар."
    USL_ED = "усл.ед."
    UPAK = "упак."
    USLUGA = "услуга."
    PACH = "пач."
    MIN = "мин."
    CH = "ч."
    SUT = "сут."
    G = "г."
    KG = "кг."
    L_ = "л."
    M = "м."
    M2 = "м2."
    M3 = "м3."
    KM = "км."
    GA = "га."
    KVT = "кВт."
    KVT_CH = "кВт.ч."


class CreateInvoiceDataSecondSideType(StrEnum):
    """CreateInvoiceDataSecondSideType values."""

    IP = "ip"
    COMPANY = "company"


class GetInvoicePaymentStatusResponseDataPaymentStatus(StrEnum):
    """GetInvoicePaymentStatusResponseDataPaymentStatus values."""

    PAYMENT_WAITING = "payment_waiting"
    PAYMENT_EXPIRED = "payment_expired"
    PAYMENT_PAID = "payment_paid"
