# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Получатели — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetRecipientResponseDataPayoutMethodsMethodType(StrEnum):
    """GetRecipientResponseDataPayoutMethodsMethodType values."""

    SBP = "SBP"
    CARD = "CARD"


class GetRecipientV2ResponseDataPayoutMethodsMethodType(StrEnum):
    """GetRecipientV2ResponseDataPayoutMethodsMethodType values."""

    SBP = "SBP"
    CARD = "CARD"
