# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Загрузка документов — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class UploadDocumentBeneficiaryDocumentType(StrEnum):
    """UploadDocumentBeneficiaryDocumentType values."""

    CONTRACT_OFFER = "contract_offer"


class UploadDocumentDealDocumentType(StrEnum):
    """UploadDocumentDealDocumentType values."""

    SERVICE_AGREEMENT = "service_agreement"
