# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платежами — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetPaymentStatusResponseDataStatus(StrEnum):
    """GetPaymentStatusResponseDataStatus values."""

    WAITINGFORCREATE = "WaitingForCreate"
    CREATED = "Created"
    PAID = "Paid"
    CANCELED = "Canceled"
    REJECTED = "Rejected"
