# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платёжными ссылками — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetPaymentOperationListResponseDataOperationItemsMeasure(StrEnum):
    """GetPaymentOperationListResponseDataOperationItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class GetPaymentOperationListResponseDataOperationItemsPaymentMethod(StrEnum):
    """GetPaymentOperationListResponseDataOperationItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class GetPaymentOperationListResponseDataOperationItemsPaymentObject(StrEnum):
    """GetPaymentOperationListResponseDataOperationItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class GetPaymentOperationListResponseDataOperationItemsVatType(StrEnum):
    """GetPaymentOperationListResponseDataOperationItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT20 = "vat20"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT120 = "vat120"
    VAT122 = "vat122"


class GetPaymentOperationListResponseDataOperationOrderType(StrEnum):
    """GetPaymentOperationListResponseDataOperationOrderType values."""

    REFUND = "refund"
    APPROVAL = "approval"
    AUTHORIZED = "authorized"


class GetPaymentOperationListResponseDataOperationPaymentMode(StrEnum):
    """GetPaymentOperationListResponseDataOperationPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentOperationListResponseDataOperationPaymentType(StrEnum):
    """GetPaymentOperationListResponseDataOperationPaymentType values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentOperationListResponseDataOperationStatus(StrEnum):
    """GetPaymentOperationListResponseDataOperationStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class GetPaymentOperationListResponseDataOperationTaxSystemCode(StrEnum):
    """GetPaymentOperationListResponseDataOperationTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"
    ENVD = "envd"


class GetPaymentOperationListStatus(StrEnum):
    """GetPaymentOperationListStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class CreatePaymentOperationResponseDataPaymentMode(StrEnum):
    """CreatePaymentOperationResponseDataPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class CreatePaymentOperationResponseDataStatus(StrEnum):
    """CreatePaymentOperationResponseDataStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class CreatePaymentOperationDataPaymentMode(StrEnum):
    """CreatePaymentOperationDataPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentOperationInfoResponseDataOperationItemsMeasure(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class GetPaymentOperationInfoResponseDataOperationItemsPaymentMethod(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class GetPaymentOperationInfoResponseDataOperationItemsPaymentObject(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class GetPaymentOperationInfoResponseDataOperationItemsVatType(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT20 = "vat20"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT120 = "vat120"
    VAT122 = "vat122"


class GetPaymentOperationInfoResponseDataOperationOrderType(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationOrderType values."""

    REFUND = "refund"
    APPROVAL = "approval"
    AUTHORIZED = "authorized"


class GetPaymentOperationInfoResponseDataOperationPaymentMode(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentOperationInfoResponseDataOperationPaymentType(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationPaymentType values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentOperationInfoResponseDataOperationStatus(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class GetPaymentOperationInfoResponseDataOperationTaxSystemCode(StrEnum):
    """GetPaymentOperationInfoResponseDataOperationTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"
    ENVD = "envd"


class CreatePaymentOperationWithReceiptResponseDataItemsMeasure(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class CreatePaymentOperationWithReceiptResponseDataItemsPaymentMethod(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class CreatePaymentOperationWithReceiptResponseDataItemsPaymentObject(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class CreatePaymentOperationWithReceiptResponseDataItemsVatType(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT122 = "vat122"


class CreatePaymentOperationWithReceiptResponseDataPaymentMode(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class CreatePaymentOperationWithReceiptResponseDataStatus(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class CreatePaymentOperationWithReceiptResponseDataTaxSystemCode(StrEnum):
    """CreatePaymentOperationWithReceiptResponseDataTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"


class CreatePaymentOperationWithReceiptDataItemsMeasure(StrEnum):
    """CreatePaymentOperationWithReceiptDataItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class CreatePaymentOperationWithReceiptDataItemsPaymentMethod(StrEnum):
    """CreatePaymentOperationWithReceiptDataItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class CreatePaymentOperationWithReceiptDataItemsPaymentObject(StrEnum):
    """CreatePaymentOperationWithReceiptDataItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class CreatePaymentOperationWithReceiptDataItemsVatType(StrEnum):
    """CreatePaymentOperationWithReceiptDataItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT122 = "vat122"


class CreatePaymentOperationWithReceiptDataPaymentMode(StrEnum):
    """CreatePaymentOperationWithReceiptDataPaymentMode values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class CreatePaymentOperationWithReceiptDataTaxSystemCode(StrEnum):
    """CreatePaymentOperationWithReceiptDataTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"


class GetPaymentRegistryResponseDataRegistryPaymentType(StrEnum):
    """GetPaymentRegistryResponseDataRegistryPaymentType values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetPaymentRegistryResponseDataRegistryPaymentsStatus(StrEnum):
    """GetPaymentRegistryResponseDataRegistryPaymentsStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class GetRetailersResponseDataRetailerPaymentModes(StrEnum):
    """GetRetailersResponseDataRetailerPaymentModes values."""

    SBP = "sbp"
    CARD = "card"
    TINKOFF = "tinkoff"
    DOLYAME = "dolyame"


class GetRetailersResponseDataRetailerStatus(StrEnum):
    """GetRetailersResponseDataRetailerStatus values."""

    NEW = "NEW"
    ADDRESS_DADATA = "ADDRESS_DADATA"
    OPEN_ACCOUNT = "OPEN_ACCOUNT"
    TWPG_SENDED = "TWPG_SENDED"
    RETAILER_CREATED = "RETAILER_CREATED"
    TERMINAL_CREATED = "TERMINAL_CREATED"
    FILE_SENT = "FILE_SENT"
    REG = "REG"
    CLOSE = "CLOSE"
