# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с разрешениями — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetAllConsentsListResponseDataConsentPermissions(StrEnum):
    """GetAllConsentsListResponseDataConsentPermissions values."""

    READACCOUNTSBASIC = "ReadAccountsBasic"
    READACCOUNTSDETAIL = "ReadAccountsDetail"
    READBALANCES = "ReadBalances"
    READSTATEMENTS = "ReadStatements"
    READTRANSACTIONSBASIC = "ReadTransactionsBasic"
    READTRANSACTIONSCREDITS = "ReadTransactionsCredits"
    READTRANSACTIONSDEBITS = "ReadTransactionsDebits"
    READTRANSACTIONSDETAIL = "ReadTransactionsDetail"
    READCUSTOMERDATA = "ReadCustomerData"
    READSBPDATA = "ReadSBPData"
    EDITSBPDATA = "EditSBPData"
    READSBPDATA1C = "ReadSBPData1C"
    EDITSBPDATA1C = "EditSBPData1C"
    CREATEPAYMENTFORSIGN = "CreatePaymentForSign"
    CREATEPAYMENTORDER = "CreatePaymentOrder"
    READACQUIRINGDATA = "ReadAcquiringData"
    MAKEACQUIRINGOPERATION = "MakeAcquiringOperation"
    MANAGEINVOICEDATA = "ManageInvoiceData"
    MANAGEWEBHOOKDATA = "ManageWebhookData"
    MAKECUSTOMER = "MakeCustomer"
    MANAGEGUARANTEE = "ManageGuarantee"
    MANAGEEDODATA = "ManageEdoData"
    READBIAPI = "ReadBiApi"


class GetAllConsentsListResponseDataConsentStatus(StrEnum):
    """GetAllConsentsListResponseDataConsentStatus values."""

    AWAITINGAUTHORISATION = "AwaitingAuthorisation"
    AUTHORISED = "Authorised"
    REJECTED = "Rejected"
    REVOKED = "Revoked"


class CreateNewConsentResponseDataConsentPermissions(StrEnum):
    """CreateNewConsentResponseDataConsentPermissions values."""

    READACCOUNTSBASIC = "ReadAccountsBasic"
    READACCOUNTSDETAIL = "ReadAccountsDetail"
    READBALANCES = "ReadBalances"
    READSTATEMENTS = "ReadStatements"
    READTRANSACTIONSBASIC = "ReadTransactionsBasic"
    READTRANSACTIONSCREDITS = "ReadTransactionsCredits"
    READTRANSACTIONSDEBITS = "ReadTransactionsDebits"
    READTRANSACTIONSDETAIL = "ReadTransactionsDetail"
    READCUSTOMERDATA = "ReadCustomerData"
    READSBPDATA = "ReadSBPData"
    EDITSBPDATA = "EditSBPData"
    READSBPDATA1C = "ReadSBPData1C"
    EDITSBPDATA1C = "EditSBPData1C"
    CREATEPAYMENTFORSIGN = "CreatePaymentForSign"
    CREATEPAYMENTORDER = "CreatePaymentOrder"
    READACQUIRINGDATA = "ReadAcquiringData"
    MAKEACQUIRINGOPERATION = "MakeAcquiringOperation"
    MANAGEINVOICEDATA = "ManageInvoiceData"
    MANAGEWEBHOOKDATA = "ManageWebhookData"
    MAKECUSTOMER = "MakeCustomer"
    MANAGEGUARANTEE = "ManageGuarantee"
    MANAGEEDODATA = "ManageEdoData"
    READBIAPI = "ReadBiApi"


class CreateNewConsentResponseDataConsentStatus(StrEnum):
    """CreateNewConsentResponseDataConsentStatus values."""

    AWAITINGAUTHORISATION = "AwaitingAuthorisation"
    AUTHORISED = "Authorised"
    REJECTED = "Rejected"
    REVOKED = "Revoked"


class CreateNewConsentDataPermissions(StrEnum):
    """CreateNewConsentDataPermissions values."""

    READACCOUNTSBASIC = "ReadAccountsBasic"
    READACCOUNTSDETAIL = "ReadAccountsDetail"
    READBALANCES = "ReadBalances"
    READSTATEMENTS = "ReadStatements"
    READTRANSACTIONSBASIC = "ReadTransactionsBasic"
    READTRANSACTIONSCREDITS = "ReadTransactionsCredits"
    READTRANSACTIONSDEBITS = "ReadTransactionsDebits"
    READTRANSACTIONSDETAIL = "ReadTransactionsDetail"
    READCUSTOMERDATA = "ReadCustomerData"
    READSBPDATA = "ReadSBPData"
    EDITSBPDATA = "EditSBPData"
    CREATEPAYMENTFORSIGN = "CreatePaymentForSign"
    CREATEPAYMENTORDER = "CreatePaymentOrder"
    READACQUIRINGDATA = "ReadAcquiringData"
    MAKEACQUIRINGOPERATION = "MakeAcquiringOperation"
    MANAGEINVOICEDATA = "ManageInvoiceData"
    MANAGEWEBHOOKDATA = "ManageWebhookData"
    MAKECUSTOMER = "MakeCustomer"
    MANAGEGUARANTEE = "ManageGuarantee"
    MANAGEEDODATA = "ManageEdoData"
    READBIAPI = "ReadBiApi"


class GetConsentInfoResponseDataPermissions(StrEnum):
    """GetConsentInfoResponseDataPermissions values."""

    READACCOUNTSBASIC = "ReadAccountsBasic"
    READACCOUNTSDETAIL = "ReadAccountsDetail"
    READBALANCES = "ReadBalances"
    READSTATEMENTS = "ReadStatements"
    READTRANSACTIONSBASIC = "ReadTransactionsBasic"
    READTRANSACTIONSCREDITS = "ReadTransactionsCredits"
    READTRANSACTIONSDEBITS = "ReadTransactionsDebits"
    READTRANSACTIONSDETAIL = "ReadTransactionsDetail"
    READCUSTOMERDATA = "ReadCustomerData"
    READSBPDATA = "ReadSBPData"
    EDITSBPDATA = "EditSBPData"
    CREATEPAYMENTFORSIGN = "CreatePaymentForSign"
    CREATEPAYMENTORDER = "CreatePaymentOrder"
    READACQUIRINGDATA = "ReadAcquiringData"
    MAKEACQUIRINGOPERATION = "MakeAcquiringOperation"
    MANAGEINVOICEDATA = "ManageInvoiceData"
    MANAGEWEBHOOKDATA = "ManageWebhookData"
    MAKECUSTOMER = "MakeCustomer"
    MANAGEGUARANTEE = "ManageGuarantee"
    MANAGEEDODATA = "ManageEdoData"
    READBIAPI = "ReadBiApi"


class GetConsentInfoResponseDataStatus(StrEnum):
    """GetConsentInfoResponseDataStatus values."""

    AWAITINGAUTHORISATION = "AwaitingAuthorisation"
    AUTHORISED = "Authorised"
    REJECTED = "Rejected"
    REVOKED = "Revoked"


class GetAllChildConsentsResponseDataConsentPermissions(StrEnum):
    """GetAllChildConsentsResponseDataConsentPermissions values."""

    READACCOUNTSBASIC = "ReadAccountsBasic"
    READACCOUNTSDETAIL = "ReadAccountsDetail"
    READBALANCES = "ReadBalances"
    READSTATEMENTS = "ReadStatements"
    READTRANSACTIONSBASIC = "ReadTransactionsBasic"
    READTRANSACTIONSCREDITS = "ReadTransactionsCredits"
    READTRANSACTIONSDEBITS = "ReadTransactionsDebits"
    READTRANSACTIONSDETAIL = "ReadTransactionsDetail"
    READCUSTOMERDATA = "ReadCustomerData"
    READSBPDATA = "ReadSBPData"
    EDITSBPDATA = "EditSBPData"
    READSBPDATA1C = "ReadSBPData1C"
    EDITSBPDATA1C = "EditSBPData1C"
    CREATEPAYMENTFORSIGN = "CreatePaymentForSign"
    CREATEPAYMENTORDER = "CreatePaymentOrder"
    READACQUIRINGDATA = "ReadAcquiringData"
    MAKEACQUIRINGOPERATION = "MakeAcquiringOperation"
    MANAGEINVOICEDATA = "ManageInvoiceData"
    MANAGEWEBHOOKDATA = "ManageWebhookData"
    MAKECUSTOMER = "MakeCustomer"
    MANAGEGUARANTEE = "ManageGuarantee"
    MANAGEEDODATA = "ManageEdoData"
    READBIAPI = "ReadBiApi"


class GetAllChildConsentsResponseDataConsentStatus(StrEnum):
    """GetAllChildConsentsResponseDataConsentStatus values."""

    AWAITINGAUTHORISATION = "AwaitingAuthorisation"
    AUTHORISED = "Authorised"
    REJECTED = "Rejected"
    REVOKED = "Revoked"
