# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с ЮЛ — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetAccountsListResponseDataAccountListStatus(StrEnum):
    """GetAccountsListResponseDataAccountListStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"


class GetCustomerInfoResponseDataAccountListStatus(StrEnum):
    """GetCustomerInfoResponseDataAccountListStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"


class GetCustomerInfoResponseDataMerchantListCapabilities(StrEnum):
    """GetCustomerInfoResponseDataMerchantListCapabilities values."""

    V_001 = "001"
    V_010 = "010"
    V_011 = "011"
    V_100 = "100"
    V_101 = "101"
    V_110 = "110"
    V_111 = "111"


class GetCustomerInfoResponseDataMerchantListStatus(StrEnum):
    """GetCustomerInfoResponseDataMerchantListStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"


class GetCustomerInfoResponseDataStatus(StrEnum):
    """GetCustomerInfoResponseDataStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"


class GetLegalEntityResponseDataStatus(StrEnum):
    """GetLegalEntityResponseDataStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"


class SetLegalEntityStatusDataStatus(StrEnum):
    """SetLegalEntityStatusDataStatus values."""

    ACTIVE = "Active"
    SUSPENDED = "Suspended"
