# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с возвратами — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetPaymentsResponseDataPaymentsStatus(StrEnum):
    """GetPaymentsResponseDataPaymentsStatus values."""

    CONFIRMING = "Confirming"
    CONFIRMED = "Confirmed"
    INITIATED = "Initiated"
    ACCEPTING = "Accepting"
    ACCEPTED = "Accepted"
    INPROGRESS = "InProgress"
    REJECTED = "Rejected"
    ERROR = "Error"
    TIMEOUT = "Timeout"


class StartRefundResponseDataStatus(StrEnum):
    """StartRefundResponseDataStatus values."""

    WAITINGFORCLIENTCONFIRM = "WaitingForClientConfirm"
    INITIATED = "Initiated"
    WAITINGFORCONFIRM = "WaitingForConfirm"
    CONFIRMED = "Confirmed"
    WAITINGFORACCEPT = "WaitingForAccept"
    ACCEPTED = "Accepted"
    REJECTED = "Rejected"


class GetRefundDataResponseDataStatus(StrEnum):
    """GetRefundDataResponseDataStatus values."""

    WAITINGFORCLIENTCONFIRM = "WaitingForClientConfirm"
    INITIATED = "Initiated"
    WAITINGFORCONFIRM = "WaitingForConfirm"
    CONFIRMED = "Confirmed"
    WAITINGFORACCEPT = "WaitingForAccept"
    ACCEPTED = "Accepted"
    REJECTED = "Rejected"
