# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с выписками — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetStatementResponseDataStatementTransactionCreditorAccountSchemeName(StrEnum):
    """GetStatementResponseDataStatementTransactionCreditorAccountSchemeName values."""

    RU_CBR_PAN = "RU.CBR.PAN"
    RU_CBR_CELLPHONENUMBER = "RU.CBR.CellphoneNumber"
    RU_CBR_BBAN = "RU.CBR.BBAN"


class GetStatementResponseDataStatementTransactionCreditorAgentSchemeName(StrEnum):
    """GetStatementResponseDataStatementTransactionCreditorAgentSchemeName values."""

    RU_CBR_BICFI = "RU.CBR.BICFI"
    RU_CBR_BIK = "RU.CBR.BIK"


class GetStatementResponseDataStatementTransactionDebtorAccountSchemeName(StrEnum):
    """GetStatementResponseDataStatementTransactionDebtorAccountSchemeName values."""

    RU_CBR_PAN = "RU.CBR.PAN"
    RU_CBR_CELLPHONENUMBER = "RU.CBR.CellphoneNumber"
    RU_CBR_BBAN = "RU.CBR.BBAN"


class GetStatementResponseDataStatementTransactionDebtorAgentSchemeName(StrEnum):
    """GetStatementResponseDataStatementTransactionDebtorAgentSchemeName values."""

    RU_CBR_BICFI = "RU.CBR.BICFI"
    RU_CBR_BIK = "RU.CBR.BIK"


class GetStatementResponseDataStatementTransactionCreditDebitIndicator(StrEnum):
    """GetStatementResponseDataStatementTransactionCreditDebitIndicator values."""

    CREDIT = "Credit"
    DEBIT = "Debit"


class GetStatementResponseDataStatementTransactionStatus(StrEnum):
    """GetStatementResponseDataStatementTransactionStatus values."""

    BOOKED = "Booked"
    PENDING = "Pending"


class GetStatementResponseDataStatementTransactionTransactionTypeCode(StrEnum):
    """GetStatementResponseDataStatementTransactionTransactionTypeCode values."""

    NEOPREDELENNOE_ZNACHENIE = "Неопределенное значение"
    PLATEZHNOE_PORUCHENIE = "Платежное поручение"
    PLATEZHNOE_TREBOVANIE = "Платежное требование"
    DENEZHNYI_CHEK_RKO = "Денежный чек, РКО"
    OBYAVLENIE_NA_VZNOS_NALICHNYMI_PKO = "Объявление на взнос наличными, ПКО"
    TREBOVANIE_PORUCHENIE = "Требование-поручение"
    INKASSOVOE_PORUCHENIE = "Инкассовое поручение"
    RASCHETNYI_CHEK = "Расчетный чек"
    AKKREDITIV = "Аккредитив"
    MEMORIALNYI_ORDER = "Мемориальный ордер"
    POGASHENIE_KREDITA = "Погашение кредита"
    VYDACHA_KREDITA = "Выдача кредита"
    AVIZO = "Авизо"
    BANKOVSKIE_KARTY = "Банковские карты"
    PLATEZHNYI_ORDER = "Платежный ордер"
    BANKOVSKII_ORDER = "Банковский ордер"
    ORDER_PO_PEREDACHE_TSENNOSTEI = "Ордер по передаче ценностей"
    PROGRAMMNYI_ORDER = "Программный ордер"
    IMPORTIROVANNAYA_ZAPIS = "Импортированная запись"


class GetStatementResponseDataStatementStatus(StrEnum):
    """GetStatementResponseDataStatementStatus values."""

    CREATED = "Created"
    PROCESSING = "Processing"
    ERROR = "Error"
    READY = "Ready"


class GetStatementsListResponseDataStatementTransactionCreditorAccountSchemeName(StrEnum):
    """GetStatementsListResponseDataStatementTransactionCreditorAccountSchemeName values."""

    RU_CBR_PAN = "RU.CBR.PAN"
    RU_CBR_CELLPHONENUMBER = "RU.CBR.CellphoneNumber"
    RU_CBR_BBAN = "RU.CBR.BBAN"


class GetStatementsListResponseDataStatementTransactionCreditorAgentSchemeName(StrEnum):
    """GetStatementsListResponseDataStatementTransactionCreditorAgentSchemeName values."""

    RU_CBR_BICFI = "RU.CBR.BICFI"
    RU_CBR_BIK = "RU.CBR.BIK"


class GetStatementsListResponseDataStatementTransactionDebtorAccountSchemeName(StrEnum):
    """GetStatementsListResponseDataStatementTransactionDebtorAccountSchemeName values."""

    RU_CBR_PAN = "RU.CBR.PAN"
    RU_CBR_CELLPHONENUMBER = "RU.CBR.CellphoneNumber"
    RU_CBR_BBAN = "RU.CBR.BBAN"


class GetStatementsListResponseDataStatementTransactionDebtorAgentSchemeName(StrEnum):
    """GetStatementsListResponseDataStatementTransactionDebtorAgentSchemeName values."""

    RU_CBR_BICFI = "RU.CBR.BICFI"
    RU_CBR_BIK = "RU.CBR.BIK"


class GetStatementsListResponseDataStatementTransactionCreditDebitIndicator(StrEnum):
    """GetStatementsListResponseDataStatementTransactionCreditDebitIndicator values."""

    CREDIT = "Credit"
    DEBIT = "Debit"


class GetStatementsListResponseDataStatementTransactionStatus(StrEnum):
    """GetStatementsListResponseDataStatementTransactionStatus values."""

    BOOKED = "Booked"
    PENDING = "Pending"


class GetStatementsListResponseDataStatementTransactionTransactionTypeCode(StrEnum):
    """GetStatementsListResponseDataStatementTransactionTransactionTypeCode values."""

    NEOPREDELENNOE_ZNACHENIE = "Неопределенное значение"
    PLATEZHNOE_PORUCHENIE = "Платежное поручение"
    PLATEZHNOE_TREBOVANIE = "Платежное требование"
    DENEZHNYI_CHEK_RKO = "Денежный чек, РКО"
    OBYAVLENIE_NA_VZNOS_NALICHNYMI_PKO = "Объявление на взнос наличными, ПКО"
    TREBOVANIE_PORUCHENIE = "Требование-поручение"
    INKASSOVOE_PORUCHENIE = "Инкассовое поручение"
    RASCHETNYI_CHEK = "Расчетный чек"
    AKKREDITIV = "Аккредитив"
    MEMORIALNYI_ORDER = "Мемориальный ордер"
    POGASHENIE_KREDITA = "Погашение кредита"
    VYDACHA_KREDITA = "Выдача кредита"
    AVIZO = "Авизо"
    BANKOVSKIE_KARTY = "Банковские карты"
    PLATEZHNYI_ORDER = "Платежный ордер"
    BANKOVSKII_ORDER = "Банковский ордер"
    ORDER_PO_PEREDACHE_TSENNOSTEI = "Ордер по передаче ценностей"
    PROGRAMMNYI_ORDER = "Программный ордер"
    IMPORTIROVANNAYA_ZAPIS = "Импортированная запись"


class GetStatementsListResponseDataStatementStatus(StrEnum):
    """GetStatementsListResponseDataStatementStatus values."""

    CREATED = "Created"
    PROCESSING = "Processing"
    ERROR = "Error"
    READY = "Ready"


class InitStatementResponseDataStatementStatus(StrEnum):
    """InitStatementResponseDataStatementStatus values."""

    CREATED = "Created"
    PROCESSING = "Processing"
    ERROR = "Error"
    READY = "Ready"
