# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с подписками — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetSubscriptionListResponseDataSubscriptionItemsMeasure(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class GetSubscriptionListResponseDataSubscriptionItemsPaymentMethod(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class GetSubscriptionListResponseDataSubscriptionItemsPaymentObject(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class GetSubscriptionListResponseDataSubscriptionItemsVatType(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT20 = "vat20"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT120 = "vat120"
    VAT122 = "vat122"


class GetSubscriptionListResponseDataSubscriptionOptionsPeriod(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionOptionsPeriod values."""

    DAY = "Day"
    MONTH = "Month"
    YEAR = "Year"
    QUARTER = "Quarter"


class GetSubscriptionListResponseDataSubscriptionStatus(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionStatus values."""

    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ON_REFUND = "ON-REFUND"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
    REFUNDED_PARTIALLY = "REFUNDED_PARTIALLY"
    AUTHORIZED = "AUTHORIZED"
    WAIT_FULL_PAYMENT = "WAIT_FULL_PAYMENT"


class GetSubscriptionListResponseDataSubscriptionTaxSystemCode(StrEnum):
    """GetSubscriptionListResponseDataSubscriptionTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"
    ENVD = "envd"


class CreateSubscriptionResponseDataOptionsPeriod(StrEnum):
    """CreateSubscriptionResponseDataOptionsPeriod values."""

    DAY = "Day"
    MONTH = "Month"
    YEAR = "Year"
    QUARTER = "Quarter"


class CreateSubscriptionResponseDataStatus(StrEnum):
    """CreateSubscriptionResponseDataStatus values."""

    CREATED = "CREATED"


class CreateSubscriptionDataOptionsPeriod(StrEnum):
    """CreateSubscriptionDataOptionsPeriod values."""

    DAY = "Day"
    MONTH = "Month"
    YEAR = "Year"


class GetSubscriptionStatusResponseDataStatus(StrEnum):
    """GetSubscriptionStatusResponseDataStatus values."""

    ACTIVE = "Active"
    CANCELLED = "Cancelled"
    COMPLETED = "Completed"
    EXPIRED = "Expired"
    FAILED = "Failed"
    PASTDUE = "PastDue"
    PREPARING = "Preparing"
    REFUSED = "Refused"
    REJECTED = "Rejected"
    SUSPENDED = "Suspended"
    TRIAL = "Trial"


class SetSubscriptionStatusDataStatus(StrEnum):
    """SetSubscriptionStatusDataStatus values."""

    CANCELLED = "Cancelled"


class CreateSubscriptionWithReceiptResponseDataItemsMeasure(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class CreateSubscriptionWithReceiptResponseDataItemsPaymentMethod(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class CreateSubscriptionWithReceiptResponseDataItemsPaymentObject(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class CreateSubscriptionWithReceiptResponseDataItemsVatType(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT122 = "vat122"


class CreateSubscriptionWithReceiptResponseDataOptionsPeriod(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataOptionsPeriod values."""

    DAY = "Day"
    MONTH = "Month"
    YEAR = "Year"
    QUARTER = "Quarter"


class CreateSubscriptionWithReceiptResponseDataStatus(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataStatus values."""

    CREATED = "CREATED"


class CreateSubscriptionWithReceiptResponseDataTaxSystemCode(StrEnum):
    """CreateSubscriptionWithReceiptResponseDataTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"


class CreateSubscriptionWithReceiptDataItemsMeasure(StrEnum):
    """CreateSubscriptionWithReceiptDataItemsMeasure values."""

    G = "г."
    KG = "кг."
    T = "т."
    SM = "см."
    DM = "дм."
    M = "м."
    SM2 = "см2."
    DM2 = "дм2."
    M2 = "м2."
    ML = "мл."
    L_ = "л."
    M3 = "м3"
    KVT_CH = "кВт.ч."
    GKAL = "Гкал."
    DN = "дн."
    CH = "ч."
    MIN = "мин."
    SEK = "сек."
    KB = "Кб."
    MB = "Мб."
    GB = "Гб."
    TB = "Тб."
    SHT = "шт."


class CreateSubscriptionWithReceiptDataItemsPaymentMethod(StrEnum):
    """CreateSubscriptionWithReceiptDataItemsPaymentMethod values."""

    FULL_PAYMENT = "full_payment"
    FULL_PREPAYMENT = "full_prepayment"


class CreateSubscriptionWithReceiptDataItemsPaymentObject(StrEnum):
    """CreateSubscriptionWithReceiptDataItemsPaymentObject values."""

    GOODS = "goods"
    SERVICE = "service"
    WORK = "work"


class CreateSubscriptionWithReceiptDataItemsVatType(StrEnum):
    """CreateSubscriptionWithReceiptDataItemsVatType values."""

    NONE = "none"
    VAT0 = "vat0"
    VAT5 = "vat5"
    VAT7 = "vat7"
    VAT10 = "vat10"
    VAT22 = "vat22"
    VAT105 = "vat105"
    VAT107 = "vat107"
    VAT110 = "vat110"
    VAT122 = "vat122"


class CreateSubscriptionWithReceiptDataOptionsPeriod(StrEnum):
    """CreateSubscriptionWithReceiptDataOptionsPeriod values."""

    DAY = "Day"
    MONTH = "Month"
    YEAR = "Year"


class CreateSubscriptionWithReceiptDataTaxSystemCode(StrEnum):
    """CreateSubscriptionWithReceiptDataTaxSystemCode values."""

    OSN = "osn"
    USN_INCOME = "usn_income"
    USN_INCOME_OUTCOME = "usn_income_outcome"
    ESN = "esn"
    PATENT = "patent"
