# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с вебхуками — domain enums (auto-generated from the Tochka OpenAPI spec)."""

from enum import StrEnum


class GetWebhooksResponseDataWebhooksList(StrEnum):
    """GetWebhooksResponseDataWebhooksList values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"


class EditWebhookResponseDataWebhooksList(StrEnum):
    """EditWebhookResponseDataWebhooksList values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"


class EditWebhookWebhooksList(StrEnum):
    """EditWebhookWebhooksList values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"


class CreateWebhookResponseDataWebhooksList(StrEnum):
    """CreateWebhookResponseDataWebhooksList values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"


class CreateWebhookWebhooksList(StrEnum):
    """CreateWebhookWebhooksList values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"


class SendWebhookWebhookType(StrEnum):
    """SendWebhookWebhookType values."""

    INCOMINGPAYMENT = "incomingPayment"
    OUTGOINGPAYMENT = "outgoingPayment"
    INCOMINGSBPPAYMENT = "incomingSbpPayment"
    ACQUIRINGINTERNETPAYMENT = "acquiringInternetPayment"
    INCOMINGSBPB2BPAYMENT = "incomingSbpB2BPayment"
    CUSTOMWEBHOOK = "customWebhook"
