"""Pure text-emit helpers — import blocks, docstrings, field lines.

No spec knowledge; just turns already-computed specs into source lines. Files are run
through ``ruff format`` afterwards, so spacing here only needs to be valid, not perfect.
"""

from __future__ import annotations

import textwrap
from collections.abc import Iterable

GENERATED_HEADER = "# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.\n"

#: token → import line for the stdlib/house symbols the mapper may emit.
_TYPE_IMPORTS = {
    "datetime": "from datetime import datetime",
    "date": "from datetime import date",
    "TZDatetime": "from .common import TZDatetime",
    "TZDatetime_method": "from ..models.common import TZDatetime",
}


def module_doc(title: str, kind: str, *, see: str | None = None) -> str:
    body = f"{title} — {kind} (auto-generated from the Tochka OpenAPI spec)."
    # 6 = the opening `\"\"\"` plus the closing one, which sits on the same line when the
    # summary fits on one — the common case for a module doc.
    lines = wrap(body, "", first_offset=6)
    rendered = '"""' + "\n".join(lines)
    if see:
        rendered += f"\n\nSee: {see}"
    return f'{rendered}"""\n'


#: `ruff format` never rewraps prose inside a docstring, and the bank's descriptions run to
#: several hundred characters — so wrapping happens here or not at all.
LINE_LIMIT = 110


def wrap(text: str, indent: str, *, hanging: str | None = None, first_offset: int = 0) -> list[str]:
    """Wrap one prose line to `LINE_LIMIT`, indenting continuations by `hanging`.

    `first_offset` accounts for text the caller prepends to the first line — the opening
    `\"\"\"` — which would otherwise push it past the limit by exactly three characters.
    A single unbreakable token (a URL) is left over-long rather than mangled.
    """

    continuation = hanging if hanging is not None else indent
    # Continuations are indented deeper than the first line, so the budget must come from
    # the WIDEST prefix — sizing on `indent` alone overruns every wrapped line by 4.
    prefix = max(len(indent) + first_offset, len(continuation))
    width = max(LINE_LIMIT - prefix, 20)
    wrapped = textwrap.wrap(text, width=width, break_long_words=False, break_on_hyphens=False)
    if not wrapped:
        return []
    return [f"{indent}{wrapped[0]}"] + [f"{continuation}{line}" for line in wrapped[1:]]


def docstring(lines: Iterable[str], indent: str = "    ") -> str:
    body = [ln for ln in lines if ln]
    if not body:
        return ""
    if len(body) == 1 and len(indent) + len(body[0]) + 6 <= LINE_LIMIT:
        return f'{indent}"""{body[0]}"""\n'
    first = wrap(body[0], indent, first_offset=3)
    out = f'{indent}"""{first[0].lstrip()}\n'
    for line in first[1:]:
        out += f"{line}\n"
    for ln in body[1:]:
        out += "\n".join(wrap(ln, indent)) + "\n"
    return out + f'{indent}"""\n'


def class_docstring(
    summary: str,
    section: str,
    items: Iterable[tuple[str, str | None]],
    indent: str = "    ",
    note: str | None = None,
) -> str:
    """Google-style class docstring: summary, an optional ``note`` line, then a section.

    Field descriptions live here (per project convention), never in ``Field(..., description=…)``.
    ``note`` renders one line under the summary — used for the Tochka docs link.
    """

    documented = [(n, d) for n, d in items if d]
    if not documented and not note:
        if len(indent) + len(summary) + 6 <= LINE_LIMIT:
            return f'{indent}"""{summary}"""\n'
        return docstring([summary], indent)

    summary_lines = wrap(summary, indent, first_offset=3)
    out = f'{indent}"""{summary_lines[0].lstrip()}\n'
    for line in summary_lines[1:]:
        out += f"{line}\n"
    if note:
        out += "\n" + "\n".join(wrap(note, indent)) + "\n"
    if documented:
        out += f"\n{indent}{section}:\n"
        item_indent = f"{indent}    "
        for name, desc in documented:
            entry = wrap(f"{name}: {desc}", item_indent, hanging=f"{item_indent}    ")
            out += "\n".join(entry) + "\n"
    return out + f'{indent}"""\n'


def datetime_imports(needs: set[str], *, in_methods: bool) -> list[str]:
    """Return import lines for the datetime/house type tokens actually used."""

    out: list[str] = []
    if "datetime" in needs:
        out.append(_TYPE_IMPORTS["datetime"])
    if "date" in needs:
        out.append(_TYPE_IMPORTS["date"])
    if "TZDatetime" in needs:
        out.append(_TYPE_IMPORTS["TZDatetime_method"] if in_methods else _TYPE_IMPORTS["TZDatetime"])
    return out


def field_line(name: str, annotation: str, assignment: str | None) -> str:
    """Render one field line — bare (``name: T``) when ``assignment`` is ``None``."""

    if assignment is None:
        return f"    {name}: {annotation}\n"
    return f"    {name}: {annotation} = {assignment}\n"
