# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Every generated domain facade, folded into the one base `Client` inherits."""

from __future__ import annotations

from ._base import FacadeBase
from .accounts import AccountsFacade
from .acquiring_authentication import AcquiringAuthenticationFacade
from .acquiring_bank_form import AcquiringBankFormFacade
from .acquiring_cashbox_links import AcquiringCashboxLinksFacade
from .acquiring_confirmation import AcquiringConfirmationFacade
from .acquiring_functional_links import AcquiringFunctionalLinksFacade
from .acquiring_merchant_form import AcquiringMerchantFormFacade
from .acquiring_payment_tokens import AcquiringPaymentTokensFacade
from .acquiring_refunds import AcquiringRefundsFacade
from .acquiring_webhooks import AcquiringWebhooksFacade
from .balances import BalancesFacade
from .beneficiaries import BeneficiariesFacade
from .closing_documents import ClosingDocumentsFacade
from .customer_info import CustomerInfoFacade
from .customers import CustomersFacade
from .deals import DealsFacade
from .express_credits import ExpressCreditsFacade
from .invoices import InvoicesFacade
from .marketplace_orders import MarketplaceOrdersFacade
from .marketplace_recipients import MarketplaceRecipientsFacade
from .nominal_document_uploads import NominalDocumentUploadsFacade
from .nominal_documents import NominalDocumentsFacade
from .nominal_health import NominalHealthFacade
from .nominal_payments import NominalPaymentsFacade
from .nominal_sbp import NominalSbpFacade
from .payment_links import PaymentLinksFacade
from .payments import PaymentsFacade
from .permissions import PermissionsFacade
from .sbp_b2b_qr_codes import SbpB2bQrCodesFacade
from .sbp_cashbox_qr_codes import SbpCashboxQrCodesFacade
from .sbp_legal_entities import SbpLegalEntitiesFacade
from .sbp_merchants import SbpMerchantsFacade
from .sbp_qr_codes import SbpQrCodesFacade
from .sbp_refunds import SbpRefundsFacade
from .statements import StatementsFacade
from .subscriptions import SubscriptionsFacade
from .virtual_accounts import VirtualAccountsFacade
from .webhooks import WebhooksFacade


class GeneratedFacades(
    AccountsFacade,
    AcquiringAuthenticationFacade,
    AcquiringBankFormFacade,
    AcquiringCashboxLinksFacade,
    AcquiringConfirmationFacade,
    AcquiringFunctionalLinksFacade,
    AcquiringMerchantFormFacade,
    AcquiringPaymentTokensFacade,
    AcquiringRefundsFacade,
    AcquiringWebhooksFacade,
    BalancesFacade,
    BeneficiariesFacade,
    ClosingDocumentsFacade,
    CustomerInfoFacade,
    CustomersFacade,
    DealsFacade,
    ExpressCreditsFacade,
    InvoicesFacade,
    MarketplaceOrdersFacade,
    MarketplaceRecipientsFacade,
    NominalDocumentUploadsFacade,
    NominalDocumentsFacade,
    NominalHealthFacade,
    NominalPaymentsFacade,
    NominalSbpFacade,
    PaymentLinksFacade,
    PaymentsFacade,
    PermissionsFacade,
    SbpB2bQrCodesFacade,
    SbpCashboxQrCodesFacade,
    SbpLegalEntitiesFacade,
    SbpMerchantsFacade,
    SbpQrCodesFacade,
    SbpRefundsFacade,
    StatementsFacade,
    SubscriptionsFacade,
    VirtualAccountsFacade,
    WebhooksFacade,
    FacadeBase,
):
    """All domain endpoints on one class — see `tochka.Client`."""
