# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Подтверждение — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.acquiring_confirmation import (
    CreateCaptureApiVersion,
    GetCaptureApiVersion,
    GetCapturesApiVersion,
)
from ..methods.acquiring_confirmation import CreateCapture, GetCapture, GetCaptures
from ..models.acquiring_confirmation import (
    CreateCaptureData,
    CreateCaptureDataAmount,
    CreateCaptureResponse,
    GetCaptureResponse,
    GetCapturesResponse,
)
from ._base import FacadeBase


class AcquiringConfirmationFacade(FacadeBase):
    """``Client`` mixin — Подтверждение endpoints."""

    async def get_captures(
        self, site_uid: str, payment_uid: str, api_version: GetCapturesApiVersion
    ) -> GetCapturesResponse:
        """Получить список попыток подтверждения платежа via ``GET
        /{api_version}/sites/{site_uid}/payments/{payment_uid}/captures``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            api_version: Версия API
        """
        return await self.execute(
            GetCaptures(site_uid=site_uid, payment_uid=payment_uid, api_version=api_version)
        )

    async def create_capture(
        self,
        site_uid: str,
        payment_uid: str,
        api_version: CreateCaptureApiVersion,
        capture_uid: str,
        amount: CreateCaptureDataAmount | None = None,
        callback_url: str | None = None,
        comment: str | None = None,
    ) -> CreateCaptureResponse:
        """Подтвердить платёж после холдирования средств. Данный запрос необходим для подтверждения операции
        при двустадийном сценарии проведения платежа. **Возможно только однократное успешное подтверждение
        платежа.** via ``POST /{api_version}/sites/{site_uid}/payments/{payment_uid}/captures``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            api_version: Версия API
            amount: Информация о сумме операции
            callback_url: URL отправки уведомления об операции
            capture_uid: Идентификатор подтверждения платежа в информационной системе ТСП
            comment: Комментарий
        """
        return await self.execute(
            CreateCapture(
                site_uid=site_uid,
                payment_uid=payment_uid,
                api_version=api_version,
                data=CreateCaptureData(
                    amount=amount, callback_url=callback_url, capture_uid=capture_uid, comment=comment
                ),
            )
        )

    async def get_capture(
        self, site_uid: str, payment_uid: str, capture_uid: str, api_version: GetCaptureApiVersion
    ) -> GetCaptureResponse:
        """Получить статус указанного подтверждения платежа via ``GET
        /{api_version}/sites/{site_uid}/payments/{payment_uid}/captures/{capture_uid}``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            capture_uid: Идентификатор подтверждения платежа в информационной системе ТСП
            api_version: Версия API
        """
        return await self.execute(
            GetCapture(
                site_uid=site_uid, payment_uid=payment_uid, capture_uid=capture_uid, api_version=api_version
            )
        )
