# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платёж через форму мерчанта — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.acquiring_merchant_form import CreatePaymentApiVersion, GetPaymentApiVersion
from ..methods.acquiring_merchant_form import CreatePayment, GetPayment
from ..models.acquiring_merchant_form import (
    CreatePaymentData,
    CreatePaymentDataAmount,
    CreatePaymentDataCustomer,
    CreatePaymentResponse,
    GetPaymentResponse,
)
from ._base import FacadeBase


class AcquiringMerchantFormFacade(FacadeBase):
    """``Client`` mixin — Платёж через форму мерчанта endpoints."""

    async def create_payment(
        self,
        site_uid: str,
        api_version: CreatePaymentApiVersion,
        amount: CreatePaymentDataAmount,
        payment_method: Any,
        payment_uid: str,
        callback_url: str | None = None,
        comment: str | None = None,
        customer: CreatePaymentDataCustomer | None = None,
        metadata: str | None = None,
        order_uid: str | None = None,
    ) -> CreatePaymentResponse:
        """Создать платёжную транзакцию via ``POST /{api_version}/sites/{site_uid}/payments``.

        Args:
            site_uid: ID Сайта
            api_version: Версия API
            amount: Информация о сумме операции
            callback_url: URL отправки уведомления об операции
            comment: Комментарий
            customer: CustomerDTO
            metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
                формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
            order_uid: Уникальный идентификатор заказа в информационной системе ТСП
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
        """
        return await self.execute(
            CreatePayment(
                site_uid=site_uid,
                api_version=api_version,
                data=CreatePaymentData(
                    amount=amount,
                    callback_url=callback_url,
                    comment=comment,
                    customer=customer,
                    metadata=metadata,
                    order_uid=order_uid,
                    payment_method=payment_method,
                    payment_uid=payment_uid,
                ),
            )
        )

    async def get_payment(
        self, site_uid: str, payment_uid: str, api_version: GetPaymentApiVersion
    ) -> GetPaymentResponse:
        """Получить информацию о платёжной транзакции via ``GET
        /{api_version}/sites/{site_uid}/payments/{payment_uid}``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            api_version: Версия API
        """
        return await self.execute(
            GetPayment(site_uid=site_uid, payment_uid=payment_uid, api_version=api_version)
        )
