# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Функциональные ссылки СБП — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.acquiring_functional_links import (
    CreateQrCodeApiVersion,
    GetPaymentsByQrcIdApiVersion,
    GetPaymentsByQrcIdQrcIdType,
    GetQrCodeApiVersion,
    GetQrCodeMediaType,
    GetQrCodeQrcIdType,
    GetTokenizationResultApiVersion,
    GetTokenizationResultQrcIdType,
)
from ..methods.acquiring_functional_links import (
    CreateQrCode,
    GetPaymentsByQrcId,
    GetQrCode,
    GetTokenizationResult,
)
from ..models.acquiring_functional_links import (
    CreateQrCodeResponse,
    GetPaymentsByQrcIdResponse,
    GetQrCodeResponse,
    GetTokenizationResultResponse,
)
from ..pagination import MethodPaginator
from ._base import FacadeBase


class AcquiringFunctionalLinksFacade(FacadeBase):
    """``Client`` mixin — Функциональные ссылки СБП endpoints."""

    async def create_qr_code(
        self, site_uid: str, api_version: CreateQrCodeApiVersion, data: Any
    ) -> CreateQrCodeResponse:
        """Создать Функциональную ссылку СБП via ``POST /{api_version}/sites/{site_uid}/sbp/qrc``.

        Args:
            site_uid: ID Сайта
            api_version: Версия API
        """
        return await self.execute(CreateQrCode(site_uid=site_uid, api_version=api_version, data=data))

    async def get_qr_code(
        self,
        site_uid: str,
        qrc_id: str,
        api_version: GetQrCodeApiVersion,
        qrc_id_type: GetQrCodeQrcIdType,
        media_type: GetQrCodeMediaType | None = None,
        width: int = 300,
        height: int = 300,
    ) -> GetQrCodeResponse:
        """Получить содержимое ранее зарегистрированной Функциональной ссылки СБП via ``GET
        /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}``.

        Args:
            site_uid: ID Сайта
            qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
            api_version: Версия API
            qrc_id_type: Тип идентификатора
            media_type: Формат изображения QR-кода
            width: Ширина изображения QR-кода
            height: Высота изображения QR-кода
        """
        return await self.execute(
            GetQrCode(
                site_uid=site_uid,
                qrc_id=qrc_id,
                api_version=api_version,
                qrc_id_type=qrc_id_type,
                media_type=media_type,
                width=width,
                height=height,
            )
        )

    def get_payments_by_qrc_id(
        self,
        site_uid: str,
        qrc_id: str,
        api_version: GetPaymentsByQrcIdApiVersion,
        qrc_id_type: GetPaymentsByQrcIdQrcIdType,
    ) -> MethodPaginator[GetPaymentsByQrcIdResponse]:
        """Получить платежи по ранее зарегистрированной Функциональной ссылке СБП via ``GET
        /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/payments``.

        Args:
            site_uid: ID Сайта
            qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
            api_version: Версия API
            qrc_id_type: Тип идентификатора
        """
        return self.paginate(
            GetPaymentsByQrcId(
                site_uid=site_uid, qrc_id=qrc_id, api_version=api_version, qrc_id_type=qrc_id_type
            )
        )

    async def get_tokenization_result(
        self,
        site_uid: str,
        qrc_id: str,
        api_version: GetTokenizationResultApiVersion,
        qrc_id_type: GetTokenizationResultQrcIdType,
    ) -> GetTokenizationResultResponse:
        """Получить результат выполнения привязки счёта по ранее зарегистрированной Функциональной ссылке СБП
        via ``GET /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/tokenization/result``.

        Args:
            site_uid: ID Сайта
            qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
            api_version: Версия API
            qrc_id_type: Тип идентификатора
        """
        return await self.execute(
            GetTokenizationResult(
                site_uid=site_uid, qrc_id=qrc_id, api_version=api_version, qrc_id_type=qrc_id_type
            )
        )
