# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""[WIP] Платёж через форму банка — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.acquiring_bank_form import CancelInvoiceApiVersion, CreateInvoiceApiVersion, GetInvoiceApiVersion
from ..methods.acquiring_bank_form import CancelInvoice, CreateInvoice, GetInvoice
from ..models.acquiring_bank_form import (
    CancelInvoiceData,
    CancelInvoiceResponse,
    CreateInvoiceData,
    CreateInvoiceDataAmount,
    CreateInvoiceDataCustomer,
    CreateInvoiceDataPaymentOptions,
    CreateInvoiceDataRedirect,
    CreateInvoiceResponse,
    GetInvoiceResponse,
)
from ._base import FacadeBase


class AcquiringBankFormFacade(FacadeBase):
    """``Client`` mixin — [WIP] Платёж через форму банка endpoints."""

    async def create_invoice(
        self,
        site_uid: str,
        api_version: CreateInvoiceApiVersion,
        amount: CreateInvoiceDataAmount,
        expiration_date_time: str,
        invoice_uid: str,
        callback_url: str | None = None,
        comment: str | None = None,
        customer: CreateInvoiceDataCustomer | None = None,
        metadata: str | None = None,
        order_uid: str | None = None,
        payment_options: CreateInvoiceDataPaymentOptions | None = None,
        redirect: CreateInvoiceDataRedirect | None = None,
    ) -> CreateInvoiceResponse:
        """Создать счёт на оплату via ``POST /{api_version}/sites/{site_uid}/invoices``.

        Args:
            site_uid: ID Сайта
            api_version: Версия API
            amount: Информация о сумме операции
            callback_url: URL отправки уведомления об операции
            comment: Комментарий
            customer: CustomerDTO
            expiration_date_time: Срок действия счёта
            invoice_uid: Уникальный идентификатор счёта
            metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
                формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
            order_uid: Уникальный идентификатор заказа в информационной системе ТСП
            payment_options: Способы оплаты доступные покупателю и их настройка. Если не передать, то
                будут доступны все способы оплаты с настройками по умолчанию.
            redirect: Настройки переадресации покупателя после оплаты
        """
        return await self.execute(
            CreateInvoice(
                site_uid=site_uid,
                api_version=api_version,
                data=CreateInvoiceData(
                    amount=amount,
                    callback_url=callback_url,
                    comment=comment,
                    customer=customer,
                    expiration_date_time=expiration_date_time,
                    invoice_uid=invoice_uid,
                    metadata=metadata,
                    order_uid=order_uid,
                    payment_options=payment_options,
                    redirect=redirect,
                ),
            )
        )

    async def get_invoice(
        self, site_uid: str, invoice_uid: str, api_version: GetInvoiceApiVersion
    ) -> GetInvoiceResponse:
        """Получить информацию о счёте via ``GET /{api_version}/sites/{site_uid}/invoices/{invoice_uid}``.

        Args:
            site_uid: ID Сайта
            invoice_uid: Уникальный идентификатор счёта
            api_version: Версия API
        """
        return await self.execute(
            GetInvoice(site_uid=site_uid, invoice_uid=invoice_uid, api_version=api_version)
        )

    async def cancel_invoice(
        self, site_uid: str, invoice_uid: str, api_version: CancelInvoiceApiVersion, reason: str | None = None
    ) -> CancelInvoiceResponse:
        """Отменить ранее созданный счёт via ``POST
        /{api_version}/sites/{site_uid}/invoices/{invoice_uid}/cancel``.

        Args:
            site_uid: ID Сайта
            invoice_uid: Уникальный идентификатор счёта
            api_version: Версия API
            reason: Причина отмены
        """
        return await self.execute(
            CancelInvoice(
                site_uid=site_uid,
                invoice_uid=invoice_uid,
                api_version=api_version,
                data=CancelInvoiceData(reason=reason),
            )
        )
