# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платёжные токены — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.acquiring_payment_tokens import HandleCardTokenOperationApiVersion
from ..methods.acquiring_payment_tokens import HandleCardTokenOperation
from ..models.acquiring_payment_tokens import HandleCardTokenOperationResponse
from ._base import FacadeBase


class AcquiringPaymentTokensFacade(FacadeBase):
    """``Client`` mixin — Платёжные токены endpoints."""

    async def handle_card_token_operation(
        self, site_uid: str, api_version: HandleCardTokenOperationApiVersion, data: Any
    ) -> HandleCardTokenOperationResponse:
        """Выполняет операции с платёжным токеном карты via ``POST
        /{api_version}/sites/{site_uid}/card-token-operations``.

        Args:
            site_uid: ID Сайта
            api_version: Версия API
        """
        return await self.execute(
            HandleCardTokenOperation(site_uid=site_uid, api_version=api_version, data=data)
        )
