# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Возвраты — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.acquiring_refunds import CreateRefundApiVersion, GetRefundApiVersion, GetRefundsApiVersion
from ..methods.acquiring_refunds import CreateRefund, GetRefund, GetRefunds
from ..models.acquiring_refunds import (
    CreateRefundData,
    CreateRefundDataAmount,
    CreateRefundResponse,
    GetRefundResponse,
    GetRefundsResponse,
)
from ._base import FacadeBase


class AcquiringRefundsFacade(FacadeBase):
    """``Client`` mixin — Возвраты endpoints."""

    async def get_refunds(
        self, site_uid: str, payment_uid: str, api_version: GetRefundsApiVersion
    ) -> GetRefundsResponse:
        """Получить статусы всех возвратов для данного платежа via ``GET
        /{api_version}/sites/{site_uid}/payments/{payment_uid}/refunds``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            api_version: Версия API
        """
        return await self.execute(
            GetRefunds(site_uid=site_uid, payment_uid=payment_uid, api_version=api_version)
        )

    async def create_refund(
        self,
        site_uid: str,
        payment_uid: str,
        api_version: CreateRefundApiVersion,
        refund_uid: str,
        amount: CreateRefundDataAmount | None = None,
        callback_url: str | None = None,
        comment: str | None = None,
        metadata: str | None = None,
    ) -> CreateRefundResponse:
        """Запрос предназначен для возврата средств по платежу via ``POST
        /{api_version}/sites/{site_uid}/payments/{payment_uid}/refunds``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            api_version: Версия API
            amount: Информация о сумме операции
            callback_url: URL отправки уведомления об операции
            comment: Дополнительное описание возврата
            metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
                формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
            refund_uid: Уникальный идентификатор возврата в информационной системе ТСП
        """
        return await self.execute(
            CreateRefund(
                site_uid=site_uid,
                payment_uid=payment_uid,
                api_version=api_version,
                data=CreateRefundData(
                    amount=amount,
                    callback_url=callback_url,
                    comment=comment,
                    metadata=metadata,
                    refund_uid=refund_uid,
                ),
            )
        )

    async def get_refund(
        self, site_uid: str, payment_uid: str, refund_uid: str, api_version: GetRefundApiVersion
    ) -> GetRefundResponse:
        """Получить статус указанного возврата via ``GET
        /{api_version}/sites/{site_uid}/payments/{payment_uid}/refunds/{refund_uid}``.

        Args:
            site_uid: ID Сайта
            payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
            refund_uid: Идентификатор возврата в информационной системе ТСП
            api_version: Версия API
        """
        return await self.execute(
            GetRefund(
                site_uid=site_uid, payment_uid=payment_uid, refund_uid=refund_uid, api_version=api_version
            )
        )
