# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с закрывающими документами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..methods.closing_documents import (
    CreateClosingDocument,
    DeleteClosingDocuments,
    GetClosingDocument,
    SendClosingDocumentsToEmail,
)
from ..models._helpers import _resolve_customer_code
from ..models.closing_documents import (
    CreateClosingDocumentData,
    CreateClosingDocumentDataSecondSide,
    CreateClosingDocumentResponse,
    DeleteClosingDocumentsResponse,
    SendClosingDocumentsToEmailData,
    SendClosingDocumentsToEmailResponse,
)
from ._base import FacadeBase


class ClosingDocumentsFacade(FacadeBase):
    """``Client`` mixin — Работа с закрывающими документами endpoints."""

    async def create_closing_document(
        self,
        content: Any,
        second_side: CreateClosingDocumentDataSecondSide,
        account_id: str,
        customer_code: str,
        document_id: str | None = None,
    ) -> CreateClosingDocumentResponse:
        """Метод для создания закрывающего документа via ``POST /invoice/v1.0/closing-documents``.

        Args:
            content: Содержимое закрывающего документа
            second_side: Сторона заказчика/покупателя в сделке в документе
            account_id: Уникальный и неизменный идентификатор счёта
            customer_code: Уникальный код клиента
            document_id: ID родительского документа
        """
        return await self.execute(
            CreateClosingDocument(
                data=CreateClosingDocumentData(
                    content=content,
                    second_side=second_side,
                    account_id=account_id,
                    customer_code=customer_code,
                    document_id=document_id,
                )
            )
        )

    async def delete_closing_documents(
        self, document_id: str, customer_code: str | None = None
    ) -> DeleteClosingDocumentsResponse:
        """Метод для удаления закрывающего документа via ``DELETE
        /invoice/v1.0/closing-documents/{customer_code}/{document_id}``.

        Args:
            customer_code: Уникальный код клиента
            document_id: Уникальный идентификатор документа
        """
        return await self.execute(
            DeleteClosingDocuments(
                customer_code=_resolve_customer_code(self) if customer_code is None else customer_code,
                document_id=document_id,
            )
        )

    async def send_closing_documents_to_email(
        self, document_id: str, email: str, customer_code: str | None = None
    ) -> SendClosingDocumentsToEmailResponse:
        """Метод для отправки закрывающего документа на почту via ``POST
        /invoice/v1.0/closing-documents/{customer_code}/{document_id}/email``.

        Args:
            customer_code: Уникальный код клиента
            document_id: Уникальный идентификатор документа
            email: Электронная почта, на которую нужно отправить
        """
        return await self.execute(
            SendClosingDocumentsToEmail(
                customer_code=_resolve_customer_code(self) if customer_code is None else customer_code,
                document_id=document_id,
                data=SendClosingDocumentsToEmailData(email=email),
            )
        )

    async def get_closing_document(self, document_id: str, customer_code: str | None = None) -> bytes:
        """Метод для получения файла закрывающего документа via ``GET
        /invoice/v1.0/closing-documents/{customer_code}/{document_id}/file``.

        Args:
            customer_code: Уникальный код клиента
            document_id: Уникальный идентификатор документа
        """
        return await self.execute(
            GetClosingDocument(
                customer_code=_resolve_customer_code(self) if customer_code is None else customer_code,
                document_id=document_id,
            )
        )
