# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.customer_info import GetCustomerInfo
from ..models._helpers import _resolve_customer_code
from ..models.customer_info import GetCustomerInfoResponse
from ._base import FacadeBase


class CustomerInfoFacade(FacadeBase):
    """``Client`` mixin — Работа с клиентами endpoints."""

    async def get_customer_info(self, customer_code: str | None = None) -> GetCustomerInfoResponse:
        """Метод получения информации по конкретному клиенту via ``GET /info/v1.0/customers/{customer_code}``.

        Args:
            customer_code: Идентификатор клиента
        """
        return await self.execute(
            GetCustomerInfo(
                customer_code=_resolve_customer_code(self) if customer_code is None else customer_code
            )
        )
