# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.customers import GetCustomerInfo, GetCustomersList
from ..models._helpers import _resolve_customer_code
from ..models.customers import GetCustomerInfoResponse, GetCustomersListResponse
from ._base import FacadeBase


class CustomersFacade(FacadeBase):
    """``Client`` mixin — Работа с клиентами endpoints."""

    async def get_customers_list(self) -> GetCustomersListResponse:
        """Метод для получения списка доступных клиентов via ``GET /open-banking/v1.0/customers``."""
        return await self.execute(GetCustomersList())

    async def get_customer_info_customers(self, customer_code: str | None = None) -> GetCustomerInfoResponse:
        """Метод для получения информации по конкретному клиенту via ``GET
        /open-banking/v1.0/customers/{customer_code}``.

        Args:
            customer_code: Идентификатор клиента
        """
        return await self.execute(
            GetCustomerInfo(
                customer_code=_resolve_customer_code(self) if customer_code is None else customer_code
            )
        )
