# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с Экспресс кредитами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.express_credits import (
    ActivationRefuseApiVersion,
    ActivationRefuseDataResult,
    LoansChangeApiVersion,
    OfferApiVersion,
)
from ..methods.express_credits import ActivationRefuse, LoansChange, Offer
from ..models.common import TZDatetime
from ..models.express_credits import (
    ActivationRefuseData,
    ActivationRefuseResponse,
    LoansChangeData,
    LoansChangeDataLoans,
    LoansChangeResponse,
    OfferData,
    OfferDataOfferPayload,
    OfferResponse,
)
from ._base import FacadeBase


class ExpressCreditsFacade(FacadeBase):
    """``Client`` mixin — Работа с Экспресс кредитами endpoints."""

    async def activation_refuse(
        self,
        api_version: ActivationRefuseApiVersion,
        application_id: str,
        refuse_reason: str,
        result: ActivationRefuseDataResult,
        risks: dict[str, Any] | None = None,
    ) -> ActivationRefuseResponse:
        """Метод для отказа при активации via ``POST
        /expresscredit/{api_version}/application/activation/refuse``.

        Args:
            api_version: Версия API
            application_id: ID кредитной заявки
            refuse_reason: Причина ошибки
            result: Результат процесса активации
            risks: Risks
        """
        return await self.execute(
            ActivationRefuse(
                api_version=api_version,
                data=ActivationRefuseData(
                    application_id=application_id, refuse_reason=refuse_reason, result=result
                ),
                risks=risks,
            )
        )

    async def loans_change(
        self,
        api_version: LoansChangeApiVersion,
        id: str,
        inn: str,
        loans: list[LoansChangeDataLoans],
        name: str | None = None,
        risks: dict[str, Any] | None = None,
    ) -> LoansChangeResponse:
        """Метод для передачи данных по активному кредиту via ``POST
        /expresscredit/{api_version}/loans_change``.

        Args:
            api_version: Версия API
            id: requestId запроса Точки на кредит
            inn: ИНН компании
            loans: Список кредитов
            name: Наименование клиента
            risks: Risks
        """
        return await self.execute(
            LoansChange(
                api_version=api_version,
                data=LoansChangeData(id=id, inn=inn, loans=loans, name=name),
                risks=risks,
            )
        )

    async def offer(
        self,
        api_version: OfferApiVersion,
        application_id: str,
        approval_deadline_date: TZDatetime,
        company_inn: str,
        offer_payload: OfferDataOfferPayload,
        risks: dict[str, Any] | None = None,
    ) -> OfferResponse:
        """Метод для передачи параметров кредита (предодоба) via ``POST /expresscredit/{api_version}/offer``.

        Args:
            api_version: Версия API
            application_id: ID кредитной заявки
            approval_deadline_date: Дата, до которой действителен оффер
            company_inn: ИНН компании
            offer_payload: Данные по предложению
            risks: Risks
        """
        return await self.execute(
            Offer(
                api_version=api_version,
                data=OfferData(
                    application_id=application_id,
                    approval_deadline_date=approval_deadline_date,
                    company_inn=company_inn,
                    offer_payload=offer_payload,
                ),
                risks=risks,
            )
        )
