# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Заказы — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.marketplace_orders import (
    CreateOrder,
    CreateOrderV2,
    CreateOrderV3,
    GetOrder,
    GetOrderList,
    GetOrderReport,
    GetOrderV2,
    GetOrderV3,
    MakeOrderServicesDecision,
    UpdateOrder,
)
from ..models.marketplace_orders import (
    CreateOrderData,
    CreateOrderDataIncomingPayment,
    CreateOrderDataReceipt,
    CreateOrderDataServices,
    CreateOrderResponse,
    CreateOrderV2Data,
    CreateOrderV2DataIncomingPayment,
    CreateOrderV2DataReceipt,
    CreateOrderV2DataServices,
    CreateOrderV2Response,
    CreateOrderV3Data,
    CreateOrderV3DataIncomingPayment,
    CreateOrderV3DataReceipt,
    CreateOrderV3DataServices,
    CreateOrderV3Response,
    GetOrderListResponse,
    GetOrderReportResponse,
    GetOrderResponse,
    GetOrderV2Response,
    GetOrderV3Response,
    MakeOrderServicesDecisionData,
    MakeOrderServicesDecisionDataDecisions,
    MakeOrderServicesDecisionResponse,
    UpdateOrderData,
    UpdateOrderDataUpdates,
    UpdateOrderResponse,
)
from ..pagination import MethodPaginator
from ._base import FacadeBase


class MarketplaceOrdersFacade(FacadeBase):
    """``Client`` mixin — Заказы endpoints."""

    def get_order_list(self) -> MethodPaginator[GetOrderListResponse]:
        """Получить список заказов via ``GET /medusa/v1.0/orders``."""
        return self.paginate(GetOrderList())

    async def create_order(
        self,
        incoming_payment: CreateOrderDataIncomingPayment,
        services: list[CreateOrderDataServices],
        order_commission: str,
        order_ext_id: str,
        receipt: CreateOrderDataReceipt | None = None,
        receipt_email: str | None = None,
    ) -> CreateOrderResponse:
        """Создать заказ via ``POST /medusa/v1.0/orders``.

        Args:
            incoming_payment: IncomingPayment
            receipt: Информация для чека
            services: Услуги
            order_commission: Комиссия за заказ
            order_ext_id: Внешний идентификатор заказа
            receipt_email: DEPRECATED! Используйте Receipt.email. Почта для отправки чека
        """
        return await self.execute(
            CreateOrder(
                data=CreateOrderData(
                    incoming_payment=incoming_payment,
                    receipt=receipt,
                    services=services,
                    order_commission=order_commission,
                    order_ext_id=order_ext_id,
                    receipt_email=receipt_email,
                )
            )
        )

    async def get_order_report(self, finished_at_gte: str, finished_at_lte: str) -> GetOrderReportResponse:
        """Получить отчет по заказам via ``GET /medusa/v1.0/orders/report``.

        Args:
            finished_at_gte: Finishedatgte
            finished_at_lte: Finishedatlte
        """
        return await self.execute(
            GetOrderReport(finished_at_gte=finished_at_gte, finished_at_lte=finished_at_lte)
        )

    async def get_order(self, order_ext_id: str) -> GetOrderResponse:
        """Получить заказ via ``GET /medusa/v1.0/orders/{order_ext_id}``.

        Args:
            order_ext_id: Внешний идентификатор заказа
        """
        return await self.execute(GetOrder(order_ext_id=order_ext_id))

    async def update_order(
        self, order_ext_id: str, updates: list[UpdateOrderDataUpdates], order_version: int
    ) -> UpdateOrderResponse:
        """Изменить услуги в заказе via ``PATCH /medusa/v1.0/orders/{order_ext_id}``.

        Args:
            order_ext_id: Идентификатор заказа
            updates: Обновления
            order_version: Нужен, чтобы внешний клиент всегда понимал текущее состояние заказа перед
                обновлением. Если версии не сошлись, значит у клиента неактуальное состояние заказа
        """
        return await self.execute(
            UpdateOrder(
                order_ext_id=order_ext_id, data=UpdateOrderData(updates=updates, order_version=order_version)
            )
        )

    async def make_order_services_decision(
        self, order_ext_id: str, decisions: list[MakeOrderServicesDecisionDataDecisions]
    ) -> MakeOrderServicesDecisionResponse:
        """Подтвердить оказание услуги via ``POST /medusa/v1.0/orders/{order_ext_id}/decisions``.

        Args:
            order_ext_id: Идентификатор заказа
            decisions: Решения по услугам заказа
        """
        return await self.execute(
            MakeOrderServicesDecision(
                order_ext_id=order_ext_id, data=MakeOrderServicesDecisionData(decisions=decisions)
            )
        )

    async def create_order_v2(
        self,
        incoming_payment: CreateOrderV2DataIncomingPayment,
        services: list[CreateOrderV2DataServices],
        order_ext_id: str,
        receipt: CreateOrderV2DataReceipt | None = None,
    ) -> CreateOrderV2Response:
        """Создать заказ v2 via ``POST /medusa/v2.0/orders``.

        Args:
            incoming_payment: IncomingPayment
            receipt: Информация для чека
            services: Услуги
            order_ext_id: Внешний идентификатор заказа
        """
        return await self.execute(
            CreateOrderV2(
                data=CreateOrderV2Data(
                    incoming_payment=incoming_payment,
                    receipt=receipt,
                    services=services,
                    order_ext_id=order_ext_id,
                )
            )
        )

    async def get_order_v2(self, order_ext_id: str) -> GetOrderV2Response:
        """Получить заказ v2 via ``GET /medusa/v2.0/orders/{order_ext_id}``.

        Args:
            order_ext_id: Внешний идентификатор заказа
        """
        return await self.execute(GetOrderV2(order_ext_id=order_ext_id))

    async def create_order_v3(
        self,
        incoming_payment: CreateOrderV3DataIncomingPayment,
        services: list[CreateOrderV3DataServices],
        ext_id: str,
        receipt: CreateOrderV3DataReceipt | None = None,
    ) -> CreateOrderV3Response:
        """Создать заказ v3 via ``POST /medusa/v3.0/orders``.

        Args:
            incoming_payment: IncomingPaymentV3
            receipt: Информация для чека
            services: Услуги
            ext_id: Внешний идентификатор заказа
        """
        return await self.execute(
            CreateOrderV3(
                data=CreateOrderV3Data(
                    incoming_payment=incoming_payment, receipt=receipt, services=services, ext_id=ext_id
                )
            )
        )

    async def get_order_v3(self, order_ext_id: str) -> GetOrderV3Response:
        """Получить заказ v3 via ``GET /medusa/v3.0/orders/{order_ext_id}``.

        Args:
            order_ext_id: Внешний идентификатор заказа
        """
        return await self.execute(GetOrderV3(order_ext_id=order_ext_id))
