# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Получатели — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.marketplace_recipients import (
    AddCardRecipientPayoutMethod,
    AddSbpRecipientPayoutMethod,
    CreateRecipient,
    DeleteCardRecipientPayoutMethod,
    DeleteRecipientPayoutMethod,
    GetRecipient,
    GetRecipientV2,
    ListRecipientSbpBanks,
    UpdateRecipient,
)
from ..models.marketplace_recipients import (
    AddCardRecipientPayoutMethodData,
    AddCardRecipientPayoutMethodDataCardPayoutMethod,
    AddCardRecipientPayoutMethodResponse,
    AddSbpRecipientPayoutMethodData,
    AddSbpRecipientPayoutMethodDataSbpPayoutMethod,
    AddSbpRecipientPayoutMethodResponse,
    CreateRecipientData,
    CreateRecipientDataSbp,
    CreateRecipientResponse,
    GetRecipientResponse,
    GetRecipientV2Response,
    ListRecipientSbpBanksResponse,
    UpdateRecipientData,
    UpdateRecipientDataSbp,
    UpdateRecipientResponse,
)
from ._base import FacadeBase


class MarketplaceRecipientsFacade(FacadeBase):
    """``Client`` mixin — Получатели endpoints."""

    async def create_recipient(
        self, ext_id: str, name: str, sbp: CreateRecipientDataSbp | None = None
    ) -> CreateRecipientResponse:
        """Создать получателя via ``POST /medusa/v1.0/recipients``.

        Args:
            sbp: Опциональный блок с данными получателя для выплат через СБП
            ext_id: Идентификатор в рамках Платформы
            name: Используется только для удобства вашего просмотра. Можно класть ваши ID как строку
        """
        return await self.execute(
            CreateRecipient(data=CreateRecipientData(sbp=sbp, ext_id=ext_id, name=name))
        )

    async def list_recipient_sbp_banks(self) -> ListRecipientSbpBanksResponse:
        """Получить список банков-получателей СБП via ``GET /medusa/v1.0/recipients/sbp-banks/``."""
        return await self.execute(ListRecipientSbpBanks())

    async def get_recipient(self, recipient_ext_id: str) -> GetRecipientResponse:
        """Детали о получателе via ``GET /medusa/v1.0/recipients/{recipient_ext_id}``.

        Args:
            recipient_ext_id: Идентификатор получателя
        """
        return await self.execute(GetRecipient(recipient_ext_id=recipient_ext_id))

    async def update_recipient(
        self, recipient_ext_id: str, sbp: UpdateRecipientDataSbp, version: int
    ) -> UpdateRecipientResponse:
        """Обновить получателя via ``PATCH /medusa/v1.0/recipients/{recipient_ext_id}``.

        Args:
            recipient_ext_id: Идентификатор получателя
            sbp: Можно обновить либо телефон, либо ФИО (имя и фамилия обязательны, отчество опционально).
                Если получатель создан без данных СБП, первое обновление допускается исключительно при наличии
                всех полей СБП
            version: Нужна для оптимистичной блокировки. Если версия не совпадёт с актуальной — обновление
                будет отклонено
        """
        return await self.execute(
            UpdateRecipient(
                recipient_ext_id=recipient_ext_id, data=UpdateRecipientData(sbp=sbp, version=version)
            )
        )

    async def add_card_recipient_payout_method(
        self, recipient_id: str, card_payout_method: AddCardRecipientPayoutMethodDataCardPayoutMethod
    ) -> AddCardRecipientPayoutMethodResponse:
        """Добавить карту via ``POST /medusa/v1.0/recipients/{recipient_ext_id}/payout_methods/cards``.

        Args:
            recipient_id: Идентификатор получателя
            card_payout_method: CardPayoutMethod
        """
        return await self.execute(
            AddCardRecipientPayoutMethod(
                recipient_id=recipient_id,
                data=AddCardRecipientPayoutMethodData(card_payout_method=card_payout_method),
            )
        )

    async def delete_card_recipient_payout_method(
        self, recipient_ext_id: str, payout_method_ext_id: str
    ) -> None:
        """Удалить карту via ``DELETE
        /medusa/v1.0/recipients/{recipient_ext_id}/payout_methods/cards/{payout_method_ext_id}``.

        Args:
            recipient_ext_id: Идентификатор получателя
            payout_method_ext_id: Идентификатор метода выплаты
        """
        return await self.execute(
            DeleteCardRecipientPayoutMethod(
                recipient_ext_id=recipient_ext_id, payout_method_ext_id=payout_method_ext_id
            )
        )

    async def add_sbp_recipient_payout_method(
        self, recipient_ext_id: str, sbp_payout_method: AddSbpRecipientPayoutMethodDataSbpPayoutMethod
    ) -> AddSbpRecipientPayoutMethodResponse:
        """Добавить метод выплаты СБП via ``POST
        /medusa/v1.0/recipients/{recipient_ext_id}/payout_methods/sbp``.

        Args:
            recipient_ext_id: Идентификатор получателя, UUID
            sbp_payout_method: SbpPayoutMethod
        """
        return await self.execute(
            AddSbpRecipientPayoutMethod(
                recipient_ext_id=recipient_ext_id,
                data=AddSbpRecipientPayoutMethodData(sbp_payout_method=sbp_payout_method),
            )
        )

    async def delete_recipient_payout_method(self, recipient_ext_id: str, payout_method_ext_id: str) -> None:
        """Удалить метод выплаты via ``DELETE
        /medusa/v1.0/recipients/{recipient_ext_id}/payout_methods/{payout_method_ext_id}``.

        Args:
            recipient_ext_id: Идентификатор получателя
            payout_method_ext_id: Идентификатор метода выплаты
        """
        return await self.execute(
            DeleteRecipientPayoutMethod(
                recipient_ext_id=recipient_ext_id, payout_method_ext_id=payout_method_ext_id
            )
        )

    async def get_recipient_v2(self, recipient_ext_id: str) -> GetRecipientV2Response:
        """Детали о получателе v2 via ``GET /medusa/v2.0/recipients/{recipient_ext_id}``.

        Args:
            recipient_ext_id: Идентификатор получателя
        """
        return await self.execute(GetRecipientV2(recipient_ext_id=recipient_ext_id))
