# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Документы — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..methods.nominal_documents import GetDocumentV2, ListDocumentsV2
from ..models.nominal_documents import (
    GetDocumentV2Params,
    ListDocumentsV2Params,
    ListDocumentsV2ParamsFilters,
)
from ._base import FacadeBase


class NominalDocumentsFacade(FacadeBase):
    """``Client`` mixin — Документы endpoints."""

    async def get_document_v2(self, id: Any, jsonrpc: str, method: str, document_id: str) -> None:
        """Метод возвращает подробную информацию по указанному документу via ``POST
        /v2/jsonrpc/get_document``.

        Args:
            id: JsonRPC id
            document_id: Идентификатор документа
        """
        return await self.execute(
            GetDocumentV2(
                id=id, jsonrpc=jsonrpc, method=method, params=GetDocumentV2Params(document_id=document_id)
            )
        )

    async def list_documents_v2(
        self,
        id: Any,
        jsonrpc: str,
        method: str,
        filters: ListDocumentsV2ParamsFilters | None = None,
        page: int = 1,
        per_page: int = 100,
    ) -> None:
        """Метод возвращает список загруженных документов, соответствующих заданным фильтрам via ``POST
        /v2/jsonrpc/list_documents``.

        Args:
            id: JsonRPC id
            filters: Фильтры
            page: Страница
            per_page: Количество элементов на странице
        """
        return await self.execute(
            ListDocumentsV2(
                id=id,
                jsonrpc=jsonrpc,
                method=method,
                params=ListDocumentsV2Params(filters=filters, page=page, per_page=per_page),
            )
        )
