# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Загрузка документов — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from datetime import date

from ..enums.nominal_document_uploads import (
    UploadDocumentBeneficiaryDocumentType,
    UploadDocumentDealDocumentType,
)
from ..methods.nominal_document_uploads import UploadDocumentBeneficiary, UploadDocumentDeal
from ..models.nominal_document_uploads import UploadDocumentBeneficiaryResponse, UploadDocumentDealResponse
from ._base import FacadeBase


class NominalDocumentUploadsFacade(FacadeBase):
    """``Client`` mixin — Загрузка документов endpoints."""

    async def upload_document_beneficiary(
        self,
        beneficiary_id: str,
        document_type: UploadDocumentBeneficiaryDocumentType,
        document_date: date,
        document_number: str,
    ) -> UploadDocumentBeneficiaryResponse:
        """Загрузка документов для API.  Информацию по загруженным документам можно посмотреть в api_v2.  Все
        запросы должны содержать заголовок Content-Type  Важно: Загружаемые файлы не должны превышать
        размер 25 МБ.  Документы добавляются в систему не сразу, и после вызова метода может произойти
        ошибка. Понять, что документ загрузился успешно, можно через вызов метода api_v2_get_document.
        Некоторые фреймворки по умолчанию отправляют файл в формате multipart/form-data, наша система не
        воспринимает такие запросы. Файл в запросе должен передаваться сразу в теле сообщения. via ``POST
        /upload_document/beneficiary``.

        Args:
            beneficiary_id: Идентификатор бенефициара
            document_type: Тип документа
            document_date: Дата документа
            document_number: Номер документа
        """
        return await self.execute(
            UploadDocumentBeneficiary(
                beneficiary_id=beneficiary_id,
                document_type=document_type,
                document_date=document_date,
                document_number=document_number,
            )
        )

    async def upload_document_deal(
        self,
        beneficiary_id: str,
        deal_id: str,
        document_type: UploadDocumentDealDocumentType,
        document_date: date,
        document_number: str,
    ) -> UploadDocumentDealResponse:
        """Загрузка документов для API.  Информацию по загруженным документам можно посмотреть в api_v2.  Все
        запросы должны содержать заголовок Content-Type  Важно: Загружаемые файлы не должны превышать
        размер 25 МБ. *Документы добавляются в систему не сразу, и после вызова метода может произойти
        ошибка. Понять, что документ загрузился успешно, можно через вызов метода api_v2_get_document*.
        *Некоторые фреймворки по умолчанию отправляют файл в формате multipart/form-data, наша система не
        воспринимает такие запросы. Файл в запросе должен передаваться сразу в теле сообщения.* via ``POST
        /upload_document/deal``.

        Args:
            beneficiary_id: Идентификатор бенефициара
            deal_id: Идентификатор сделки
            document_type: Тип документа
            document_date: Дата документа
            document_number: Номер документа
        """
        return await self.execute(
            UploadDocumentDeal(
                beneficiary_id=beneficiary_id,
                deal_id=deal_id,
                document_type=document_type,
                document_date=document_date,
                document_number=document_number,
            )
        )
