# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платежами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from datetime import date

from ..methods.payments import CreatePaymentForSign, GetPaymentForSignList, GetPaymentStatus
from ..models.payments import (
    CreatePaymentForSignData,
    CreatePaymentForSignResponse,
    GetPaymentForSignListResponse,
    GetPaymentStatusResponse,
)
from ._base import FacadeBase


class PaymentsFacade(FacadeBase):
    """``Client`` mixin — Работа с платежами endpoints."""

    async def get_payment_for_sign_list(self, customer_code: str) -> GetPaymentForSignListResponse:
        """Метод получения списка платежей на подпись via ``GET /payment/v1.0/for-sign``.

        Args:
            customer_code: Уникальный код клиента
        """
        return await self.execute(GetPaymentForSignList(customer_code=customer_code))

    async def create_payment_for_sign(
        self,
        account_code: str,
        bank_code: str,
        counterparty_account_number: str,
        counterparty_bank_bic: str,
        counterparty_name: str,
        payment_amount: float,
        payment_date: date,
        payment_purpose: str,
        budget_payment_code: str | None = None,
        code_purpose: str | None = None,
        counterparty_bank_corr_account: str | None = None,
        counterparty_inn: str | None = None,
        counterparty_kpp: str | None = None,
        email: str | None = None,
        payer_inn: str | None = None,
        payer_kpp: str | None = None,
        payment_number: int | None = None,
        payment_priority: str = "5",
        supplier_bill_id: str | None = None,
        tax_info_document_date: str | None = None,
        tax_info_document_number: str | None = None,
        tax_info_kbk: str | None = None,
        tax_info_okato: str | None = None,
        tax_info_period: str | None = None,
        tax_info_reason_code: str | None = None,
        tax_info_status: str | None = None,
    ) -> CreatePaymentForSignResponse:
        """Метод для создания платежа.  Чтобы платёж прошёл, его нужно будет подписать в интернет-банке.  Если
        вы создаёте платёж за третье лицо, поля `payerINN` и `payerKPP` обязательные для заполнения. Если
        платите за себя в бюджет, поле `payerKPP` становится обязательным.  **Обратите внимание:**
        *paymentDate* нужно заполнить по часовому поясу Москвы. via ``POST /payment/v1.0/for-sign``.

        Args:
            account_code: Номер счёта отправителя
            bank_code: БИК отправителя
            budget_payment_code: Код выплат из бюджета на ФЛ (поле 110)
            code_purpose: Заполняется только при платеже физ лицам на счета:('40810', '40817', '40823',
                '40824', '40826', '423', '30232', '40803', '40813', '40820', '426'). Допустимые значения
                1,2,3,4,5 и пусто
            counterparty_account_number: Счёт получателя
            counterparty_bank_bic: БИК получателя
            counterparty_bank_corr_account: Кор. счёт банка получателя
            counterparty_inn: ИНН получателя
            counterparty_kpp: Допустимые значения \"0\" или 9 значное число
            counterparty_name: Получатель платежа
            email: Email для отправки платежного поручения
            payer_inn: - 10-значный — для юрлиц - 12-значный — для физлиц - \"0\" — если у лица, за
                которого платите, нет ИНН в РФ
            payer_kpp: Обязательное поле при платеже в бюджет или за нерезидента РФ. Значением может быть
                \"0\" или девятизначное число. - Если платите за себя в бюджет на единый налоговый счёт (ЕНС),
                укажите \"0\" - Если это платёж за другое лицо, которое не является налоговым резидентом РФ,
                передайте \"0\" или девятизначное число
            payment_amount: Сумма платежа
            payment_date: Дата платежа, приведенная к часовому поясу Москвы
            payment_number: Номер платежа
            payment_priority: Приоритет платежа
            payment_purpose: Назначение платежа
            supplier_bill_id: Код УИН (поле 22)
            tax_info_document_date: Дата документа (поле 109). Используется стандарт ISO8601. Допустимо
                значение \"0\"
            tax_info_document_number: Номера документа (поле 108)
            tax_info_kbk: КБК (поле 104)
            tax_info_okato: ОКАТО (поле 105)
            tax_info_period: Налоговый период (поле 107). Допустимо значение \"0\"
            tax_info_reason_code: Основание (поле 106)
            tax_info_status: Статус (поле 101)
        """
        return await self.execute(
            CreatePaymentForSign(
                data=CreatePaymentForSignData(
                    account_code=account_code,
                    bank_code=bank_code,
                    budget_payment_code=budget_payment_code,
                    code_purpose=code_purpose,
                    counterparty_account_number=counterparty_account_number,
                    counterparty_bank_bic=counterparty_bank_bic,
                    counterparty_bank_corr_account=counterparty_bank_corr_account,
                    counterparty_inn=counterparty_inn,
                    counterparty_kpp=counterparty_kpp,
                    counterparty_name=counterparty_name,
                    email=email,
                    payer_inn=payer_inn,
                    payer_kpp=payer_kpp,
                    payment_amount=payment_amount,
                    payment_date=payment_date,
                    payment_number=payment_number,
                    payment_priority=payment_priority,
                    payment_purpose=payment_purpose,
                    supplier_bill_id=supplier_bill_id,
                    tax_info_document_date=tax_info_document_date,
                    tax_info_document_number=tax_info_document_number,
                    tax_info_kbk=tax_info_kbk,
                    tax_info_okato=tax_info_okato,
                    tax_info_period=tax_info_period,
                    tax_info_reason_code=tax_info_reason_code,
                    tax_info_status=tax_info_status,
                )
            )
        )

    async def get_payment_status(self, request_id: str) -> GetPaymentStatusResponse:
        """Метод для получения статуса платежа via ``GET /payment/v1.0/status/{request_id}``.

        Args:
            request_id: Идентификатор запроса
        """
        return await self.execute(GetPaymentStatus(request_id=request_id))
