# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платёжными ссылками — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.payment_links import (
    CreatePaymentOperationDataPaymentMode,
    CreatePaymentOperationWithReceiptDataPaymentMode,
    CreatePaymentOperationWithReceiptDataTaxSystemCode,
    GetPaymentOperationListStatus,
)
from ..methods.payment_links import (
    CapturePayment,
    CreatePaymentOperation,
    CreatePaymentOperationWithReceipt,
    GetPaymentOperationInfo,
    GetPaymentOperationList,
    GetPaymentRegistry,
    GetRetailers,
    RefundPaymentOperation,
)
from ..models.payment_links import (
    CapturePaymentResponse,
    CreatePaymentOperationData,
    CreatePaymentOperationResponse,
    CreatePaymentOperationWithReceiptData,
    CreatePaymentOperationWithReceiptDataClient,
    CreatePaymentOperationWithReceiptDataItems,
    CreatePaymentOperationWithReceiptDataSupplier,
    CreatePaymentOperationWithReceiptResponse,
    GetPaymentOperationInfoResponse,
    GetPaymentOperationListResponse,
    GetPaymentRegistryResponse,
    GetRetailersResponse,
    RefundPaymentOperationData,
    RefundPaymentOperationResponse,
)
from ..pagination import MethodPaginator
from ._base import FacadeBase


class PaymentLinksFacade(FacadeBase):
    """``Client`` mixin — Работа с платёжными ссылками endpoints."""

    def get_payment_operation_list(
        self,
        customer_code: str,
        from_date: str | None = None,
        to_date: str | None = None,
        status: GetPaymentOperationListStatus | None = None,
    ) -> MethodPaginator[GetPaymentOperationListResponse]:
        """Метод для получения списка операций  - *CREATED* - Операция создана - *APPROVED* - Операция
        одобрена (оплата прошла успешно) - *ON-REFUND* - Операция заблокирована на время выполнения
        возврата - *REFUNDED* - Осуществлен возврат - *EXPIRED* - Истек срок действия via ``GET
        /acquiring/v1.0/payments``.

        Args:
            customer_code: Уникальный код клиента
            from_date: Начало периода создания операций
            to_date: Конец периода создания операций
            status: Статус операции
        """
        return self.paginate(
            GetPaymentOperationList(
                customer_code=customer_code, from_date=from_date, to_date=to_date, status=status
            )
        )

    async def create_payment_operation(
        self,
        amount: float,
        customer_code: str,
        payment_mode: list[CreatePaymentOperationDataPaymentMode],
        purpose: str,
        consumer_id: str | None = None,
        fail_redirect_url: str | None = None,
        merchant_id: str | None = None,
        payment_link_id: str | None = None,
        pre_authorization: bool | None = None,
        redirect_url: str | None = None,
        save_card: bool | None = None,
        ttl: int = 10080,
    ) -> CreatePaymentOperationResponse:
        """Метод для создания ссылки на оплату via ``POST /acquiring/v1.0/payments``.

        Args:
            amount: Сумма платежа
            consumer_id: Идентификатор покупателя
            customer_code: Уникальный код клиента
            fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
            merchant_id: Идентификатор торговой точки в интернет-эквайринге
            payment_link_id: Уникальный номер заказа
            payment_mode: Способ оплаты
            pre_authorization: Создать платёж с двухэтапной оплатой
            purpose: Назначение платежа
            redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
            save_card: Предложить покупателю сохранить карту
            ttl: Время жизни платёжной ссылки в минутах
        """
        return await self.execute(
            CreatePaymentOperation(
                data=CreatePaymentOperationData(
                    amount=amount,
                    consumer_id=consumer_id,
                    customer_code=customer_code,
                    fail_redirect_url=fail_redirect_url,
                    merchant_id=merchant_id,
                    payment_link_id=payment_link_id,
                    payment_mode=payment_mode,
                    pre_authorization=pre_authorization,
                    purpose=purpose,
                    redirect_url=redirect_url,
                    save_card=save_card,
                    ttl=ttl,
                )
            )
        )

    async def get_payment_operation_info(self, operation_id: str) -> GetPaymentOperationInfoResponse:
        """Метод для получения информации о конкретной операции  - *CREATED* - Операция создана - *APPROVED* -
        Операция одобрена (оплата прошла успешно) - *ON-REFUND* - Операция заблокирована на время
        выполнения возврата - *REFUNDED* - Осуществлен возврат - *EXPIRED* - Истек срок действия via ``GET
        /acquiring/v1.0/payments/{operation_id}``.

        Args:
            operation_id: Идентификатор платежа
        """
        return await self.execute(GetPaymentOperationInfo(operation_id=operation_id))

    async def capture_payment(self, operation_id: str) -> CapturePaymentResponse:
        """Метод для списания средств при двухэтапной оплате via ``POST
        /acquiring/v1.0/payments/{operation_id}/capture``.

        Args:
            operation_id: Идентификатор подписки
        """
        return await self.execute(CapturePayment(operation_id=operation_id))

    async def refund_payment_operation(
        self, operation_id: str, amount: float
    ) -> RefundPaymentOperationResponse:
        """Метод для возврата платежей, созданных через платёжную ссылку Возврат возможен только для платежа
        со статусом APPROVED via ``POST /acquiring/v1.0/payments/{operation_id}/refund``.

        Args:
            operation_id: Идентификатор платежа
            amount: Не больше суммы оплаты
        """
        return await self.execute(
            RefundPaymentOperation(operation_id=operation_id, data=RefundPaymentOperationData(amount=amount))
        )

    async def create_payment_operation_with_receipt(
        self,
        client: CreatePaymentOperationWithReceiptDataClient,
        items: list[CreatePaymentOperationWithReceiptDataItems],
        amount: float,
        customer_code: str,
        payment_mode: list[CreatePaymentOperationWithReceiptDataPaymentMode],
        purpose: str,
        supplier: CreatePaymentOperationWithReceiptDataSupplier | None = None,
        consumer_id: str | None = None,
        fail_redirect_url: str | None = None,
        merchant_id: str | None = None,
        payment_link_id: str | None = None,
        pre_authorization: bool | None = None,
        redirect_url: str | None = None,
        save_card: bool | None = None,
        tax_system_code: CreatePaymentOperationWithReceiptDataTaxSystemCode | None = None,
        ttl: int = 10080,
    ) -> CreatePaymentOperationWithReceiptResponse:
        """Метод для создания ссылки на оплату и отправки чека via ``POST
        /acquiring/v1.0/payments_with_receipt``.

        Args:
            client: Данные покупателя
            items: Список товаров в заказе
            supplier: Данные поставщика
            amount: Сумма платежа
            consumer_id: Идентификатор покупателя
            customer_code: Уникальный код клиента
            fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
            merchant_id: Идентификатор торговой точки в интернет-эквайринге
            payment_link_id: Уникальный номер заказа
            payment_mode: Способ оплаты
            pre_authorization: Создать платёж с двухэтапной оплатой
            purpose: Назначение платежа
            redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
            save_card: Предложить покупателю сохранить карту
            tax_system_code: Система налогообложения
            ttl: Время жизни платёжной ссылки в минутах
        """
        return await self.execute(
            CreatePaymentOperationWithReceipt(
                data=CreatePaymentOperationWithReceiptData(
                    client=client,
                    items=items,
                    supplier=supplier,
                    amount=amount,
                    consumer_id=consumer_id,
                    customer_code=customer_code,
                    fail_redirect_url=fail_redirect_url,
                    merchant_id=merchant_id,
                    payment_link_id=payment_link_id,
                    payment_mode=payment_mode,
                    pre_authorization=pre_authorization,
                    purpose=purpose,
                    redirect_url=redirect_url,
                    save_card=save_card,
                    tax_system_code=tax_system_code,
                    ttl=ttl,
                )
            )
        )

    async def get_payment_registry(
        self, customer_code: str, merchant_id: str, date_: str, payment_id: str | None = None
    ) -> GetPaymentRegistryResponse:
        """Метод для получения реестра платежей по интернет-эквайрингу via ``GET /acquiring/v1.0/registry``.

        Args:
            customer_code: Уникальный код клиента
            merchant_id: Идентификатор торговой точки в интернет-эквайринге
            payment_id: Уникальный идентификатор платежа, по которому произошла транзакция
            date_: Дата реестра
        """
        return await self.execute(
            GetPaymentRegistry(
                customer_code=customer_code, merchant_id=merchant_id, payment_id=payment_id, date_=date_
            )
        )

    async def get_retailers(self, customer_code: str) -> GetRetailersResponse:
        """Метод для получения информации о ретейлере  - *NEW* - Ретейлер создан - *ADDRESS_DADATA* - Адрес
        уточнен - *OPEN_ACCOUNT* - Счёт открыт - *TWPG_SENDED* - Данные мерчанта и терминала отправлены в
        процессинг - *RETAILER_CREATED* - Мерчант создан в процессинге - *TERMINAL_CREATED* - Терминал
        создан в процессинге - *FILE_SENT* - файл отправлен в НСПК - *REG* - Зарегистрирован - *CLOSE* -
        Закрыт via ``GET /acquiring/v1.0/retailers``.

        Args:
            customer_code: Уникальный код клиента
        """
        return await self.execute(GetRetailers(customer_code=customer_code))
