# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с разрешениями — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.permissions import CreateNewConsentDataPermissions
from ..methods.permissions import CreateNewConsent, GetAllChildConsents, GetAllConsentsList, GetConsentInfo
from ..models.common import TZDatetime
from ..models.permissions import (
    CreateNewConsentData,
    CreateNewConsentResponse,
    GetAllChildConsentsResponse,
    GetAllConsentsListResponse,
    GetConsentInfoResponse,
)
from ._base import FacadeBase


class PermissionsFacade(FacadeBase):
    """``Client`` mixin — Работа с разрешениями endpoints."""

    async def get_all_consents_list(self) -> GetAllConsentsListResponse:
        """Метод для получения списка разрешений. via ``GET /consent/v1.0/consents``."""
        return await self.execute(GetAllConsentsList())

    async def create_new_consent(
        self,
        permissions: list[CreateNewConsentDataPermissions],
        creation_date_time: TZDatetime | None = None,
        expiration_date_time: TZDatetime | None = None,
        status: str = "AwaitingAuthorisation",
        status_update_date_time: TZDatetime | None = None,
        risks: dict[str, Any] | None = None,
    ) -> CreateNewConsentResponse:
        """Метод для создания разрешения. via ``POST /consent/v1.0/consents``.

        Args:
            creation_date_time: Дата и время создания статуса ресурса. Используется стандарт ISO8601
            expiration_date_time: Дата и время истечения срока действия разрешений. Используется стандарт
                ISO8601
            permissions: Указание типов данных доступа.
            status: Статус разрешения
            status_update_date_time: Дата и время обновления статуса ресурса. Используется стандарт
                ISO8601
            risks: Risks
        """
        return await self.execute(
            CreateNewConsent(
                data=CreateNewConsentData(
                    creation_date_time=creation_date_time,
                    expiration_date_time=expiration_date_time,
                    permissions=permissions,
                    status=status,
                    status_update_date_time=status_update_date_time,
                ),
                risks=risks,
            )
        )

    async def get_consent_info(self, consent_id: str) -> GetConsentInfoResponse:
        """Метод для получения информации о списке разрешений via ``GET /consent/v1.0/consents/{consent_id}``.

        Args:
            consent_id: Уникальный идентификатор, предназначенный для идентификации разрешения
        """
        return await self.execute(GetConsentInfo(consent_id=consent_id))

    async def get_all_child_consents(self, consent_id: str) -> GetAllChildConsentsResponse:
        """Метод для получения всех дочерних разрешений via ``GET /consent/v1.0/consents/{consent_id}/child``.

        Args:
            consent_id: Уникальный идентификатор, предназначенный для идентификации разрешения
        """
        return await self.execute(GetAllChildConsents(consent_id=consent_id))
