# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с возвратами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.sbp_refunds import GetPayments, GetRefundData, StartRefund
from ..models.sbp_refunds import (
    GetPaymentsResponse,
    GetRefundDataResponse,
    StartRefundData,
    StartRefundResponse,
)
from ..pagination import MethodPaginator
from ._base import FacadeBase


class SbpRefundsFacade(FacadeBase):
    """``Client`` mixin — Сервис СБП: Работа с возвратами endpoints."""

    def get_payments(
        self,
        customer_code: str,
        qrc_id: str | None = None,
        from_date: str = "Вчера и сегодня",
        to_date: str | None = None,
    ) -> MethodPaginator[GetPaymentsResponse]:
        """Метод для получения списка платежей в Системе быстрых платежей  Обратите внимание: при поиске
        платежей за прошедшие дни обязательно передавать атрибут `fromDate` с указанием начальной даты
        периода. Если этот атрибут не передать, поиск выдаст результаты только за вчерашний и сегодняшний
        дни. via ``GET /sbp/v1.0/get-sbp-payments``.

        Args:
            customer_code: Уникальный код клиента
            qrc_id: ID qr-кода для фильтрации
            from_date: Начало периода для запроса статусов платежей. При отсутствии параметра в запросе
                будет задано дефолтное значение
            to_date: Конец периода для запроса статусов платежей
        """
        return self.paginate(
            GetPayments(customer_code=customer_code, qrc_id=qrc_id, from_date=from_date, to_date=to_date)
        )

    async def start_refund(
        self,
        account_code: str,
        amount: str,
        bank_code: str,
        qrc_id: str,
        currency: str = "RUB",
        purpose: str | None = None,
        ref_transaction_id: str | None = None,
        trx_id: str | None = None,
    ) -> StartRefundResponse:
        """Метод запрашивает возврат платежа через Систему быстрых платежей  Если нужно вернуть деньги
        нерезиденту, назначение платежа должно начинаться с «{VO99020} Возврат ошибочно полученной суммы
        transactionId», где `transactionId` — это идентификатор оригинальной операции. via ``POST
        /sbp/v1.0/refund``.

        Args:
            account_code: Уникальный и неизменный идентификатор счёта
            amount: Cумма операции в рублях
            bank_code: БИК отправителя
            currency: Валюта операции
            purpose: Назначение платежа
            qrc_id: ID qr-кода, по которому был сделан платеж
            ref_transaction_id: Идентификатор транзакции, по которой осуществляется возврат
            trx_id: Идентификатор операции в НСПК, по которой можно осуществить возврат
        """
        return await self.execute(
            StartRefund(
                data=StartRefundData(
                    account_code=account_code,
                    amount=amount,
                    bank_code=bank_code,
                    currency=currency,
                    purpose=purpose,
                    qrc_id=qrc_id,
                    ref_transaction_id=ref_transaction_id,
                    trx_id=trx_id,
                )
            )
        )

    async def get_refund_data(self, request_id: str) -> GetRefundDataResponse:
        """Метод для получения информация о платеже-возврате по Системе быстрых платежей via ``GET
        /sbp/v1.0/refund/{request_id}``.

        Args:
            request_id: ID запроса
        """
        return await self.execute(GetRefundData(request_id=request_id))
