# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с кассовыми QR-кодами — client facade mixin (auto-generated from the Tochka OpenAPI
spec)."""

from __future__ import annotations

from ..methods.sbp_cashbox_qr_codes import (
    ActivateCashboxQrcode,
    ChangeCashboxQrcodeAccount,
    DeactivateCashboxQrcode,
    GetCashboxQrcode,
    GetCashboxQrcodeList,
    GetCashboxQrcodeOperationInfo,
    GetCashboxQrcodeStatus,
    RegisterCashboxQrcode,
)
from ..models.sbp_cashbox_qr_codes import (
    ActivateCashboxQrcodeData,
    ActivateCashboxQrcodeResponse,
    ChangeCashboxQrcodeAccountData,
    ChangeCashboxQrcodeAccountResponse,
    DeactivateCashboxQrcodeResponse,
    GetCashboxQrcodeData,
    GetCashboxQrcodeDataImageParams,
    GetCashboxQrcodeListResponse,
    GetCashboxQrcodeOperationInfoResponse,
    GetCashboxQrcodeResponse,
    GetCashboxQrcodeStatusResponse,
    RegisterCashboxQrcodeData,
    RegisterCashboxQrcodeDataImageParams,
    RegisterCashboxQrcodeResponse,
)
from ._base import FacadeBase


class SbpCashboxQrCodesFacade(FacadeBase):
    """``Client`` mixin — Сервис СБП: Работа с кассовыми QR-кодами endpoints."""

    async def register_cashbox_qrcode(
        self,
        account_id: str,
        merchant_id: str,
        image_params: RegisterCashboxQrcodeDataImageParams | None = None,
        redirect_url: str | None = None,
    ) -> RegisterCashboxQrcodeResponse:
        """Метод для регистрации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code``.

        Args:
            account_id: Уникальный и неизменный идентификатор счёта
            image_params: Параметры изображения
            merchant_id: Идентификатор ТСП
            redirect_url: Ссылка для автоматического возврата плательщика из приложения банка в приложение
                или на сайт ТСП
        """
        return await self.execute(
            RegisterCashboxQrcode(
                data=RegisterCashboxQrcodeData(
                    account_id=account_id,
                    image_params=image_params,
                    merchant_id=merchant_id,
                    redirect_url=redirect_url,
                )
            )
        )

    async def get_cashbox_qrcode_list(
        self, merchant_id: str, account_id: str
    ) -> GetCashboxQrcodeListResponse:
        """Метод для получения списка кассовых QR-кодов via ``GET
        /sbp/v1.0/cashbox-qr-code/merchant/{merchant_id}/{account_id}``.

        Args:
            merchant_id: Идентификатор ТСП
            account_id: Уникальный и неизменный идентификатор счёта
        """
        return await self.execute(GetCashboxQrcodeList(merchant_id=merchant_id, account_id=account_id))

    async def get_cashbox_qrcode(
        self, qrc_id: str, image_params: GetCashboxQrcodeDataImageParams | None = None
    ) -> GetCashboxQrcodeResponse:
        """Метод для получения информации о кассовом QR-коде via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
            image_params: QrCodeImageParams
        """
        return await self.execute(
            GetCashboxQrcode(qrc_id=qrc_id, data=GetCashboxQrcodeData(image_params=image_params))
        )

    async def change_cashbox_qrcode_account(
        self, qrc_id: str, account_id: str
    ) -> ChangeCashboxQrcodeAccountResponse:
        """Метод для смены счёта зачисления кассового QR-кода via ``POST
        /sbp/v1.0/cashbox-qr-code/{qrc_id}/account``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
            account_id: Уникальный и неизменный идентификатор счёта
        """
        return await self.execute(
            ChangeCashboxQrcodeAccount(
                qrc_id=qrc_id, data=ChangeCashboxQrcodeAccountData(account_id=account_id)
            )
        )

    async def activate_cashbox_qrcode(
        self,
        qrc_id: str,
        amount: int,
        currency: str = "RUB",
        payment_purpose: str | None = None,
        ttl: int = 5,
    ) -> ActivateCashboxQrcodeResponse:
        """Метод для активации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}/activate``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
            amount: Сумма в копейках.
            currency: Валюта операции
            payment_purpose: Назначение платежа
            ttl: Период использования QR-кода в минутах
        """
        return await self.execute(
            ActivateCashboxQrcode(
                qrc_id=qrc_id,
                data=ActivateCashboxQrcodeData(
                    amount=amount, currency=currency, payment_purpose=payment_purpose, ttl=ttl
                ),
            )
        )

    async def deactivate_cashbox_qrcode(self, qrc_id: str) -> DeactivateCashboxQrcodeResponse:
        """Метод для деактивации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}/deactivate``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
        """
        return await self.execute(DeactivateCashboxQrcode(qrc_id=qrc_id))

    async def get_cashbox_qrcode_operation_info(
        self, qrc_id: str, params_id: str
    ) -> GetCashboxQrcodeOperationInfoResponse:
        """Метод для получения статуса кассового QR-кода. via ``GET
        /sbp/v1.0/cashbox-qr-code/{qrc_id}/operation``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
            params_id: Идентификатор активных значений параметров QR-кода
        """
        return await self.execute(GetCashboxQrcodeOperationInfo(qrc_id=qrc_id, params_id=params_id))

    async def get_cashbox_qrcode_status(self, qrc_id: str) -> GetCashboxQrcodeStatusResponse:
        """Метод для получения статуса кассового QR-кода. via ``GET
        /sbp/v1.0/cashbox-qr-code/{qrc_id}/status``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
        """
        return await self.execute(GetCashboxQrcodeStatus(qrc_id=qrc_id))
