# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: работа с B2B QR-кодами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.sbp_b2b_qr_codes import GetB2bQrCode, RegisterB2bQrCode
from ..models.sbp_b2b_qr_codes import GetB2bQrCodeResponse, RegisterB2bQrCodeData, RegisterB2bQrCodeResponse
from ._base import FacadeBase


class SbpB2bQrCodesFacade(FacadeBase):
    """``Client`` mixin — Сервис СБП: работа с B2B QR-кодами endpoints."""

    async def register_b2b_qr_code(
        self,
        account_id: str,
        merchant_id: str,
        amount: int,
        payment_purpose: str,
        source_name: str,
        take_tax: bool,
        redirect_url: str | None = None,
        total_tax_amount: int | None = None,
        ttl: int = 4320,
        uip: str | None = None,
    ) -> RegisterB2bQrCodeResponse:
        """Метод для регистрации B2B QR-кода в Системе быстрых платежей via ``POST
        /sbp/v1.0/b2b-qr-code/merchant/{merchant_id}/{account_id}``.

        Args:
            account_id: Уникальный и неизменный идентификатор счёта юрлица
            merchant_id: Идентификатор ТСП
            amount: Сумма в копейках
            payment_purpose: Назначение платежа
            redirect_url: Ссылка для автоматического возврата плательщика из приложения банка в приложение
                или на сайт ТСП
            source_name: Система, создавшая QR-код
            take_tax: Наличие НДС
            total_tax_amount: Сумма НДС в копейках
            ttl: Период использования в минутах
            uip: Уникальный идентификатор платежа, назначаемый получателем
        """
        return await self.execute(
            RegisterB2bQrCode(
                account_id=account_id,
                merchant_id=merchant_id,
                data=RegisterB2bQrCodeData(
                    amount=amount,
                    payment_purpose=payment_purpose,
                    redirect_url=redirect_url,
                    source_name=source_name,
                    take_tax=take_tax,
                    total_tax_amount=total_tax_amount,
                    ttl=ttl,
                    uip=uip,
                ),
            )
        )

    async def get_b2b_qr_code(
        self, qrc_id: str, width: int | None = None, height: int | None = None
    ) -> GetB2bQrCodeResponse:
        """Метод для получения информации о B2B QR-коде via ``GET /sbp/v1.0/b2b-qr-code/{qrc_id}``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
            width: Ширина изображения (по умолчанию: 300)
            height: Высота изображения (по умолчанию: 300)
        """
        return await self.execute(GetB2bQrCode(qrc_id=qrc_id, width=width, height=height))
