# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с QR-кодами — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.sbp_qr_codes import RegisterQrCodeDataQrcType
from ..methods.sbp_qr_codes import GetQrCode, GetQrCodesList, GetQrCodesPaymentStatus, RegisterQrCode
from ..models.sbp_qr_codes import (
    GetQrCodeResponse,
    GetQrCodesListResponse,
    GetQrCodesPaymentStatusResponse,
    RegisterQrCodeData,
    RegisterQrCodeDataImageParams,
    RegisterQrCodeResponse,
)
from ._base import FacadeBase


class SbpQrCodesFacade(FacadeBase):
    """``Client`` mixin — Сервис СБП: Работа с QR-кодами endpoints."""

    async def get_qr_codes_list(self, legal_id: str) -> GetQrCodesListResponse:
        """Метод для получения списка QR-кодов via ``GET /sbp/v1.0/qr-code/legal-entity/{legal_id}``.

        Args:
            legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        """
        return await self.execute(GetQrCodesList(legal_id=legal_id))

    async def register_qr_code(
        self,
        account_id: str,
        merchant_id: str,
        payment_purpose: str,
        qrc_type: RegisterQrCodeDataQrcType,
        amount: int | None = None,
        currency: str | None = None,
        image_params: RegisterQrCodeDataImageParams | None = None,
        redirect_url: str | None = None,
        source_name: str | None = None,
        ttl: int | None = None,
    ) -> RegisterQrCodeResponse:
        """Метод для регистрации статического или динамического QR-кода в Системе быстрых платежей via ``POST
        /sbp/v1.0/qr-code/merchant/{merchant_id}/{account_id}``.

        Args:
            account_id: Уникальный и неизменный идентификатор счёта юрлица
            merchant_id: Идентификатор ТСП
            amount: Поле обязательно для заполнения, если тип QR = QR-Dynamic
            currency: Валюта операции
            image_params: Параметры изображения
            payment_purpose: Назначение платежа
            qrc_type: 01 - QR-Static (QR наклейка) 02 - QR-Dynamic (QR на кассе)
            redirect_url: Ссылка для автоматического возврата плательщика из приложения банка в приложение
                или на сайт ТСП
            source_name: Cистема, создавшая QR-код
            ttl: Задается, только если тип QR = QR-Dynamic
        """
        return await self.execute(
            RegisterQrCode(
                account_id=account_id,
                merchant_id=merchant_id,
                data=RegisterQrCodeData(
                    amount=amount,
                    currency=currency,
                    image_params=image_params,
                    payment_purpose=payment_purpose,
                    qrc_type=qrc_type,
                    redirect_url=redirect_url,
                    source_name=source_name,
                    ttl=ttl,
                ),
            )
        )

    async def get_qr_code_sbp_qr_codes(self, qrc_id: str) -> GetQrCodeResponse:
        """Метод для получения информации о QR-коде via ``GET /sbp/v1.0/qr-code/{qrc_id}``.

        Args:
            qrc_id: Идентификатор QR-кода в СБП
        """
        return await self.execute(GetQrCode(qrc_id=qrc_id))

    async def get_qr_codes_payment_status(self, qrc_ids: str) -> GetQrCodesPaymentStatusResponse:
        """Метод для получения статусов операций по динамическим QR-кодам via ``GET
        /sbp/v1.0/qr-codes/{qrc_ids}/payment-status``.

        Args:
            qrc_ids: Список qr-кодов для запроса статусов, разделенных через запятую
        """
        return await self.execute(GetQrCodesPaymentStatus(qrc_ids=qrc_ids))
