# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с выписками — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..methods.statements import GetStatement, GetStatementsList, InitStatement
from ..models.statements import (
    GetStatementResponse,
    GetStatementsListResponse,
    InitStatementData,
    InitStatementDataStatement,
    InitStatementResponse,
)
from ._base import FacadeBase


class StatementsFacade(FacadeBase):
    """``Client`` mixin — Работа с выписками endpoints."""

    async def get_statement(self, account_id: str, statement_id: str) -> GetStatementResponse:
        """Метод для получения конкретной выписки  После вызова метода `Init Statement` с помощью
        `statementId` можно отследить,на каком этапе создание определённой выписки.  Есть три статуса:
        *Created* — создан запрос на выписку; *Processing* — запрос в обработке; *Ready* — выписка готова.
        **Особенности:** Метод *Init Statement* отрабатывает асинхронно.Отражаются только операции,
        находящиеся в финальном статусе — *Ready*. via ``GET
        /open-banking/v1.0/accounts/{account_id}/statements/{statement_id}``.

        Args:
            account_id: Идентификатор счета
            statement_id: Идентификатор выписки
        """
        return await self.execute(GetStatement(account_id=account_id, statement_id=statement_id))

    async def get_statements_list(self, limit: int = 5) -> GetStatementsListResponse:
        """Метод для получения списка доступных выписок  После вызова метода `Init Statement` можно отследить,
        в каком статусе готовящаяся выписка: *Created* — только создан запрос на выписку; *Processing* —
        запрос в обработке; *Ready* — выписка готова.  **Особенности:** Отражаются только операции,
        находящиеся в финальном статусе — *Ready*. via ``GET /open-banking/v1.0/statements``.

        Args:
            limit: Максимальное количество выписок в ответе
        """
        return await self.execute(GetStatementsList(limit=limit))

    async def init_statement(self, statement: InitStatementDataStatement) -> InitStatementResponse:
        """Метод для создания выписки по конкретному счёту via ``POST /open-banking/v1.0/statements``.

        Args:
            statement: StatementInitReqModel
        """
        return await self.execute(InitStatement(data=InitStatementData(statement=statement)))
