# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с вебхуками — client facade mixin (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from ..enums.webhooks import CreateWebhookWebhooksList, EditWebhookWebhooksList, SendWebhookWebhookType
from ..methods.webhooks import CreateWebhook, DeleteWebhook, EditWebhook, GetWebhooks, SendWebhook
from ..models.webhooks import (
    CreateWebhookResponse,
    DeleteWebhookResponse,
    EditWebhookResponse,
    GetWebhooksResponse,
    SendWebhookResponse,
)
from ._base import FacadeBase


class WebhooksFacade(FacadeBase):
    """``Client`` mixin — Работа с вебхуками endpoints."""

    async def delete_webhook(self, client_id: str) -> DeleteWebhookResponse:
        """Метод для удаления вебхука via ``DELETE /webhook/v1.0/{client_id}``.

        Args:
            client_id: Уникальный идентификатор приложения
        """
        return await self.execute(DeleteWebhook(client_id=client_id))

    async def get_webhooks(self, client_id: str) -> GetWebhooksResponse:
        """Метод для получения списка вебхуков приложения via ``GET /webhook/v1.0/{client_id}``.

        Args:
            client_id: Уникальный идентификатор приложения
        """
        return await self.execute(GetWebhooks(client_id=client_id))

    async def edit_webhook(
        self, client_id: str, url: str, webhooks_list: list[EditWebhookWebhooksList]
    ) -> EditWebhookResponse:
        """Метод для изменения URL и типа вебхука via ``POST /webhook/v1.0/{client_id}``.

        Args:
            client_id: Уникальный идентификатор приложения
            url: url на который необходимо отправлять запрос
            webhooks_list: Новый список событий, на которые нужно подписаться
        """
        return await self.execute(EditWebhook(client_id=client_id, url=url, webhooks_list=webhooks_list))

    async def create_webhook(
        self, client_id: str, url: str, webhooks_list: list[CreateWebhookWebhooksList]
    ) -> CreateWebhookResponse:
        """Метод для создания вебхуков via ``PUT /webhook/v1.0/{client_id}``.

        Args:
            client_id: Уникальный идентификатор приложения
            url: url на который необходимо отправлять запрос
            webhooks_list: Список событий, на которое подписано приложение
        """
        return await self.execute(CreateWebhook(client_id=client_id, url=url, webhooks_list=webhooks_list))

    async def send_webhook(self, client_id: str, webhook_type: SendWebhookWebhookType) -> SendWebhookResponse:
        """Метод для проверки отправки вебхука via ``POST /webhook/v1.0/{client_id}/test_send``.

        Args:
            client_id: Уникальный идентификатор приложения
            webhook_type: Тип вебхука
        """
        return await self.execute(SendWebhook(client_id=client_id, webhook_type=webhook_type))
