# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Shared models — cross-domain DTOs collapsed by codegen dedup (auto-generated from the Tochka OpenAPI
spec)."""

from __future__ import annotations

from pydantic import Field

from ._base import TochkaObject


class DocumentIdResponse(TochkaObject):
    """DocumentIdResponse — shared across domains.

    Attributes:
        document_id: Уникальный идентификатор документа
    """

    document_id: str = Field(..., alias="documentId")


class ResultResponse(TochkaObject):
    """ResultResponse — shared across domains.

    Attributes:
        result: Статус операции
    """

    result: bool


class SelfResponse(TochkaObject):
    """SelfResponse — shared across domains.

    Attributes:
        self: Self
    """

    self: str = Field(..., min_length=1, max_length=2083)


class SuccessResponse(TochkaObject):
    """SuccessResponse — shared across domains.

    Attributes:
        success: Success
    """

    success: bool


class TotalPagesResponse(TochkaObject):
    """TotalPagesResponse — shared across domains.

    Attributes:
        total_pages: Totalpages
    """

    total_pages: int = Field(..., alias="totalPages")
