# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платёж через форму мерчанта — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ._base import TochkaObject
from ._shared import TotalPagesResponse


class CreatePaymentResponse(TochkaObject):
    """CreatePaymentResponse response model.

    Attributes:
        data: PaymentResponseDTO
        links: Links
    """

    data: CreatePaymentResponseData = Field(..., alias="Data")
    links: CreatePaymentResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreatePaymentResponseData(TochkaObject):
    """CreatePaymentResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        chargeback_summary: Информация о суммах удержаний и возвратов чарджбеков
        comment: Комментарий
        created_date_time: Дата создания платежа
        customer: CustomerDTO
        is_test: Флаг тестовой операции
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        order_uid: Уникальный идентификатор заказа в информационной системе ТСП
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП + :::warning При оплате
            через динамическую или статическую платёжную ссылку СБП идентификатор создаётся на стороне
            Точки:::
        refunded_amount: Информация о сумме возвратов
    """

    amount: CreatePaymentResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    chargeback_summary: CreatePaymentResponseDataChargebackSummary = Field(..., alias="chargebackSummary")
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    customer: CreatePaymentResponseDataCustomer | None = None
    is_test: bool = Field(..., alias="isTest")
    metadata: str
    order_uid: str | None = Field(None, pattern="^[0-9a-zA-Z-:]{1,64}$", alias="orderUid")
    payment_method: Any = Field(..., alias="paymentMethod")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")
    refunded_amount: CreatePaymentResponseDataRefundedAmount = Field(..., alias="refundedAmount")
    requirements: Any | None = None
    status: Any


class CreatePaymentResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreatePaymentResponseDataChargebackSummary(TochkaObject):
    """Информация о суммах удержаний и возвратов чарджбеков

    Attributes:
        charged_amount: Сумма чарджбеков по платежу
        reversed_amount: Сумма возвращённых чарджбеков
    """

    charged_amount: CreatePaymentResponseDataChargebackSummaryChargedAmount = Field(
        ..., alias="chargedAmount"
    )
    reversed_amount: CreatePaymentResponseDataChargebackSummaryReversedAmount = Field(
        ..., alias="reversedAmount"
    )


class CreatePaymentResponseDataChargebackSummaryChargedAmount(TochkaObject):
    """Сумма чарджбеков по платежу

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreatePaymentResponseDataChargebackSummaryReversedAmount(TochkaObject):
    """Сумма возвращённых чарджбеков

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreatePaymentResponseDataCustomer(TochkaObject):
    """CreatePaymentResponseDataCustomer response model.

    Attributes:
        account: Идентификатор пользователя
        address: Адрес покупателя
        email: E-mail пользователя
        first_name: Имя покупателя
        last_name: Фамилия покупателя
        middle_name: Отчество покупателя
        phone: Номер телефона пользователя
        simple_address: Адрес покупателя
    """

    account: str | None = Field(None, min_length=1, max_length=64)
    address: CreatePaymentResponseDataCustomerAddress | None = None
    email: str | None = Field(None, min_length=1, max_length=64, pattern="^[^@\\s]+@[^@\\s]+$")
    first_name: str | None = Field(None, min_length=1, max_length=64, alias="firstName")
    last_name: str | None = Field(None, min_length=1, max_length=64, alias="lastName")
    middle_name: str | None = Field(None, min_length=1, max_length=64, alias="middleName")
    phone: str | None = Field(None, pattern="^\\+?\\d{11,16}$")
    simple_address: str | None = Field(None, min_length=1, max_length=256, alias="simpleAddress")


class CreatePaymentResponseDataCustomerAddress(TochkaObject):
    """Адрес покупателя

    Attributes:
        city: Город адреса покупателя
        country: Страна адреса покупателя
        details: Детали адреса покупателя
        region: Регион адреса покупателя
    """

    city: str | None = Field(None, min_length=1, max_length=64)
    country: str | None = Field(None, min_length=1, max_length=64)
    details: str | None = Field(None, min_length=1, max_length=256)
    region: str | None = Field(None, min_length=1, max_length=64)


class CreatePaymentResponseDataRefundedAmount(TochkaObject):
    """Информация о сумме возвратов

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreatePaymentResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class CreatePaymentData(TochkaObject):
    """CreatePaymentData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Комментарий
        customer: CustomerDTO
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        order_uid: Уникальный идентификатор заказа в информационной системе ТСП
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
    """

    amount: CreatePaymentDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    customer: CreatePaymentDataCustomer | None = None
    metadata: str | None = Field(None, min_length=0, max_length=2048)
    order_uid: str | None = Field(None, pattern="^[0-9a-zA-Z-:]{1,64}$", alias="orderUid")
    payment_method: Any = Field(..., alias="paymentMethod")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")


class CreatePaymentDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreatePaymentDataCustomer(TochkaObject):
    """CreatePaymentDataCustomer response model.

    Attributes:
        account: Идентификатор пользователя
        address: Адрес покупателя
        email: E-mail пользователя
        first_name: Имя покупателя
        last_name: Фамилия покупателя
        middle_name: Отчество покупателя
        phone: Номер телефона пользователя
        simple_address: Адрес покупателя
    """

    account: str | None = Field(None, min_length=1, max_length=64)
    address: CreatePaymentDataCustomerAddress | None = None
    email: str | None = Field(None, min_length=1, max_length=64, pattern="^[^@\\s]+@[^@\\s]+$")
    first_name: str | None = Field(None, min_length=1, max_length=64, alias="firstName")
    last_name: str | None = Field(None, min_length=1, max_length=64, alias="lastName")
    middle_name: str | None = Field(None, min_length=1, max_length=64, alias="middleName")
    phone: str | None = Field(None, pattern="^\\+?\\d{11,16}$")
    simple_address: str | None = Field(None, min_length=1, max_length=256, alias="simpleAddress")


class CreatePaymentDataCustomerAddress(TochkaObject):
    """Адрес покупателя

    Attributes:
        city: Город адреса покупателя
        country: Страна адреса покупателя
        details: Детали адреса покупателя
        region: Регион адреса покупателя
    """

    city: str | None = Field(None, min_length=1, max_length=64)
    country: str | None = Field(None, min_length=1, max_length=64)
    details: str | None = Field(None, min_length=1, max_length=256)
    region: str | None = Field(None, min_length=1, max_length=64)


class GetPaymentResponse(TochkaObject):
    """GetPaymentResponse response model.

    Attributes:
        data: PaymentResponseDTO
        links: Links
    """

    data: GetPaymentResponseData = Field(..., alias="Data")
    links: GetPaymentResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentResponseData(TochkaObject):
    """GetPaymentResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        chargeback_summary: Информация о суммах удержаний и возвратов чарджбеков
        comment: Комментарий
        created_date_time: Дата создания платежа
        customer: CustomerDTO
        is_test: Флаг тестовой операции
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        order_uid: Уникальный идентификатор заказа в информационной системе ТСП
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП + :::warning При оплате
            через динамическую или статическую платёжную ссылку СБП идентификатор создаётся на стороне
            Точки:::
        refunded_amount: Информация о сумме возвратов
    """

    amount: GetPaymentResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    chargeback_summary: GetPaymentResponseDataChargebackSummary = Field(..., alias="chargebackSummary")
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    customer: GetPaymentResponseDataCustomer | None = None
    is_test: bool = Field(..., alias="isTest")
    metadata: str
    order_uid: str | None = Field(None, pattern="^[0-9a-zA-Z-:]{1,64}$", alias="orderUid")
    payment_method: Any = Field(..., alias="paymentMethod")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")
    refunded_amount: GetPaymentResponseDataRefundedAmount = Field(..., alias="refundedAmount")
    requirements: Any | None = None
    status: Any


class GetPaymentResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentResponseDataChargebackSummary(TochkaObject):
    """Информация о суммах удержаний и возвратов чарджбеков

    Attributes:
        charged_amount: Сумма чарджбеков по платежу
        reversed_amount: Сумма возвращённых чарджбеков
    """

    charged_amount: GetPaymentResponseDataChargebackSummaryChargedAmount = Field(..., alias="chargedAmount")
    reversed_amount: GetPaymentResponseDataChargebackSummaryReversedAmount = Field(
        ..., alias="reversedAmount"
    )


class GetPaymentResponseDataChargebackSummaryChargedAmount(TochkaObject):
    """Сумма чарджбеков по платежу

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentResponseDataChargebackSummaryReversedAmount(TochkaObject):
    """Сумма возвращённых чарджбеков

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentResponseDataCustomer(TochkaObject):
    """GetPaymentResponseDataCustomer response model.

    Attributes:
        account: Идентификатор пользователя
        address: Адрес покупателя
        email: E-mail пользователя
        first_name: Имя покупателя
        last_name: Фамилия покупателя
        middle_name: Отчество покупателя
        phone: Номер телефона пользователя
        simple_address: Адрес покупателя
    """

    account: str | None = Field(None, min_length=1, max_length=64)
    address: GetPaymentResponseDataCustomerAddress | None = None
    email: str | None = Field(None, min_length=1, max_length=64, pattern="^[^@\\s]+@[^@\\s]+$")
    first_name: str | None = Field(None, min_length=1, max_length=64, alias="firstName")
    last_name: str | None = Field(None, min_length=1, max_length=64, alias="lastName")
    middle_name: str | None = Field(None, min_length=1, max_length=64, alias="middleName")
    phone: str | None = Field(None, pattern="^\\+?\\d{11,16}$")
    simple_address: str | None = Field(None, min_length=1, max_length=256, alias="simpleAddress")


class GetPaymentResponseDataCustomerAddress(TochkaObject):
    """Адрес покупателя

    Attributes:
        city: Город адреса покупателя
        country: Страна адреса покупателя
        details: Детали адреса покупателя
        region: Регион адреса покупателя
    """

    city: str | None = Field(None, min_length=1, max_length=64)
    country: str | None = Field(None, min_length=1, max_length=64)
    details: str | None = Field(None, min_length=1, max_length=256)
    region: str | None = Field(None, min_length=1, max_length=64)


class GetPaymentResponseDataRefundedAmount(TochkaObject):
    """Информация о сумме возвратов

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )
