# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Возвраты — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ._base import TochkaObject
from ._shared import TotalPagesResponse


class GetRefundsResponse(TochkaObject):
    """GetRefundsResponse response model.

    Attributes:
        links: Links
    """

    data: list[GetRefundsResponseData] = Field(..., alias="Data")
    links: GetRefundsResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRefundsResponseData(TochkaObject):
    """GetRefundsResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Дополнительное описание возврата
        created_date_time: Дата создания операции в формате ISO8601
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        refund_uid: Уникальный идентификатор возврата в информационной системе ТСП
    """

    amount: GetRefundsResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    metadata: str
    refund_method_result: Any | None = Field(None, alias="refundMethodResult")
    refund_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="refundUid")
    status: Any


class GetRefundsResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetRefundsResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class CreateRefundResponse(TochkaObject):
    """CreateRefundResponse response model.

    Attributes:
        data: RefundResponseDTO
        links: Links
    """

    data: CreateRefundResponseData = Field(..., alias="Data")
    links: CreateRefundResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateRefundResponseData(TochkaObject):
    """CreateRefundResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Дополнительное описание возврата
        created_date_time: Дата создания операции в формате ISO8601
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        refund_uid: Уникальный идентификатор возврата в информационной системе ТСП
    """

    amount: CreateRefundResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    metadata: str
    refund_method_result: Any | None = Field(None, alias="refundMethodResult")
    refund_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="refundUid")
    status: Any


class CreateRefundResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreateRefundResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class CreateRefundData(TochkaObject):
    """CreateRefundData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Дополнительное описание возврата
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        refund_uid: Уникальный идентификатор возврата в информационной системе ТСП
    """

    amount: CreateRefundDataAmount | None = None
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    metadata: str | None = Field(None, min_length=0, max_length=2048)
    refund_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="refundUid")


class CreateRefundDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetRefundResponse(TochkaObject):
    """GetRefundResponse response model.

    Attributes:
        data: RefundResponseDTO
        links: Links
    """

    data: GetRefundResponseData = Field(..., alias="Data")
    links: GetRefundResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRefundResponseData(TochkaObject):
    """GetRefundResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Дополнительное описание возврата
        created_date_time: Дата создания операции в формате ISO8601
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        refund_uid: Уникальный идентификатор возврата в информационной системе ТСП
    """

    amount: GetRefundResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    metadata: str
    refund_method_result: Any | None = Field(None, alias="refundMethodResult")
    refund_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="refundUid")
    status: Any


class GetRefundResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetRefundResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )
