# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Функциональные ссылки СБП — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ..enums.acquiring_functional_links import (
    CreateQrCodeResponseDataImageMediaType,
    GetQrCodeResponseDataImageMediaType,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse


class CreateQrCodeResponse(TochkaObject):
    """CreateQrCodeResponse response model.

    Attributes:
        data: QRCodeResponseDTO
        links: Links
    """

    data: CreateQrCodeResponseData = Field(..., alias="Data")
    links: CreateQrCodeResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateQrCodeResponseData(TochkaObject):
    """CreateQrCodeResponseData response model.

    Attributes:
        image: Опциональные данные сгенерированного изображения QR-кода
        is_test: Флаг тестовой операции
        merchant_qrc_id: Уникальный идентификатор Функциональной ссылки СБП в информационной системе ТСП
        payload: Payload зарегистрированной Функциональной ссылки СБП
        qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
    """

    image: CreateQrCodeResponseDataImage | None = None
    is_test: bool = Field(..., alias="isTest")
    merchant_qrc_id: str | None = Field(None, pattern="^[0-9a-zA-Z-]{1,64}$", alias="merchantQrcId")
    payload: str = Field(..., max_length=999)
    qrc_id: str = Field(..., max_length=32, alias="qrcId")


class CreateQrCodeResponseDataImage(TochkaObject):
    """Опциональные данные сгенерированного изображения QR-кода

    Attributes:
        content: Закодированное изображение. Формат для декодирования зависит от mediaType
        media_type: Формат изображения QR-кода
    """

    content: str
    media_type: CreateQrCodeResponseDataImageMediaType = Field(..., alias="mediaType")


class CreateQrCodeResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class GetQrCodeResponse(TochkaObject):
    """GetQrCodeResponse response model.

    Attributes:
        data: QRCodeResponseDTO
        links: Links
    """

    data: GetQrCodeResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetQrCodeResponseData(TochkaObject):
    """GetQrCodeResponseData response model.

    Attributes:
        image: Опциональные данные сгенерированного изображения QR-кода
        is_test: Флаг тестовой операции
        merchant_qrc_id: Уникальный идентификатор Функциональной ссылки СБП в информационной системе ТСП
        payload: Payload зарегистрированной Функциональной ссылки СБП
        qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
    """

    image: GetQrCodeResponseDataImage | None = None
    is_test: bool = Field(..., alias="isTest")
    merchant_qrc_id: str | None = Field(None, pattern="^[0-9a-zA-Z-]{1,64}$", alias="merchantQrcId")
    payload: str = Field(..., max_length=999)
    qrc_id: str = Field(..., max_length=32, alias="qrcId")


class GetQrCodeResponseDataImage(TochkaObject):
    """Опциональные данные сгенерированного изображения QR-кода

    Attributes:
        content: Закодированное изображение. Формат для декодирования зависит от mediaType
        media_type: Формат изображения QR-кода
    """

    content: str
    media_type: GetQrCodeResponseDataImageMediaType = Field(..., alias="mediaType")


class GetPaymentsByQrcIdResponse(TochkaObject):
    """GetPaymentsByQrcIdResponse response model.

    Attributes:
        links: Links
    """

    data: list[GetPaymentsByQrcIdResponseData] = Field(..., alias="Data")
    links: GetPaymentsByQrcIdResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentsByQrcIdResponseData(TochkaObject):
    """GetPaymentsByQrcIdResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        chargeback_summary: Информация о суммах удержаний и возвратов чарджбеков
        comment: Комментарий
        created_date_time: Дата создания платежа
        customer: CustomerDTO
        is_test: Флаг тестовой операции
        metadata: Строка с json, содержащим дополнительные поля с произвольной информацией. Пример
            формата: `\"{\\\"property1\\\": \\\"string\\\"}\"`
        order_uid: Уникальный идентификатор заказа в информационной системе ТСП
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП + :::warning При оплате
            через динамическую или статическую платёжную ссылку СБП идентификатор создаётся на стороне
            Точки:::
        refunded_amount: Информация о сумме возвратов
    """

    amount: GetPaymentsByQrcIdResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    chargeback_summary: GetPaymentsByQrcIdResponseDataChargebackSummary = Field(
        ..., alias="chargebackSummary"
    )
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    customer: GetPaymentsByQrcIdResponseDataCustomer | None = None
    is_test: bool = Field(..., alias="isTest")
    metadata: str
    order_uid: str | None = Field(None, pattern="^[0-9a-zA-Z-:]{1,64}$", alias="orderUid")
    payment_method: Any = Field(..., alias="paymentMethod")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")
    refunded_amount: GetPaymentsByQrcIdResponseDataRefundedAmount = Field(..., alias="refundedAmount")
    requirements: Any | None = None
    status: Any


class GetPaymentsByQrcIdResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentsByQrcIdResponseDataChargebackSummary(TochkaObject):
    """Информация о суммах удержаний и возвратов чарджбеков

    Attributes:
        charged_amount: Сумма чарджбеков по платежу
        reversed_amount: Сумма возвращённых чарджбеков
    """

    charged_amount: GetPaymentsByQrcIdResponseDataChargebackSummaryChargedAmount = Field(
        ..., alias="chargedAmount"
    )
    reversed_amount: GetPaymentsByQrcIdResponseDataChargebackSummaryReversedAmount = Field(
        ..., alias="reversedAmount"
    )


class GetPaymentsByQrcIdResponseDataChargebackSummaryChargedAmount(TochkaObject):
    """Сумма чарджбеков по платежу

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentsByQrcIdResponseDataChargebackSummaryReversedAmount(TochkaObject):
    """Сумма возвращённых чарджбеков

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentsByQrcIdResponseDataCustomer(TochkaObject):
    """GetPaymentsByQrcIdResponseDataCustomer response model.

    Attributes:
        account: Идентификатор пользователя
        address: Адрес покупателя
        email: E-mail пользователя
        first_name: Имя покупателя
        last_name: Фамилия покупателя
        middle_name: Отчество покупателя
        phone: Номер телефона пользователя
        simple_address: Адрес покупателя
    """

    account: str | None = Field(None, min_length=1, max_length=64)
    address: GetPaymentsByQrcIdResponseDataCustomerAddress | None = None
    email: str | None = Field(None, min_length=1, max_length=64, pattern="^[^@\\s]+@[^@\\s]+$")
    first_name: str | None = Field(None, min_length=1, max_length=64, alias="firstName")
    last_name: str | None = Field(None, min_length=1, max_length=64, alias="lastName")
    middle_name: str | None = Field(None, min_length=1, max_length=64, alias="middleName")
    phone: str | None = Field(None, pattern="^\\+?\\d{11,16}$")
    simple_address: str | None = Field(None, min_length=1, max_length=256, alias="simpleAddress")


class GetPaymentsByQrcIdResponseDataCustomerAddress(TochkaObject):
    """Адрес покупателя

    Attributes:
        city: Город адреса покупателя
        country: Страна адреса покупателя
        details: Детали адреса покупателя
        region: Регион адреса покупателя
    """

    city: str | None = Field(None, min_length=1, max_length=64)
    country: str | None = Field(None, min_length=1, max_length=64)
    details: str | None = Field(None, min_length=1, max_length=256)
    region: str | None = Field(None, min_length=1, max_length=64)


class GetPaymentsByQrcIdResponseDataRefundedAmount(TochkaObject):
    """Информация о сумме возвратов

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetPaymentsByQrcIdResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class GetTokenizationResultResponse(TochkaObject):
    """GetTokenizationResultResponse response model.

    Attributes:
        links: Links
    """

    data: Any = Field(..., alias="Data")
    links: GetTokenizationResultResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetTokenizationResultResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )
