# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Подтверждение — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ._base import TochkaObject
from ._shared import TotalPagesResponse


class GetCapturesResponse(TochkaObject):
    """GetCapturesResponse response model.

    Attributes:
        links: Links
    """

    data: list[GetCapturesResponseData] = Field(..., alias="Data")
    links: GetCapturesResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCapturesResponseData(TochkaObject):
    """GetCapturesResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Комментарий
        created_date_time: Дата создания подтверждения
    """

    amount: GetCapturesResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    capture_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="captureUid")
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    status: Any


class GetCapturesResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetCapturesResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class CreateCaptureResponse(TochkaObject):
    """CreateCaptureResponse response model.

    Attributes:
        data: CaptureResponseDTO
        links: Links
    """

    data: CreateCaptureResponseData = Field(..., alias="Data")
    links: CreateCaptureResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateCaptureResponseData(TochkaObject):
    """CreateCaptureResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Комментарий
        created_date_time: Дата создания подтверждения
    """

    amount: CreateCaptureResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    capture_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="captureUid")
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    status: Any


class CreateCaptureResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class CreateCaptureResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )


class CreateCaptureData(TochkaObject):
    """CreateCaptureData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        capture_uid: Идентификатор подтверждения платежа в информационной системе ТСП
        comment: Комментарий
    """

    amount: CreateCaptureDataAmount | None = None
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    capture_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="captureUid")
    comment: str | None = Field(None, min_length=1, max_length=255)


class CreateCaptureDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetCaptureResponse(TochkaObject):
    """GetCaptureResponse response model.

    Attributes:
        data: CaptureResponseDTO
        links: Links
    """

    data: GetCaptureResponseData = Field(..., alias="Data")
    links: GetCaptureResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCaptureResponseData(TochkaObject):
    """GetCaptureResponseData response model.

    Attributes:
        amount: Информация о сумме операции
        callback_url: URL отправки уведомления об операции
        comment: Комментарий
        created_date_time: Дата создания подтверждения
    """

    amount: GetCaptureResponseDataAmount
    callback_url: str | None = Field(
        None,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
        alias="callbackUrl",
    )
    capture_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="captureUid")
    comment: str | None = Field(None, min_length=1, max_length=255)
    created_date_time: str = Field(..., alias="createdDateTime")
    status: Any


class GetCaptureResponseDataAmount(TochkaObject):
    """Информация о сумме операции

    Attributes:
        amount: Сумма операции
        currency: Валюта в формате ISO4217
    """

    amount: str
    currency: str


class GetCaptureResponseLinks(TochkaObject):
    """Links"""

    self: str = Field(
        ...,
        min_length=1,
        max_length=2083,
        pattern="^https?://[-a-zA-Z0-9¡-￿+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9¡-￿+&@#/%=~_|]",
    )
