# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from pydantic import Field

from ..enums.customers import (
    GetCustomerInfoResponseDataCustomerType,
    GetCustomersListResponseDataCustomerCustomerType,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse


class GetCustomersListResponse(TochkaObject):
    """Метод получения списка доступных клиентов

    Attributes:
        data: CustomerListModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetCustomersListResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCustomersListResponseData(TochkaObject):
    """GetCustomersListResponseData response model.

    Attributes:
        customer: Customer
    """

    customer: list[GetCustomersListResponseDataCustomer] = Field(..., alias="Customer")


class GetCustomersListResponseDataCustomer(TochkaObject):
    """GetCustomersListResponseDataCustomer response model.

    Attributes:
        customer_code: Уникальный код клиента
        customer_ogrn: ОГРН или ОГРНИП
        customer_type: Тип клиент (физическое или юридическое лицо)
        full_name: Полное наименование
        is_resident: Признак резидента
        kpp: КПП
        short_name: Краткое наименование
        tax_code: ИНН
    """

    customer_code: str = Field(..., max_length=9, alias="customerCode")
    customer_ogrn: str | None = Field(None, alias="customerOgrn")
    customer_type: GetCustomersListResponseDataCustomerCustomerType = Field(..., alias="customerType")
    full_name: str = Field(..., alias="fullName")
    is_resident: bool = Field(..., alias="isResident")
    kpp: str | None = None
    short_name: str | None = Field(None, alias="shortName")
    tax_code: str | None = Field(None, alias="taxCode")


class GetCustomerInfoResponse(TochkaObject):
    """Метод получения информации по клиенту

    Attributes:
        data: CustomerModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetCustomerInfoResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCustomerInfoResponseData(TochkaObject):
    """GetCustomerInfoResponseData response model.

    Attributes:
        customer_code: Уникальный код клиента
        customer_ogrn: ОГРН или ОГРНИП
        customer_type: Тип клиент (физическое или юридическое лицо)
        full_name: Полное наименование
        is_resident: Признак резидента
        kpp: КПП
        short_name: Краткое наименование
        tax_code: ИНН
    """

    customer_code: str = Field(..., max_length=9, alias="customerCode")
    customer_ogrn: str | None = Field(None, alias="customerOgrn")
    customer_type: GetCustomerInfoResponseDataCustomerType = Field(..., alias="customerType")
    full_name: str = Field(..., alias="fullName")
    is_resident: bool = Field(..., alias="isResident")
    kpp: str | None = None
    short_name: str | None = Field(None, alias="shortName")
    tax_code: str | None = Field(None, alias="taxCode")
