# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from pydantic import Field

from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse


class GetCustomerInfoResponse(TochkaObject):
    """GetCustomerInfoResponse response model.

    Attributes:
        data: CustomerInfoWithAddressModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetCustomerInfoResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCustomerInfoResponseData(TochkaObject):
    """GetCustomerInfoResponseData response model.

    Attributes:
        customer_code: Уникальный код клиента
        customer_ogrn: ОГРН или ОГРНИП
        customer_type: Тип клиента (юридическое лицо)
        full_name: Полное наименование
        is_resident: Признак резидента
        kpp: КПП
        legal_address: Юридический адрес
        physical_address: Фактический адрес
        postal_address: Почтовый адрес
        short_name: Краткое наименование
        tax_code: ИНН
    """

    customer_code: str = Field(..., max_length=9, alias="customerCode")
    customer_ogrn: str | None = Field(None, alias="customerOgrn")
    customer_type: str = Field(..., alias="customerType")
    full_name: str = Field(..., alias="fullName")
    is_resident: bool = Field(..., alias="isResident")
    kpp: str | None = None
    legal_address: str | None = Field(None, alias="legalAddress")
    physical_address: str | None = Field(None, alias="physicalAddress")
    postal_address: str | None = Field(None, alias="postalAddress")
    short_name: str | None = Field(None, alias="shortName")
    tax_code: str | None = Field(None, alias="taxCode")
