# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сделки — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from datetime import date
from typing import Any

from pydantic import Field

from ..enums.deals import (
    ListDealsV2ParamsFieldNames,
    ListDealsV2ParamsFiltersStatus,
    ListDealV2ParamsFiltersStatus,
)
from ._base import TochkaObject
from .common import TZDatetime


class CancelDealWithExecutedRecipientsV2Params(TochkaObject):
    """CancelDealWithExecutedRecipientsV2Params response model.

    Attributes:
        deal_id: Уникальный идентификатор сделки
    """

    deal_id: str


class ComplianceCheckDealV2Params(TochkaObject):
    """ComplianceCheckDealV2Params response model.

    Attributes:
        deal_id: Уникальный идентификатор сделки
    """

    deal_id: str


class CreateDealV2Params(TochkaObject):
    """CreateDealV2Params response model.

    Attributes:
        amount: Общая сумма сделки
        ext_key: Внешний идентификатор сделки
        payers: Владельцы денег
        recipients: Получатели
    """

    amount: float
    ext_key: str | None = Field(None, min_length=1, max_length=50)
    payers: list[CreateDealV2ParamsPayers]
    recipients: list[Any]


class CreateDealV2ParamsPayers(TochkaObject):
    """CreateDealV2ParamsPayers response model.

    Attributes:
        amount: Сумма зачисления
        virtual_account: Виртуальный счёт, типа standard
    """

    amount: float
    virtual_account: str


class ExecuteDealV2Params(TochkaObject):
    """ExecuteDealV2Params response model.

    Attributes:
        deal_id: Уникальный идентификатор сделки
        recipients_execute: Список номеров получателей, по которым нужно создать платежи. Если не указан,
            то создаются платежи по всем получателям сделки
    """

    deal_id: str
    recipients_execute: list[ExecuteDealV2ParamsRecipientsExecute] | None = Field(None, min_length=1)


class ExecuteDealV2ParamsRecipientsExecute(TochkaObject):
    """ExecuteDealV2ParamsRecipientsExecute response model.

    Attributes:
        number: Номер получателя, уникальный в рамках сделки
    """

    number: int = Field(..., ge=0)


class GetDealV2Params(TochkaObject):
    """GetDealV2Params response model.

    Attributes:
        deal_id: Уникальный идентификатор сделки
    """

    deal_id: str


class ListDealV2Params(TochkaObject):
    """ListDealV2Params response model.

    Attributes:
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    filters: ListDealV2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListDealV2ParamsFilters(TochkaObject):
    """ListDealV2ParamsFilters response model.

    Attributes:
        created_date_from: Дата создания сделки от
        created_date_to: Дата создания сделки до
        ext_key: Внешний идентификатор сделки
        status: Статусы сделки: - new: сделка создана - in_process: в процессе выполнения - correction:
            исправление - part_execute: частичное исполнение - closed: сделка завершена - rejected: сделка
            отменена (из статуса NEW) - canceled_by_platform: сделка частично отменена - canceled_by_service:
            сделка отменена сервисом.
    """

    created_date_from: date | None = None
    created_date_to: date | None = None
    ext_key: str | None = Field(None, min_length=1, max_length=50)
    status: ListDealV2ParamsFiltersStatus | None = None


class ListDealsV2Params(TochkaObject):
    """ListDealsV2Params response model.

    Attributes:
        field_names: Список возвращаемых полей
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    field_names: list[ListDealsV2ParamsFieldNames] | None = None
    filters: ListDealsV2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListDealsV2ParamsFilters(TochkaObject):
    """ListDealsV2ParamsFilters response model.

    Attributes:
        created_date_from: Дата создания сделки от
        created_date_to: Дата создания сделки до
        ext_key: Внешний идентификатор сделки
        status: Статусы сделки: - new: сделка создана - in_process: в процессе выполнения - correction:
            исправление - part_execute: частичное исполнение - closed: сделка завершена - rejected: сделка
            отменена (из статуса NEW) - canceled_by_platform: сделка частично отменена - canceled_by_service:
            сделка отменена сервисом.
        updated_at_from: Дата обновления сделки от
        updated_at_to: Дата обновления сделки до
    """

    created_date_from: date | None = None
    created_date_to: date | None = None
    ext_key: str | None = Field(None, min_length=1, max_length=50)
    status: ListDealsV2ParamsFiltersStatus | None = None
    updated_at_from: TZDatetime | None = None
    updated_at_to: TZDatetime | None = None


class RejectedDealV2Params(TochkaObject):
    """RejectedDealV2Params response model.

    Attributes:
        deal_id: Уникальный идентификатор сделки
    """

    deal_id: str


class UpdateDealV2Params(TochkaObject):
    """UpdateDealV2Params response model.

    Attributes:
        deal_data: Изменяемые данные по сделке
        deal_id: Уникальный идентификатор сделки
    """

    deal_data: UpdateDealV2ParamsDealData
    deal_id: str


class UpdateDealV2ParamsDealData(TochkaObject):
    """UpdateDealV2ParamsDealData response model.

    Attributes:
        amount: Общая сумма сделки
        ext_key: Внешний идентификатор сделки
        payers: Владельцы денег
        recipients: Получатели
    """

    amount: float
    ext_key: str | None = Field(None, min_length=1, max_length=50)
    payers: list[UpdateDealV2ParamsDealDataPayers]
    recipients: list[Any]


class UpdateDealV2ParamsDealDataPayers(TochkaObject):
    """UpdateDealV2ParamsDealDataPayers response model.

    Attributes:
        amount: Сумма зачисления
        virtual_account: Виртуальный счёт, типа standard
    """

    amount: float
    virtual_account: str
