# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Заказы — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import Field

from ..enums.marketplace_orders import (
    CreateOrderDataReceiptPaymentMethod,
    CreateOrderDataReceiptPaymentObject,
    CreateOrderDataReceiptVatType,
    CreateOrderDataServicesStartDecision,
    CreateOrderV2DataReceiptPaymentMethod,
    CreateOrderV2DataReceiptPaymentObject,
    CreateOrderV2DataReceiptVatType,
    CreateOrderV2DataServicesStartDecision,
    CreateOrderV3DataReceiptPaymentMethod,
    CreateOrderV3DataReceiptPaymentObject,
    CreateOrderV3DataReceiptVatType,
    CreateOrderV3DataServicesStartDecision,
    GetOrderListResponseDataItemsState,
    GetOrderResponseDataServicesDecision,
    GetOrderResponseDataServicesState,
    GetOrderResponseDataState,
    GetOrderV2ResponseDataServicesDecision,
    GetOrderV2ResponseDataServicesRecipientMethodType,
    GetOrderV2ResponseDataServicesState,
    GetOrderV2ResponseDataState,
    GetOrderV3ResponseDataServicesDecision,
    GetOrderV3ResponseDataServicesRecipientMethodType,
    GetOrderV3ResponseDataServicesState,
    GetOrderV3ResponseDataState,
    MakeOrderServicesDecisionDataDecisionsDecision,
    MakeOrderServicesDecisionResponseDataDecisionsDecision,
    UpdateOrderDataUpdatesState,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse
from .common import TZDatetime

if TYPE_CHECKING:
    from ..methods.marketplace_orders import (
        GetOrder,
        GetOrderV2,
        GetOrderV3,
        MakeOrderServicesDecision,
        UpdateOrder,
    )


class GetOrderListResponse(TochkaObject):
    """GetOrderListResponse response model.

    Attributes:
        data: GetOrderListResponse
        links: LinkModel
        meta: MetaModel
    """

    data: GetOrderListResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetOrderListResponseData(TochkaObject):
    """GetOrderListResponseData response model.

    Attributes:
        items: items
        has_next: Есть ещё записи?
        total_size: Всего объектов
    """

    items: list[GetOrderListResponseDataItems] | None = Field(None, alias="Items")
    has_next: bool = Field(..., alias="hasNext")
    total_size: int = Field(..., alias="totalSize")


class GetOrderListResponseDataItems(TochkaObject):
    """GetOrderListResponseDataItems response model.

    Attributes:
        ext_id: Внешний идентификатор
        state: Статус заказа
    """

    ext_id: str | None = Field(None, alias="extId")
    state: GetOrderListResponseDataItemsState


class CreateOrderResponse(TochkaObject):
    """CreateOrderResponse response model.

    Attributes:
        data: CreateOrderResponse
        links: LinkModel
        meta: MetaModel
    """

    data: CreateOrderResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateOrderResponseData(TochkaObject):
    """CreateOrderResponseData response model.

    Attributes:
        ext_id: Идентификатор
        payment_url: Ссылка на оплату заказа
    """

    ext_id: str = Field(..., alias="extId")
    payment_url: str = Field(..., alias="paymentUrl")


class CreateOrderData(TochkaObject):
    """CreateOrderData response model.

    Attributes:
        incoming_payment: IncomingPayment
        receipt: Информация для чека
        services: Услуги
        order_commission: Комиссия за заказ
        order_ext_id: Внешний идентификатор заказа
        receipt_email: DEPRECATED! Используйте Receipt.email. Почта для отправки чека
    """

    incoming_payment: CreateOrderDataIncomingPayment = Field(..., alias="IncomingPayment")
    receipt: CreateOrderDataReceipt | None = Field(None, alias="Receipt")
    services: list[CreateOrderDataServices] = Field(..., min_length=1, max_length=100, alias="Services")
    order_commission: str = Field(..., alias="orderCommission")
    order_ext_id: str = Field(..., alias="orderExtId")
    receipt_email: str | None = Field(None, alias="receiptEmail")


class CreateOrderDataIncomingPayment(TochkaObject):
    """CreateOrderDataIncomingPayment response model.

    Attributes:
        consumer_id: Идентификатор Плательщика. Используется для сохранения карты в эквайринге
        payment_url_ttl: Время действия ссылки на оплату в минутах
        purpose: Наименование пополнения в эквайринге
        redirect_fail_url: Redirect URL в случае ошибки
        redirect_url: URL адрес, куда будет перенаправлен клиент после оплаты
        type_: Способ оплаты
    """

    consumer_id: str | None = Field(None, max_length=200, alias="consumerId")
    payment_url_ttl: int = Field(..., alias="paymentUrlTtl")
    purpose: str = Field(..., max_length=256)
    redirect_fail_url: str = Field(..., alias="redirectFailUrl")
    redirect_url: str = Field(..., alias="redirectUrl")
    type_: str = Field(..., alias="type")


class CreateOrderDataReceipt(TochkaObject):
    """CreateOrderDataReceipt response model.

    Attributes:
        email: Почта для отправки чека
        name: Как называется позиция комиссии в чеке
        payment_method: Способ оплаты. full_payment – полная оплата, full_prepayment – предоплата 100%
        payment_object: Тип объекта для оплаты
        vat_type: Процент НДС
    """

    email: str
    name: str
    payment_method: CreateOrderDataReceiptPaymentMethod = Field(..., alias="paymentMethod")
    payment_object: CreateOrderDataReceiptPaymentObject = Field(..., alias="paymentObject")
    vat_type: CreateOrderDataReceiptVatType = Field(..., alias="vatType")


class CreateOrderDataServices(TochkaObject):
    """CreateOrderDataServices response model.

    Attributes:
        recipient: OrderRecipient
        ext_id: Идентификатор заказа со стороны площадки
        price: Price
        start_decision: Если заполнить confirmed, сразу после пополнения произойдет оплата получателю.
            Аналогично с rejected.
    """

    recipient: CreateOrderDataServicesRecipient = Field(..., alias="Recipient")
    ext_id: str = Field(..., alias="extId")
    price: str
    start_decision: CreateOrderDataServicesStartDecision = Field(..., alias="startDecision")


class CreateOrderDataServicesRecipient(TochkaObject):
    """CreateOrderDataServicesRecipient response model.

    Attributes:
        card_ext_id: Внешний идентификатор карты
        ext_id: Внешний идентификатор
        method: метод оплаты
    """

    card_ext_id: str = Field(..., alias="cardExtId")
    ext_id: str = Field(..., alias="extId")
    method: str


class GetOrderReportResponse(TochkaObject):
    """GetOrderReportResponse response model.

    Attributes:
        data: GetOrderReportResponse
        links: LinkModel
        meta: MetaModel
    """

    data: GetOrderReportResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetOrderReportResponseData(TochkaObject):
    """GetOrderReportResponseData response model.

    Attributes:
        items: items
    """

    items: list[GetOrderReportResponseDataItems] = Field(..., alias="Items")


class GetOrderReportResponseDataItems(TochkaObject):
    """GetOrderReportResponseDataItems response model.

    Attributes:
        compensation_sum: Общая сумма компенсаций
        income_payment_commission_sum: Общая сумма комиссий пополнений
        order_created_at: Дата/время создания заказа
        order_ext_id: Внешний идентификатор заказа
        outgoing_payout_commission_sum: Общая сумма комиссий выплат
        payout_sum: Общая сумма выплат
        platform_commission_sum: Общая сумма комиссий платформы
        refill_sum: Общая сумма пополнений
        refund_sum: Общая сумма возвратов
    """

    compensation_sum: str = Field(..., alias="compensationSum")
    income_payment_commission_sum: str = Field(..., alias="incomePaymentCommissionSum")
    order_created_at: str = Field(..., alias="orderCreatedAt")
    order_ext_id: str = Field(..., alias="orderExtId")
    outgoing_payout_commission_sum: str = Field(..., alias="outgoingPayoutCommissionSum")
    payout_sum: str = Field(..., alias="payoutSum")
    platform_commission_sum: str = Field(..., alias="platformCommissionSum")
    refill_sum: str = Field(..., alias="refillSum")
    refund_sum: str = Field(..., alias="refundSum")


class GetOrderResponse(TochkaObject):
    """GetOrderResponse response model.

    Attributes:
        data: GetOrderResponse
        links: LinkModel
        meta: MetaModel
    """

    data: GetOrderResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetOrderResponseData(TochkaObject):
    """GetOrderResponseData response model.

    Attributes:
        services: Services
        acquiring_commission: Комиссия эквайринга
        acquiring_commission_charged_at: Дата/время взимания комиссии эквайринга
        medusa_commission: Комиссия сервиса
        order_commission: Комиссия заказа
        order_ext_id: Внешний идентификатор
        platform_commission: Комиссия платформы
        platform_commission_paid_at: Дата/время взимания комиссии платформы
        purpose: Цель платежа
        receipt_email: Почта для отправки чека
        state: Состояние заказа
        total_amount: Итоговая сумма с учетом комиссии
        total_price: Стоимость заказа
    """

    services: list[GetOrderResponseDataServices] = Field(..., alias="Services")
    acquiring_commission: str = Field(..., alias="acquiringCommission")
    acquiring_commission_charged_at: TZDatetime | None = Field(None, alias="acquiringCommissionChargedAt")
    medusa_commission: str = Field(..., alias="medusaCommission")
    order_commission: str = Field(..., alias="orderCommission")
    order_ext_id: str | None = Field(None, alias="orderExtId")
    platform_commission: str = Field(..., alias="platformCommission")
    platform_commission_paid_at: TZDatetime | None = Field(None, alias="platformCommissionPaidAt")
    purpose: str
    receipt_email: str | None = Field(None, alias="receiptEmail")
    state: GetOrderResponseDataState
    total_amount: str = Field(..., alias="totalAmount")
    total_price: str = Field(..., alias="totalPrice")

    def get_order(self) -> GetOrder:
        """Build an awaitable :class:`GetOrder` bound to this object (await to execute)."""
        from ..methods.marketplace_orders import GetOrder

        return GetOrder(order_ext_id=self.order_ext_id).as_(self._client)

    def update_order(self, data: UpdateOrderData) -> UpdateOrder:
        """Build an awaitable :class:`UpdateOrder` bound to this object (await to execute)."""
        from ..methods.marketplace_orders import UpdateOrder

        return UpdateOrder(order_ext_id=self.order_ext_id, data=data).as_(self._client)

    def make_order_services_decision(self, data: MakeOrderServicesDecisionData) -> MakeOrderServicesDecision:
        """Build an awaitable :class:`MakeOrderServicesDecision` bound to this object (await to execute)."""
        from ..methods.marketplace_orders import MakeOrderServicesDecision

        return MakeOrderServicesDecision(order_ext_id=self.order_ext_id, data=data).as_(self._client)

    def get_order_v2(self) -> GetOrderV2:
        """Build an awaitable :class:`GetOrderV2` bound to this object (await to execute)."""
        from ..methods.marketplace_orders import GetOrderV2

        return GetOrderV2(order_ext_id=self.order_ext_id).as_(self._client)

    def get_order_v3(self) -> GetOrderV3:
        """Build an awaitable :class:`GetOrderV3` bound to this object (await to execute)."""
        from ..methods.marketplace_orders import GetOrderV3

        return GetOrderV3(order_ext_id=self.order_ext_id).as_(self._client)


class GetOrderResponseDataServices(TochkaObject):
    """GetOrderResponseDataServices response model.

    Attributes:
        recipient: Получатель
        decision: Текущее решение по услуге
        ext_id: Идентификатор
        price: Стоимость услуги
        state: Статус услуги
    """

    recipient: GetOrderResponseDataServicesRecipient = Field(..., alias="Recipient")
    decision: GetOrderResponseDataServicesDecision | None = None
    ext_id: str = Field(..., alias="extId")
    price: str
    state: GetOrderResponseDataServicesState


class GetOrderResponseDataServicesRecipient(TochkaObject):
    """GetOrderResponseDataServicesRecipient response model.

    Attributes:
        card_ext_id: Идентификатор карты
        ext_id: Идентификатор
        method: Способ оплаты
    """

    card_ext_id: str | None = Field(None, alias="cardExtId")
    ext_id: str = Field(..., alias="extId")
    method: str


class UpdateOrderResponse(TochkaObject):
    """UpdateOrderResponse response model.

    Attributes:
        data: UpdateOrderResponse
        links: LinkModel
        meta: MetaModel
    """

    data: UpdateOrderResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class UpdateOrderResponseData(TochkaObject):
    """UpdateOrderResponseData response model.

    Attributes:
        order_version: Актуальная версия заказа
    """

    order_version: int = Field(..., alias="orderVersion")


class UpdateOrderData(TochkaObject):
    """UpdateOrderData response model.

    Attributes:
        updates: Обновления
        order_version: Нужен, чтобы внешний клиент всегда понимал текущее состояние заказа перед
            обновлением. Если версии не сошлись, значит у клиента неактуальное состояние заказа
    """

    updates: list[UpdateOrderDataUpdates] = Field(..., min_length=1, max_length=100, alias="Updates")
    order_version: int = Field(..., alias="orderVersion")


class UpdateOrderDataUpdates(TochkaObject):
    """UpdateOrderDataUpdates response model.

    Attributes:
        payout_ext_id: Внешний id способа выплаты
        price: Price
        service_ext_id: Внешний идентификатор услуги
        state: Допустимы только переходы в waiting_platform_decision или ready_to_execute
    """

    payout_ext_id: str | None = Field(None, alias="payoutExtId")
    price: str | None = None
    service_ext_id: str = Field(..., alias="serviceExtId")
    state: UpdateOrderDataUpdatesState | None = None


class MakeOrderServicesDecisionResponse(TochkaObject):
    """MakeOrderServicesDecisionResponse response model.

    Attributes:
        data: MakeOrderServicesDecisionResponse
        links: LinkModel
        meta: MetaModel
    """

    data: MakeOrderServicesDecisionResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class MakeOrderServicesDecisionResponseData(TochkaObject):
    """MakeOrderServicesDecisionResponseData response model.

    Attributes:
        decisions: Решения по услугам заказа
        order_ext_id: Внешний идентификатор заказа
    """

    decisions: list[MakeOrderServicesDecisionResponseDataDecisions] | None = Field(None, alias="Decisions")
    order_ext_id: str = Field(..., alias="orderExtId")


class MakeOrderServicesDecisionResponseDataDecisions(TochkaObject):
    """MakeOrderServicesDecisionResponseDataDecisions response model.

    Attributes:
        decision: Принятое решение по услуге
        service_ext_id: Внешний идентификатор услуги
    """

    decision: MakeOrderServicesDecisionResponseDataDecisionsDecision
    service_ext_id: str = Field(..., alias="serviceExtId")


class MakeOrderServicesDecisionData(TochkaObject):
    """MakeOrderServicesDecisionData response model.

    Attributes:
        decisions: Решения по услугам заказа
    """

    decisions: list[MakeOrderServicesDecisionDataDecisions] = Field(..., alias="Decisions")


class MakeOrderServicesDecisionDataDecisions(TochkaObject):
    """MakeOrderServicesDecisionDataDecisions response model.

    Attributes:
        decision: Принятое решение по услуге
        service_ext_id: Внешний идентификатор услуги
    """

    decision: MakeOrderServicesDecisionDataDecisionsDecision
    service_ext_id: str = Field(..., alias="serviceExtId")


class CreateOrderV2Response(TochkaObject):
    """CreateOrderV2Response response model.

    Attributes:
        data: CreateOrderResponse
        links: LinkModel
        meta: MetaModel
    """

    data: CreateOrderV2ResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateOrderV2ResponseData(TochkaObject):
    """CreateOrderV2ResponseData response model.

    Attributes:
        ext_id: Идентификатор
        payment_url: Ссылка на оплату заказа
    """

    ext_id: str = Field(..., alias="extId")
    payment_url: str = Field(..., alias="paymentUrl")


class CreateOrderV2Data(TochkaObject):
    """CreateOrderV2Data response model.

    Attributes:
        incoming_payment: IncomingPayment
        receipt: Информация для чека
        services: Услуги
        order_ext_id: Внешний идентификатор заказа
    """

    incoming_payment: CreateOrderV2DataIncomingPayment = Field(..., alias="IncomingPayment")
    receipt: CreateOrderV2DataReceipt | None = Field(None, alias="Receipt")
    services: list[CreateOrderV2DataServices] = Field(..., min_length=1, max_length=50, alias="Services")
    order_ext_id: str = Field(..., alias="orderExtId")


class CreateOrderV2DataIncomingPayment(TochkaObject):
    """CreateOrderV2DataIncomingPayment response model.

    Attributes:
        consumer_id: Идентификатор Плательщика. Используется для сохранения карты в эквайринге
        payment_url_ttl: Время действия ссылки на оплату в минутах
        purpose: Наименование пополнения в эквайринге
        redirect_fail_url: Redirect URL в случае ошибки
        redirect_url: URL адрес, куда будет перенаправлен клиент после оплаты
        type_: Способ оплаты
    """

    consumer_id: str | None = Field(None, max_length=200, alias="consumerId")
    payment_url_ttl: int = Field(..., alias="paymentUrlTtl")
    purpose: str = Field(..., max_length=256)
    redirect_fail_url: str = Field(..., alias="redirectFailUrl")
    redirect_url: str = Field(..., alias="redirectUrl")
    type_: str = Field(..., alias="type")


class CreateOrderV2DataReceipt(TochkaObject):
    """CreateOrderV2DataReceipt response model.

    Attributes:
        email: Почта для отправки чека
        name: Как называется позиция комиссии в чеке
        payment_method: Способ оплаты. full_payment – полная оплата, full_prepayment – предоплата 100%
        payment_object: Тип объекта для оплаты
        vat_type: Процент НДС
    """

    email: str
    name: str
    payment_method: CreateOrderV2DataReceiptPaymentMethod = Field(..., alias="paymentMethod")
    payment_object: CreateOrderV2DataReceiptPaymentObject = Field(..., alias="paymentObject")
    vat_type: CreateOrderV2DataReceiptVatType = Field(..., alias="vatType")


class CreateOrderV2DataServices(TochkaObject):
    """CreateOrderV2DataServices response model.

    Attributes:
        recipient: OrderRecipient
        commission: Общая сумма комиссси (комиссия за пополнение, за вывод, остаток – комиссия платформы)
        ext_id: Идентификатор со стороны партнера
        price: Сумма выплаты
        start_decision: Если заполнить confirmed, сразу после пополнения произойдет оплата получателю.
            Аналогично с rejected.
    """

    recipient: CreateOrderV2DataServicesRecipient = Field(..., alias="Recipient")
    commission: str
    ext_id: str = Field(..., alias="extId")
    price: str
    start_decision: CreateOrderV2DataServicesStartDecision = Field(..., alias="startDecision")


class CreateOrderV2DataServicesRecipient(TochkaObject):
    """CreateOrderV2DataServicesRecipient response model.

    Attributes:
        card_ext_id: Внешний идентификатор карты
        ext_id: Внешний идентификатор
        method: метод оплаты
    """

    card_ext_id: str = Field(..., alias="cardExtId")
    ext_id: str = Field(..., alias="extId")
    method: str


class GetOrderV2Response(TochkaObject):
    """GetOrderV2Response response model.

    Attributes:
        data: GetOrderResponseV2
        links: LinkModel
        meta: MetaModel
    """

    data: GetOrderV2ResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetOrderV2ResponseData(TochkaObject):
    """GetOrderV2ResponseData response model.

    Attributes:
        incoming_payment: Входящий платёж
        receipt: Данные чека
        services: Услуги
        created_at: Дата и время создания заказа
        ext_id: Внешний идентификатор заказа
        finished_at: Дата и время завершения заказа
        payed_at: Дата и время оплаты
        state: Состояние заказа
        version: Версия заказа
    """

    incoming_payment: GetOrderV2ResponseDataIncomingPayment = Field(..., alias="IncomingPayment")
    receipt: GetOrderV2ResponseDataReceipt | None = Field(None, alias="Receipt")
    services: list[GetOrderV2ResponseDataServices] = Field(..., alias="Services")
    created_at: TZDatetime | None = Field(None, alias="createdAt")
    ext_id: str = Field(..., alias="extId")
    finished_at: TZDatetime | None = Field(None, alias="finishedAt")
    payed_at: TZDatetime | None = Field(None, alias="payedAt")
    state: GetOrderV2ResponseDataState
    version: int


class GetOrderV2ResponseDataIncomingPayment(TochkaObject):
    """GetOrderV2ResponseDataIncomingPayment response model.

    Attributes:
        details: Детали платежа
        type_: Тип входящего платежа
    """

    details: GetOrderV2ResponseDataIncomingPaymentDetails = Field(..., alias="Details")
    type_: str = Field(..., alias="type")


class GetOrderV2ResponseDataIncomingPaymentDetails(TochkaObject):
    """GetOrderV2ResponseDataIncomingPaymentDetails response model.

    Attributes:
        consumer_id: Идентификатор плательщика
        fail_redirect_url: URL адрес, куда будет перенаправлен клиент в случае неуспешной оплаты
        payment_link: Ссылка на оплату
        purpose: Назначение платежа
        redirect_url: URL адрес, куда будет перенаправлен клиент после оплаты
        ttl: Время жизни ссылки в минутах
    """

    consumer_id: str | None = Field(None, alias="consumerId")
    fail_redirect_url: str | None = Field(None, alias="failRedirectUrl")
    payment_link: str | None = Field(None, alias="paymentLink")
    purpose: str
    redirect_url: str | None = Field(None, alias="redirectUrl")
    ttl: int | None = None


class GetOrderV2ResponseDataReceipt(TochkaObject):
    """GetOrderV2ResponseDataReceipt response model.

    Attributes:
        email: Email для чека
        name: Наименование товара/услуги
        payment_method: Признак способа расчёта
        payment_object: Признак предмета расчёта
        vat_type: Ставка НДС
    """

    email: str
    name: str
    payment_method: str = Field(..., alias="paymentMethod")
    payment_object: str = Field(..., alias="paymentObject")
    vat_type: str = Field(..., alias="vatType")


class GetOrderV2ResponseDataServices(TochkaObject):
    """GetOrderV2ResponseDataServices response model.

    Attributes:
        recipient: Получатель
        commission: Сумма всех комиссий по услуге
        decision: Решение по услуге
        decision_made_at: Дата и время принятия решения
        executed_at: Дата и время исполнения услуги
        ext_id: Идентификатор услуги
        income_payment_commission_sum: Комиссия эквайринга
        income_payment_commission_sum_nds: НДС комиссии эквайринга
        outgoing_payout_commission_sum: Комиссия за выплату
        outgoing_payout_commission_sum_nds: НДС комиссии за выплату
        platform_commission_sum: Комиссия платформы
        price: Стоимость услуги
        state: Статус услуги
    """

    recipient: GetOrderV2ResponseDataServicesRecipient = Field(..., alias="Recipient")
    commission: str | None = None
    decision: GetOrderV2ResponseDataServicesDecision
    decision_made_at: TZDatetime | None = Field(None, alias="decisionMadeAt")
    executed_at: TZDatetime | None = Field(None, alias="executedAt")
    ext_id: str = Field(..., alias="extId")
    income_payment_commission_sum: str | None = Field(None, alias="incomePaymentCommissionSum")
    income_payment_commission_sum_nds: str | None = Field(None, alias="incomePaymentCommissionSumNds")
    outgoing_payout_commission_sum: str = Field(..., alias="outgoingPayoutCommissionSum")
    outgoing_payout_commission_sum_nds: str | None = Field(None, alias="outgoingPayoutCommissionSumNds")
    platform_commission_sum: str | None = Field(None, alias="platformCommissionSum")
    price: str
    state: GetOrderV2ResponseDataServicesState


class GetOrderV2ResponseDataServicesRecipient(TochkaObject):
    """GetOrderV2ResponseDataServicesRecipient response model.

    Attributes:
        method: Метод выплаты
        ext_id: Идентификатор получателя
    """

    method: GetOrderV2ResponseDataServicesRecipientMethod = Field(..., alias="Method")
    ext_id: str = Field(..., alias="extId")


class GetOrderV2ResponseDataServicesRecipientMethod(TochkaObject):
    """GetOrderV2ResponseDataServicesRecipientMethod response model.

    Attributes:
        details: Детали метода выплаты
        payout_method_ext_id: Идентификатор метода выплаты
        type_: Тип метода выплаты
    """

    details: Any = Field(..., alias="Details")
    payout_method_ext_id: str = Field(..., alias="payoutMethodExtId")
    type_: GetOrderV2ResponseDataServicesRecipientMethodType = Field(..., alias="type")


class CreateOrderV3Response(TochkaObject):
    """CreateOrderV3Response response model.

    Attributes:
        data: CreateOrderResponse
        links: LinkModel
        meta: MetaModel
    """

    data: CreateOrderV3ResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateOrderV3ResponseData(TochkaObject):
    """CreateOrderV3ResponseData response model.

    Attributes:
        ext_id: Идентификатор
        payment_url: Ссылка на оплату заказа
    """

    ext_id: str = Field(..., alias="extId")
    payment_url: str = Field(..., alias="paymentUrl")


class CreateOrderV3Data(TochkaObject):
    """CreateOrderV3Data response model.

    Attributes:
        incoming_payment: IncomingPaymentV3
        receipt: Информация для чека
        services: Услуги
        ext_id: Внешний идентификатор заказа
    """

    incoming_payment: CreateOrderV3DataIncomingPayment = Field(..., alias="IncomingPayment")
    receipt: CreateOrderV3DataReceipt | None = Field(None, alias="Receipt")
    services: list[CreateOrderV3DataServices] = Field(..., min_length=1, max_length=50, alias="Services")
    ext_id: str = Field(..., alias="extId")


class CreateOrderV3DataIncomingPayment(TochkaObject):
    """CreateOrderV3DataIncomingPayment response model.

    Attributes:
        details: Детали оплаты
        type_: Способ оплаты
    """

    details: CreateOrderV3DataIncomingPaymentDetails = Field(..., alias="Details")
    type_: str = Field(..., alias="type")


class CreateOrderV3DataIncomingPaymentDetails(TochkaObject):
    """CreateOrderV3DataIncomingPaymentDetails response model.

    Attributes:
        card_needed: Нужна ли оплата картой
        consumer_id: Идентификатор Плательщика. Используется для сохранения карты в эквайринге
        fail_redirect_url: URL адрес, куда будет перенаправлен клиент в случае неуспешной оплаты
        purpose: Наименование пополнения в эквайринге
        redirect_url: URL адрес, куда будет перенаправлен клиент после оплаты
        sbp_needed: Нужна ли оплата через СБП
        ttl: Время жизни ссылки в минутах
    """

    card_needed: bool = Field(..., alias="cardNeeded")
    consumer_id: str | None = Field(None, max_length=200, alias="consumerId")
    fail_redirect_url: str = Field(..., alias="failRedirectUrl")
    purpose: str = Field(..., max_length=256)
    redirect_url: str = Field(..., alias="redirectUrl")
    sbp_needed: bool = Field(..., alias="sbpNeeded")
    ttl: int


class CreateOrderV3DataReceipt(TochkaObject):
    """CreateOrderV3DataReceipt response model.

    Attributes:
        email: Почта для отправки чека
        name: Как называется позиция комиссии в чеке
        payment_method: Способ оплаты. full_payment – полная оплата, full_prepayment – предоплата 100%
        payment_object: Тип объекта для оплаты
        vat_type: Процент НДС
    """

    email: str
    name: str
    payment_method: CreateOrderV3DataReceiptPaymentMethod = Field(..., alias="paymentMethod")
    payment_object: CreateOrderV3DataReceiptPaymentObject = Field(..., alias="paymentObject")
    vat_type: CreateOrderV3DataReceiptVatType = Field(..., alias="vatType")


class CreateOrderV3DataServices(TochkaObject):
    """CreateOrderV3DataServices response model.

    Attributes:
        recipient: OrderRecipientV3
        commission: Общая сумма комиссии
        ext_id: Идентификатор со стороны партнера
        price: Сумма выплаты
        start_decision: Если заполнить confirmed, сразу после пополнения произойдет оплата получателю.
            Аналогично с rejected.
    """

    recipient: CreateOrderV3DataServicesRecipient = Field(..., alias="Recipient")
    commission: str
    ext_id: str = Field(..., alias="extId")
    price: str
    start_decision: CreateOrderV3DataServicesStartDecision = Field(..., alias="startDecision")


class CreateOrderV3DataServicesRecipient(TochkaObject):
    """CreateOrderV3DataServicesRecipient response model.

    Attributes:
        ext_id: Внешний идентификатор получателя
        payout_ext_id: Внешний идентификатор метода выплаты
    """

    ext_id: str = Field(..., alias="extId")
    payout_ext_id: str = Field(..., alias="payoutExtId")


class GetOrderV3Response(TochkaObject):
    """GetOrderV3Response response model.

    Attributes:
        data: GetOrderResponseV3
        links: LinkModel
        meta: MetaModel
    """

    data: GetOrderV3ResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetOrderV3ResponseData(TochkaObject):
    """GetOrderV3ResponseData response model.

    Attributes:
        incoming_payment: Входящий платёж
        receipt: Данные чека
        services: Услуги
        created_at: Дата и время создания заказа
        ext_id: Внешний идентификатор заказа
        finished_at: Дата и время завершения заказа
        payed_at: Дата и время оплаты
        state: Состояние заказа
        version: Версия заказа
    """

    incoming_payment: GetOrderV3ResponseDataIncomingPayment = Field(..., alias="IncomingPayment")
    receipt: GetOrderV3ResponseDataReceipt | None = Field(None, alias="Receipt")
    services: list[GetOrderV3ResponseDataServices] = Field(..., alias="Services")
    created_at: TZDatetime | None = Field(None, alias="createdAt")
    ext_id: str = Field(..., alias="extId")
    finished_at: TZDatetime | None = Field(None, alias="finishedAt")
    payed_at: TZDatetime | None = Field(None, alias="payedAt")
    state: GetOrderV3ResponseDataState
    version: int


class GetOrderV3ResponseDataIncomingPayment(TochkaObject):
    """GetOrderV3ResponseDataIncomingPayment response model.

    Attributes:
        details: Детали платежа
        type_: Тип входящего платежа
    """

    details: GetOrderV3ResponseDataIncomingPaymentDetails = Field(..., alias="Details")
    type_: str = Field(..., alias="type")


class GetOrderV3ResponseDataIncomingPaymentDetails(TochkaObject):
    """GetOrderV3ResponseDataIncomingPaymentDetails response model.

    Attributes:
        consumer_id: ID плательщика
        fail_redirect_url: URL переадресации при ошибке оплаты
        payment_link: Ссылка на оплату
        purpose: Назначение платежа
        redirect_url: URL переадресации после оплаты
        ttl: Время жизни ссылки на оплату (секунды)
    """

    consumer_id: str | None = Field(None, alias="consumerId")
    fail_redirect_url: str | None = Field(None, alias="failRedirectUrl")
    payment_link: str | None = Field(None, alias="paymentLink")
    purpose: str
    redirect_url: str | None = Field(None, alias="redirectUrl")
    ttl: int | None = None


class GetOrderV3ResponseDataReceipt(TochkaObject):
    """GetOrderV3ResponseDataReceipt response model.

    Attributes:
        email: Email для чека
        name: Наименование товара/услуги
        payment_method: Признак способа расчёта
        payment_object: Признак предмета расчёта
        vat_type: Ставка НДС
    """

    email: str
    name: str
    payment_method: str = Field(..., alias="paymentMethod")
    payment_object: str = Field(..., alias="paymentObject")
    vat_type: str = Field(..., alias="vatType")


class GetOrderV3ResponseDataServices(TochkaObject):
    """GetOrderV3ResponseDataServices response model.

    Attributes:
        recipient: Получатель
        commission: Сумма всех комиссий по услуге
        decision: Решение по услуге
        decision_made_at: Дата и время принятия решения
        executed_at: Дата и время исполнения услуги
        ext_id: ID услуги, UUID
        income_payment_commission_sum: Комиссия эквайринга
        income_payment_commission_sum_nds: НДС комиссии эквайринга
        outgoing_payout_commission_sum: Комиссия за выплату
        outgoing_payout_commission_sum_nds: НДС комиссии за выплату
        platform_commission_sum: Комиссия платформы
        price: Стоимость услуги
        state: Статус услуги
    """

    recipient: GetOrderV3ResponseDataServicesRecipient = Field(..., alias="Recipient")
    commission: str | None = None
    decision: GetOrderV3ResponseDataServicesDecision
    decision_made_at: TZDatetime | None = Field(None, alias="decisionMadeAt")
    executed_at: TZDatetime | None = Field(None, alias="executedAt")
    ext_id: str = Field(..., alias="extId")
    income_payment_commission_sum: str | None = Field(None, alias="incomePaymentCommissionSum")
    income_payment_commission_sum_nds: str | None = Field(None, alias="incomePaymentCommissionSumNds")
    outgoing_payout_commission_sum: str | None = Field(None, alias="outgoingPayoutCommissionSum")
    outgoing_payout_commission_sum_nds: str | None = Field(None, alias="outgoingPayoutCommissionSumNds")
    platform_commission_sum: str | None = Field(None, alias="platformCommissionSum")
    price: str
    state: GetOrderV3ResponseDataServicesState


class GetOrderV3ResponseDataServicesRecipient(TochkaObject):
    """GetOrderV3ResponseDataServicesRecipient response model.

    Attributes:
        method: Метод выплаты
        ext_id: ID получателя, UUID
    """

    method: GetOrderV3ResponseDataServicesRecipientMethod = Field(..., alias="Method")
    ext_id: str = Field(..., alias="extId")


class GetOrderV3ResponseDataServicesRecipientMethod(TochkaObject):
    """GetOrderV3ResponseDataServicesRecipientMethod response model.

    Attributes:
        details: Детали метода выплаты
        payout_method_ext_id: ID метода выплаты, UUID
        type_: Тип метода выплаты
    """

    details: Any = Field(..., alias="Details")
    payout_method_ext_id: str = Field(..., alias="payoutMethodExtId")
    type_: GetOrderV3ResponseDataServicesRecipientMethodType = Field(..., alias="type")
