# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Получатели — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import Field

from ..enums.marketplace_recipients import (
    GetRecipientResponseDataPayoutMethodsMethodType,
    GetRecipientV2ResponseDataPayoutMethodsMethodType,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse

if TYPE_CHECKING:
    from ..methods.marketplace_recipients import (
        AddSbpRecipientPayoutMethod,
        GetRecipient,
        GetRecipientV2,
        UpdateRecipient,
    )


class CreateRecipientResponse(TochkaObject):
    """CreateRecipientResponse response model.

    Attributes:
        data: CreateRecipientResponse
        links: LinkModel
        meta: MetaModel
    """

    data: CreateRecipientResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateRecipientResponseData(TochkaObject):
    """CreateRecipientResponseData response model.

    Attributes:
        ext_id: Идентификатор в рамках Платформы
        name: Наименование получателя
    """

    ext_id: str = Field(..., alias="extId")
    name: str = Field(..., max_length=128)


class CreateRecipientData(TochkaObject):
    """CreateRecipientData response model.

    Attributes:
        sbp: Опциональный блок с данными получателя для выплат через СБП
        ext_id: Идентификатор в рамках Платформы
        name: Используется только для удобства вашего просмотра. Можно класть ваши ID как строку
    """

    sbp: CreateRecipientDataSbp | None = Field(None, alias="Sbp")
    ext_id: str = Field(..., alias="extId")
    name: str = Field(..., max_length=128)


class CreateRecipientDataSbp(TochkaObject):
    """Опциональный блок с данными получателя для выплат через СБП

    Attributes:
        first_name: Имя получателя
        last_name: Фамилия получателя
        middle_name: Опционально
        phone: Номер телефона получателя
    """

    first_name: str = Field(..., alias="firstName")
    last_name: str = Field(..., alias="lastName")
    middle_name: str | None = Field(None, alias="middleName")
    phone: str


class ListRecipientSbpBanksResponse(TochkaObject):
    """ListRecipientSbpBanksResponse response model.

    Attributes:
        data: ListRecipientBankSbpResponse
        links: LinkModel
        meta: MetaModel
    """

    data: ListRecipientSbpBanksResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class ListRecipientSbpBanksResponseData(TochkaObject):
    """ListRecipientSbpBanksResponseData response model.

    Attributes:
        banks: items
    """

    banks: list[ListRecipientSbpBanksResponseDataBanks] = Field(..., alias="Banks")


class ListRecipientSbpBanksResponseDataBanks(TochkaObject):
    """ListRecipientSbpBanksResponseDataBanks response model.

    Attributes:
        bank_code: БИК банка
        bank_id: Этот идентификатор нужно отправлять при сохранении данных получателя по СБП
        effective_date: Операционный день ОПКЦ СБП, на который̆ действует справочник Участников
        name: Название участника СБП (транслитерация на английском языке)
        name_rus: Наименование Участника СБП - Не обязательный
    """

    bank_code: str = Field(..., alias="bankCode")
    bank_id: str = Field(..., alias="bankId")
    effective_date: str = Field(..., alias="effectiveDate")
    name: str
    name_rus: str = Field(..., alias="nameRus")


class GetRecipientResponse(TochkaObject):
    """GetRecipientResponse response model.

    Attributes:
        data: GetRecipientResponse
        links: LinkModel
        meta: MetaModel
    """

    data: GetRecipientResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRecipientResponseData(TochkaObject):
    """GetRecipientResponseData response model.

    Attributes:
        payout_methods: Методы выплаты
        sbp: Опциональный блок с данными получателя для выплат через СБП
        created_at: Дата/время создания получателя
        ext_id: Идентификатор в рамках Платформы
        name: Наименование получателя
        updated_at: Дата/время обновления получателя
    """

    payout_methods: list[GetRecipientResponseDataPayoutMethods] | None = Field(None, alias="PayoutMethods")
    sbp: GetRecipientResponseDataSbp | None = Field(None, alias="Sbp")
    created_at: str | None = Field(None, alias="createdAt")
    ext_id: str = Field(..., alias="extId")
    name: str = Field(..., max_length=128)
    updated_at: str | None = Field(None, alias="updatedAt")

    def get_recipient(self) -> GetRecipient:
        """Build an awaitable :class:`GetRecipient` bound to this object (await to execute)."""
        from ..methods.marketplace_recipients import GetRecipient

        return GetRecipient(recipient_ext_id=self.ext_id).as_(self._client)

    def update_recipient(self, data: UpdateRecipientData) -> UpdateRecipient:
        """Build an awaitable :class:`UpdateRecipient` bound to this object (await to execute)."""
        from ..methods.marketplace_recipients import UpdateRecipient

        return UpdateRecipient(recipient_ext_id=self.ext_id, data=data).as_(self._client)

    def add_sbp_recipient_payout_method(
        self, data: AddSbpRecipientPayoutMethodData
    ) -> AddSbpRecipientPayoutMethod:
        """Build an awaitable :class:`AddSbpRecipientPayoutMethod` bound to this object (await to execute)."""
        from ..methods.marketplace_recipients import AddSbpRecipientPayoutMethod

        return AddSbpRecipientPayoutMethod(recipient_ext_id=self.ext_id, data=data).as_(self._client)

    def get_recipient_v2(self) -> GetRecipientV2:
        """Build an awaitable :class:`GetRecipientV2` bound to this object (await to execute)."""
        from ..methods.marketplace_recipients import GetRecipientV2

        return GetRecipientV2(recipient_ext_id=self.ext_id).as_(self._client)


class GetRecipientResponseDataPayoutMethods(TochkaObject):
    """GetRecipientResponseDataPayoutMethods response model.

    Attributes:
        ext_id: Идентификатор
        masked_card_number: Маскированный номер карты
        method_type: PayoutMethodType
    """

    ext_id: str = Field(..., alias="extId")
    masked_card_number: str | None = Field(None, alias="maskedCardNumber")
    method_type: GetRecipientResponseDataPayoutMethodsMethodType = Field(..., alias="methodType")


class GetRecipientResponseDataSbp(TochkaObject):
    """Опциональный блок с данными получателя для выплат через СБП

    Attributes:
        first_name: Имя получателя
        last_name: Фамилия получателя
        middle_name: Опционально
        phone: Номер телефона получателя
    """

    first_name: str = Field(..., alias="firstName")
    last_name: str = Field(..., alias="lastName")
    middle_name: str | None = Field(None, alias="middleName")
    phone: str


class UpdateRecipientResponse(TochkaObject):
    """UpdateRecipientResponse response model.

    Attributes:
        data: UpdateRecipientResponse
        links: LinkModel
        meta: MetaModel
    """

    data: UpdateRecipientResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class UpdateRecipientResponseData(TochkaObject):
    """UpdateRecipientResponseData response model.

    Attributes:
        version: Новая версия получателя
    """

    version: int


class UpdateRecipientData(TochkaObject):
    """UpdateRecipientData response model.

    Attributes:
        sbp: Можно обновить либо телефон, либо ФИО (имя и фамилия обязательны, отчество опционально). Если
            получатель создан без данных СБП, первое обновление допускается исключительно при наличии всех
            полей СБП
        version: Нужна для оптимистичной блокировки. Если версия не совпадёт с актуальной — обновление
            будет отклонено
    """

    sbp: UpdateRecipientDataSbp = Field(..., alias="Sbp")
    version: int = Field(..., ge=0)


class UpdateRecipientDataSbp(TochkaObject):
    """Можно обновить либо телефон, либо ФИО (имя и фамилия обязательны, отчество опционально). Если
    получатель создан без данных СБП, первое обновление допускается исключительно при наличии всех полей
    СБП

    Attributes:
        first_name: Указывается вместе с lastName, если обновляется ФИО
        last_name: Указывается вместе с firstName, если обновляется ФИО
        middle_name: Указывается вместе с firstName и lastName, если обновляется ФИО
        phone: Формат +7XXXXXXXXXX. Указывается, если обновляется телефон
    """

    first_name: str | None = Field(None, alias="firstName")
    last_name: str | None = Field(None, alias="lastName")
    middle_name: str | None = Field(None, alias="middleName")
    phone: str | None = None


class AddCardRecipientPayoutMethodResponse(TochkaObject):
    """AddCardRecipientPayoutMethodResponse response model.

    Attributes:
        data: CreateCardPayoutMethodResponse
        links: LinkModel
        meta: MetaModel
    """

    data: AddCardRecipientPayoutMethodResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class AddCardRecipientPayoutMethodResponseData(TochkaObject):
    """AddCardRecipientPayoutMethodResponseData response model.

    Attributes:
        form_url: URL формы для добавления карты
    """

    form_url: str = Field(..., alias="formUrl")


class AddCardRecipientPayoutMethodData(TochkaObject):
    """AddCardRecipientPayoutMethodData response model.

    Attributes:
        card_payout_method: CardPayoutMethod
    """

    card_payout_method: AddCardRecipientPayoutMethodDataCardPayoutMethod = Field(
        ..., alias="CardPayoutMethod"
    )


class AddCardRecipientPayoutMethodDataCardPayoutMethod(TochkaObject):
    """AddCardRecipientPayoutMethodDataCardPayoutMethod response model.

    Attributes:
        payout_method_ext_id: Идентификатор со стороны площадки
        redirect_url: URL адрес, куда будет перенаправлен клиент после оплаты
    """

    payout_method_ext_id: str = Field(..., alias="payoutMethodExtId")
    redirect_url: str = Field(..., alias="redirectUrl")


class AddSbpRecipientPayoutMethodResponse(TochkaObject):
    """AddSbpRecipientPayoutMethodResponse response model.

    Attributes:
        data: CreateSbpPayoutMethodResponse
        links: LinkModel
        meta: MetaModel
    """

    data: AddSbpRecipientPayoutMethodResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class AddSbpRecipientPayoutMethodResponseData(TochkaObject):
    """AddSbpRecipientPayoutMethodResponseData response model.

    Attributes:
        ext_id: Идентификатор со стороны площадки
    """

    ext_id: str = Field(..., alias="extId")


class AddSbpRecipientPayoutMethodData(TochkaObject):
    """AddSbpRecipientPayoutMethodData response model.

    Attributes:
        sbp_payout_method: SbpPayoutMethod
    """

    sbp_payout_method: AddSbpRecipientPayoutMethodDataSbpPayoutMethod = Field(..., alias="SbpPayoutMethod")


class AddSbpRecipientPayoutMethodDataSbpPayoutMethod(TochkaObject):
    """AddSbpRecipientPayoutMethodDataSbpPayoutMethod response model.

    Attributes:
        bank_id: Идентификатор банка получателя СБП
        payout_method_ext_id: Идентификатор со стороны площадки
    """

    bank_id: str = Field(..., alias="bankId")
    payout_method_ext_id: str = Field(..., alias="payoutMethodExtId")


class GetRecipientV2Response(TochkaObject):
    """GetRecipientV2Response response model.

    Attributes:
        data: GetRecipientResponseV2
        links: LinkModel
        meta: MetaModel
    """

    data: GetRecipientV2ResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRecipientV2ResponseData(TochkaObject):
    """GetRecipientV2ResponseData response model.

    Attributes:
        payout_methods: Методы выплаты
        sbp: Данные получателя для выплат через СБП
        created_at: Дата/время создания получателя
        ext_id: Идентификатор в рамках Платформы
        name: Наименование получателя
        updated_at: Дата/время обновления получателя
    """

    payout_methods: list[GetRecipientV2ResponseDataPayoutMethods] | None = Field(None, alias="PayoutMethods")
    sbp: GetRecipientV2ResponseDataSbp | None = Field(None, alias="Sbp")
    created_at: str | None = Field(None, alias="createdAt")
    ext_id: str = Field(..., alias="extId")
    name: str = Field(..., max_length=128)
    updated_at: str | None = Field(None, alias="updatedAt")


class GetRecipientV2ResponseDataPayoutMethods(TochkaObject):
    """GetRecipientV2ResponseDataPayoutMethods response model.

    Attributes:
        details: Детали метода выплаты
        ext_id: Идентификатор
        method_type: PayoutMethodType
    """

    details: Any = Field(..., alias="Details")
    ext_id: str = Field(..., alias="extId")
    method_type: GetRecipientV2ResponseDataPayoutMethodsMethodType = Field(..., alias="methodType")


class GetRecipientV2ResponseDataSbp(TochkaObject):
    """GetRecipientV2ResponseDataSbp response model.

    Attributes:
        first_name: Имя получателя
        last_name: Фамилия получателя
        middle_name: Опционально
        phone: Номер телефона получателя
    """

    first_name: str = Field(..., alias="firstName")
    last_name: str = Field(..., alias="lastName")
    middle_name: str | None = Field(None, alias="middleName")
    phone: str
