# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""СБП — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ._base import TochkaObject


class GenerateSbpQrcodeV2Params(TochkaObject):
    """GenerateSbpQrcodeV2Params response model.

    Attributes:
        amount: Сумма пополнения
        height: Высота изображения
        nominal_bic: БИК номинального счёта
        nominal_code: Номер номинального счёта
        purpose: Дополнительная информация от ТСП по платежу (в платеже будет указано стандартное
            назначение)
        width: Ширина изображения
    """

    amount: Any
    height: int = Field(300, ge=1, le=1500)
    merchant_id: str | None = None
    nominal_bic: str | None = None
    nominal_code: str | None = None
    purpose: str = Field(..., min_length=1, max_length=1500)
    source_name: str | None = Field(None, min_length=1, max_length=50)
    width: int = Field(300, ge=1, le=1500)
