# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Загрузка документов — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from ._base import TochkaObject


class UploadDocumentBeneficiaryResponse(TochkaObject):
    """UploadDocumentBeneficiaryResponse response model.

    Attributes:
        document_id: Идентификатор документа
    """

    document_id: str


class UploadDocumentDealResponse(TochkaObject):
    """UploadDocumentDealResponse response model.

    Attributes:
        document_id: Идентификатор документа
    """

    document_id: str
