# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платежи — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from datetime import date
from typing import Any

from pydantic import Field

from ..enums.nominal_payments import (
    ListPaymentsV2ParamsFiltersStatus,
    ListPaymentsV2ParamsFiltersType,
    ListPaymentsV2V2ParamsFiltersStatus,
    ListPaymentsV2V2ParamsFiltersType,
)
from ._base import TochkaObject
from .common import TZDatetime


class ComplianceCheckPaymentV2Params(TochkaObject):
    """ComplianceCheckPaymentV2Params response model.

    Attributes:
        amount: Сумма платежа
        payer_account: Номер номинального счёта плательщика, с которого планируется выплата
        payer_bank_code: БИК номинального счёта плательщика, с которого планируется выплата
        purpose: Назначение платежа
        recipient_account: Номер счёта получателя
        recipient_bank_code: БИК получателя
        recipient_inn: ИНН получателя
        recipient_name: Наименование получателя
    """

    amount: float
    payer_account: str | None = Field(None, min_length=20, max_length=20, pattern="^\\d{20}$")
    payer_bank_code: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    purpose: str | None = Field(None, min_length=1, max_length=210, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")
    recipient_account: str = Field(..., min_length=20, max_length=20, pattern="^\\d{20}$")
    recipient_bank_code: str = Field(..., min_length=9, max_length=9, pattern="^\\d{9}$")
    recipient_inn: str = Field(..., min_length=10, max_length=12)
    recipient_name: str = Field(..., min_length=1, max_length=255)


class GeneratePaymentOrderV2Params(TochkaObject):
    """GeneratePaymentOrderV2Params response model.

    Attributes:
        payment_id: Идентификатор платежа
    """

    payment_id: str


class GetPaymentV2Params(TochkaObject):
    """GetPaymentV2Params response model.

    Attributes:
        payment_id: Идентификатор платежа
    """

    payment_id: str


class IdentificationPaymentV2Params(TochkaObject):
    """IdentificationPaymentV2Params response model.

    Attributes:
        excess_refund: Излишек
        is_returned_payment: Идентификация возвращенного платежа
        owners: Владельцы денег
        payment_id: Идентификатор платежа
    """

    excess_refund: IdentificationPaymentV2ParamsExcessRefund | None = None
    is_returned_payment: bool = False
    owners: list[IdentificationPaymentV2ParamsOwners] | None = None
    payment_id: str


class IdentificationPaymentV2ParamsExcessRefund(TochkaObject):
    """IdentificationPaymentV2ParamsExcessRefund response model.

    Attributes:
        amount: Сумма возврата
    """

    amount: float


class IdentificationPaymentV2ParamsOwners(TochkaObject):
    """IdentificationPaymentV2ParamsOwners response model.

    Attributes:
        amount: Сумма зачисления
        virtual_account: Виртуальный счет типа standard
    """

    amount: float
    virtual_account: str


class IdentificationReturnedPaymentByDealV2Params(TochkaObject):
    """IdentificationReturnedPaymentByDealV2Params response model.

    Attributes:
        deal_id: Сделка к которой относится исходный платёж
        initial_payment_id: Идентификатор исходного платежа
        payment_id: Идентификатор возвращенного платежа
    """

    deal_id: str
    initial_payment_id: str | None = None
    payment_id: str


class ListPaymentsV2Params(TochkaObject):
    """ListPaymentsV2Params response model.

    Attributes:
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    filters: ListPaymentsV2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListPaymentsV2ParamsFilters(TochkaObject):
    """ListPaymentsV2ParamsFilters response model.

    Attributes:
        account: Номер счёта
        bic: Бик
        c2b_qr_code_id: QR-код
        create_date: Дата создания платежа
        identify: Платёж идентифицирован
        incoming: Признак входящего платежа
        status: Статус платежа
        type_: Тип платежа
        update_date: Дата последнего обновления платежа
        updated_at_from: Начало интервала для даты обновления платежа
        updated_at_to: Конец интервала для даты обновления платежа
    """

    account: str | None = Field(None, min_length=20, max_length=20, pattern="^\\d{20}$")
    bic: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    c2b_qr_code_id: str | None = None
    create_date: date | None = None
    identify: bool | None = None
    incoming: bool | None = None
    status: ListPaymentsV2ParamsFiltersStatus | None = None
    type_: ListPaymentsV2ParamsFiltersType | None = Field(None, alias="type")
    update_date: date | None = None
    updated_at_from: TZDatetime | None = None
    updated_at_to: TZDatetime | None = None


class ListPaymentsV2V2Params(TochkaObject):
    """ListPaymentsV2V2Params response model.

    Attributes:
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    filters: ListPaymentsV2V2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListPaymentsV2V2ParamsFilters(TochkaObject):
    """ListPaymentsV2V2ParamsFilters response model.

    Attributes:
        account: Номер счёта
        bic: Бик
        c2b_qr_code_id: QR-код
        create_date: Дата создания платежа
        identify: Платёж идентифицирован
        incoming: Признак входящего платежа
        status: Статус платежа
        type_: Тип платежа
        update_date: Дата последнего обновления платежа
        updated_at_from: Начало интервала для даты обновления платежа
        updated_at_to: Конец интервала для даты обновления платежа
    """

    account: str | None = Field(None, min_length=20, max_length=20, pattern="^\\d{20}$")
    bic: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    c2b_qr_code_id: str | None = None
    create_date: date | None = None
    identify: bool | None = None
    incoming: bool | None = None
    status: ListPaymentsV2V2ParamsFiltersStatus | None = None
    type_: ListPaymentsV2V2ParamsFiltersType | None = Field(None, alias="type")
    update_date: date | None = None
    updated_at_from: TZDatetime | None = None
    updated_at_to: TZDatetime | None = None


class PaymentOfTaxesV2Params(TochkaObject):
    """PaymentOfTaxesV2Params response model.

    Attributes:
        amount: Сумма платежа
        ext_key: Внешний идентификатор сделки
        payer: Данные плательщика
        recipients: Получатели
    """

    amount: float
    ext_key: str | None = Field(None, min_length=1, max_length=50)
    payer: PaymentOfTaxesV2ParamsPayer
    recipients: list[Any]


class PaymentOfTaxesV2ParamsPayer(TochkaObject):
    """PaymentOfTaxesV2ParamsPayer response model.

    Attributes:
        amount: Сумма платежа
    """

    amount: float
    virtual_account: str


class RefundPaymentV2Params(TochkaObject):
    """RefundPaymentV2Params response model.

    Attributes:
        allow_refund_sbp_v2: Выполнять ли возврат по новому флоу СБП выплат (без процессинга)
        amount: Сумма возврата
        document_number: Номер платёжного документа
        payment_id: Идентификатор платежа
        purpose: Назначение платежа
        purpose_nds: % НДС
        virtual_accounts: Информация по виртуальным счетам
    """

    allow_refund_sbp_v2: bool | None = None
    amount: float | None = None
    document_number: str | None = Field(None, min_length=1, max_length=6)
    payment_id: str
    purpose: str | None = Field(None, min_length=5, max_length=210, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")
    purpose_nds: float | None = None
    virtual_accounts: list[RefundPaymentV2ParamsVirtualAccounts] | None = None


class RefundPaymentV2ParamsVirtualAccounts(TochkaObject):
    """RefundPaymentV2ParamsVirtualAccounts response model.

    Attributes:
        amount: Сумма возврата
    """

    amount: float
    virtual_account: str
