# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Доступность сервиса — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import Any

from ._base import TochkaObject


class EchoV3Params(TochkaObject):
    """EchoV3Params response model.

    Attributes:
        text: Text
    """

    text: Any
