# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платёжными ссылками — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from datetime import date

from pydantic import Field

from ..enums.payment_links import (
    CreatePaymentOperationDataPaymentMode,
    CreatePaymentOperationResponseDataPaymentMode,
    CreatePaymentOperationResponseDataStatus,
    CreatePaymentOperationWithReceiptDataItemsMeasure,
    CreatePaymentOperationWithReceiptDataItemsPaymentMethod,
    CreatePaymentOperationWithReceiptDataItemsPaymentObject,
    CreatePaymentOperationWithReceiptDataItemsVatType,
    CreatePaymentOperationWithReceiptDataPaymentMode,
    CreatePaymentOperationWithReceiptDataTaxSystemCode,
    CreatePaymentOperationWithReceiptResponseDataItemsMeasure,
    CreatePaymentOperationWithReceiptResponseDataItemsPaymentMethod,
    CreatePaymentOperationWithReceiptResponseDataItemsPaymentObject,
    CreatePaymentOperationWithReceiptResponseDataItemsVatType,
    CreatePaymentOperationWithReceiptResponseDataPaymentMode,
    CreatePaymentOperationWithReceiptResponseDataStatus,
    CreatePaymentOperationWithReceiptResponseDataTaxSystemCode,
    GetPaymentOperationInfoResponseDataOperationItemsMeasure,
    GetPaymentOperationInfoResponseDataOperationItemsPaymentMethod,
    GetPaymentOperationInfoResponseDataOperationItemsPaymentObject,
    GetPaymentOperationInfoResponseDataOperationItemsVatType,
    GetPaymentOperationInfoResponseDataOperationOrderType,
    GetPaymentOperationInfoResponseDataOperationPaymentMode,
    GetPaymentOperationInfoResponseDataOperationPaymentType,
    GetPaymentOperationInfoResponseDataOperationStatus,
    GetPaymentOperationInfoResponseDataOperationTaxSystemCode,
    GetPaymentOperationListResponseDataOperationItemsMeasure,
    GetPaymentOperationListResponseDataOperationItemsPaymentMethod,
    GetPaymentOperationListResponseDataOperationItemsPaymentObject,
    GetPaymentOperationListResponseDataOperationItemsVatType,
    GetPaymentOperationListResponseDataOperationOrderType,
    GetPaymentOperationListResponseDataOperationPaymentMode,
    GetPaymentOperationListResponseDataOperationPaymentType,
    GetPaymentOperationListResponseDataOperationStatus,
    GetPaymentOperationListResponseDataOperationTaxSystemCode,
    GetPaymentRegistryResponseDataRegistryPaymentsStatus,
    GetPaymentRegistryResponseDataRegistryPaymentType,
    GetRetailersResponseDataRetailerPaymentModes,
    GetRetailersResponseDataRetailerStatus,
)
from ._base import TochkaObject
from ._shared import ResultResponse, SelfResponse, TotalPagesResponse


class GetPaymentOperationListResponse(TochkaObject):
    """GetPaymentOperationListResponse response model.

    Attributes:
        data: AcquiringGetPaymentOperationListResponseModel
        links: PaginatedLinkModel
        meta: MetaModel
    """

    data: GetPaymentOperationListResponseData = Field(..., alias="Data")
    links: GetPaymentOperationListResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentOperationListResponseData(TochkaObject):
    """GetPaymentOperationListResponseData response model.

    Attributes:
        operation: Operation
    """

    operation: list[GetPaymentOperationListResponseDataOperation] = Field(..., alias="Operation")


class GetPaymentOperationListResponseDataOperation(TochkaObject):
    """GetPaymentOperationListResponseDataOperation response model.

    Attributes:
        client: Данные покупателя
        cof_token: Информация о карте плательщика
        items: Список товаров в заказе
        order: Список операций, связанных с платежом.
        supplier: Данные поставщика
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        created_at: Дата и время создания операции. Используется стандарт ISO8601
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        paid_at: Дата и время оплаты
        payment_id: Идентификатор платежа в процессинге или СБП
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        payment_type: Присутствует, если оплата произведена
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Отсутствует, если при создании платежа назначение не было указано
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        status: Статус платежа
        tax_system_code: Перечисление для выдачи результатов из openapi.
        transaction_id: Используется для возврата при оплате по СБП
    """

    client: GetPaymentOperationListResponseDataOperationClient | None = Field(None, alias="Client")
    cof_token: GetPaymentOperationListResponseDataOperationCofToken | None = Field(None, alias="CofToken")
    items: list[GetPaymentOperationListResponseDataOperationItems] | None = Field(
        None, min_length=1, alias="Items"
    )
    order: list[GetPaymentOperationListResponseDataOperationOrder] = Field(..., alias="Order")
    supplier: GetPaymentOperationListResponseDataOperationSupplier | None = Field(None, alias="Supplier")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    created_at: str = Field(..., alias="createdAt")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    paid_at: str | None = Field(None, alias="paidAt")
    payment_id: str | None = Field(None, alias="paymentId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[GetPaymentOperationListResponseDataOperationPaymentMode] | None = Field(
        None, min_length=1, alias="paymentMode"
    )
    payment_type: GetPaymentOperationListResponseDataOperationPaymentType | None = Field(
        None, alias="paymentType"
    )
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    status: GetPaymentOperationListResponseDataOperationStatus
    tax_system_code: GetPaymentOperationListResponseDataOperationTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )
    transaction_id: str | None = Field(None, alias="transactionId")


class GetPaymentOperationListResponseDataOperationClient(TochkaObject):
    """GetPaymentOperationListResponseDataOperationClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class GetPaymentOperationListResponseDataOperationCofToken(TochkaObject):
    """GetPaymentOperationListResponseDataOperationCofToken response model.

    Attributes:
        card_type: Тип платёжной системы
        masked_pan: Маскированный номер карты
        token_card_id: Токен карты покупателя
    """

    card_type: str | None = Field(None, alias="cardType")
    masked_pan: str | None = Field(None, alias="maskedPan")
    token_card_id: str | None = Field(None, alias="tokenCardId")


class GetPaymentOperationListResponseDataOperationItems(TochkaObject):
    """GetPaymentOperationListResponseDataOperationItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: GetPaymentOperationListResponseDataOperationItemsSupplier | None = Field(None, alias="Supplier")
    amount: float
    measure: GetPaymentOperationListResponseDataOperationItemsMeasure = (
        GetPaymentOperationListResponseDataOperationItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: GetPaymentOperationListResponseDataOperationItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: GetPaymentOperationListResponseDataOperationItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float
    vat_type: GetPaymentOperationListResponseDataOperationItemsVatType | None = Field(None, alias="vatType")


class GetPaymentOperationListResponseDataOperationItemsSupplier(TochkaObject):
    """GetPaymentOperationListResponseDataOperationItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetPaymentOperationListResponseDataOperationOrder(TochkaObject):
    """GetPaymentOperationListResponseDataOperationOrder response model.

    Attributes:
        amount: Сумма операции
        order_id: Идентификатор платежа
        time: Время операции
        type_: Тип операции
    """

    amount: float
    order_id: str = Field(..., alias="orderId")
    time: str
    type_: GetPaymentOperationListResponseDataOperationOrderType = Field(..., alias="type")


class GetPaymentOperationListResponseDataOperationSupplier(TochkaObject):
    """GetPaymentOperationListResponseDataOperationSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetPaymentOperationListResponseLinks(TochkaObject):
    """GetPaymentOperationListResponseLinks response model.

    Attributes:
        first: First
        last: Last
        next: Next
        prev: Prev
        self: Self
    """

    first: str | None = Field(None, min_length=1, max_length=2083)
    last: str | None = Field(None, min_length=1, max_length=2083)
    next: str | None = Field(None, min_length=1, max_length=2083)
    prev: str | None = Field(None, min_length=1, max_length=2083)
    self: str = Field(..., min_length=1, max_length=2083)


class CreatePaymentOperationResponse(TochkaObject):
    """CreatePaymentOperationResponse response model.

    Attributes:
        data: AcquiringCreatePaymentOperationResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: CreatePaymentOperationResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreatePaymentOperationResponseData(TochkaObject):
    """CreatePaymentOperationResponseData response model.

    Attributes:
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Назначение платежа
        status: Статус операции
        ttl: Время жизни платёжной ссылки в минутах
    """

    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[CreatePaymentOperationResponseDataPaymentMode] = Field(
        ..., min_length=1, alias="paymentMode"
    )
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str
    status: CreatePaymentOperationResponseDataStatus = CreatePaymentOperationResponseDataStatus.CREATED
    ttl: int = Field(10080, ge=1, le=44640)


class CreatePaymentOperationData(TochkaObject):
    """CreatePaymentOperationData response model.

    Attributes:
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Назначение платежа
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        save_card: Предложить покупателю сохранить карту
        ttl: Время жизни платёжной ссылки в минутах
    """

    amount: float = Field(..., gt=0)
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, min_length=15, max_length=15, alias="merchantId")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[CreatePaymentOperationDataPaymentMode] = Field(..., min_length=1, alias="paymentMode")
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str = Field(..., min_length=1, max_length=140)
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    save_card: bool | None = Field(None, alias="saveCard")
    ttl: int = Field(10080, ge=1, le=44640)


class GetPaymentOperationInfoResponse(TochkaObject):
    """GetPaymentOperationInfoResponse response model.

    Attributes:
        data: AcquiringGetPaymentOperationListResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetPaymentOperationInfoResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentOperationInfoResponseData(TochkaObject):
    """GetPaymentOperationInfoResponseData response model.

    Attributes:
        operation: Operation
    """

    operation: list[GetPaymentOperationInfoResponseDataOperation] = Field(..., alias="Operation")


class GetPaymentOperationInfoResponseDataOperation(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperation response model.

    Attributes:
        client: Данные покупателя
        cof_token: Информация о карте плательщика
        items: Список товаров в заказе
        order: Список операций, связанных с платежом.
        supplier: Данные поставщика
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        created_at: Дата и время создания операции. Используется стандарт ISO8601
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        paid_at: Дата и время оплаты
        payment_id: Идентификатор платежа в процессинге или СБП
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        payment_type: Присутствует, если оплата произведена
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Отсутствует, если при создании платежа назначение не было указано
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        status: Статус платежа
        tax_system_code: Перечисление для выдачи результатов из openapi.
        transaction_id: Используется для возврата при оплате по СБП
    """

    client: GetPaymentOperationInfoResponseDataOperationClient | None = Field(None, alias="Client")
    cof_token: GetPaymentOperationInfoResponseDataOperationCofToken | None = Field(None, alias="CofToken")
    items: list[GetPaymentOperationInfoResponseDataOperationItems] | None = Field(
        None, min_length=1, alias="Items"
    )
    order: list[GetPaymentOperationInfoResponseDataOperationOrder] = Field(..., alias="Order")
    supplier: GetPaymentOperationInfoResponseDataOperationSupplier | None = Field(None, alias="Supplier")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    created_at: str = Field(..., alias="createdAt")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    paid_at: str | None = Field(None, alias="paidAt")
    payment_id: str | None = Field(None, alias="paymentId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[GetPaymentOperationInfoResponseDataOperationPaymentMode] | None = Field(
        None, min_length=1, alias="paymentMode"
    )
    payment_type: GetPaymentOperationInfoResponseDataOperationPaymentType | None = Field(
        None, alias="paymentType"
    )
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    status: GetPaymentOperationInfoResponseDataOperationStatus
    tax_system_code: GetPaymentOperationInfoResponseDataOperationTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )
    transaction_id: str | None = Field(None, alias="transactionId")


class GetPaymentOperationInfoResponseDataOperationClient(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class GetPaymentOperationInfoResponseDataOperationCofToken(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationCofToken response model.

    Attributes:
        card_type: Тип платёжной системы
        masked_pan: Маскированный номер карты
        token_card_id: Токен карты покупателя
    """

    card_type: str | None = Field(None, alias="cardType")
    masked_pan: str | None = Field(None, alias="maskedPan")
    token_card_id: str | None = Field(None, alias="tokenCardId")


class GetPaymentOperationInfoResponseDataOperationItems(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: GetPaymentOperationInfoResponseDataOperationItemsSupplier | None = Field(None, alias="Supplier")
    amount: float
    measure: GetPaymentOperationInfoResponseDataOperationItemsMeasure = (
        GetPaymentOperationInfoResponseDataOperationItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: GetPaymentOperationInfoResponseDataOperationItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: GetPaymentOperationInfoResponseDataOperationItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float
    vat_type: GetPaymentOperationInfoResponseDataOperationItemsVatType | None = Field(None, alias="vatType")


class GetPaymentOperationInfoResponseDataOperationItemsSupplier(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetPaymentOperationInfoResponseDataOperationOrder(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationOrder response model.

    Attributes:
        amount: Сумма операции
        order_id: Идентификатор платежа
        time: Время операции
        type_: Тип операции
    """

    amount: float
    order_id: str = Field(..., alias="orderId")
    time: str
    type_: GetPaymentOperationInfoResponseDataOperationOrderType = Field(..., alias="type")


class GetPaymentOperationInfoResponseDataOperationSupplier(TochkaObject):
    """GetPaymentOperationInfoResponseDataOperationSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CapturePaymentResponse(TochkaObject):
    """CapturePaymentResponse response model.

    Attributes:
        data: BooleanResponse
        links: LinkModel
        meta: MetaModel
    """

    data: ResultResponse = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class RefundPaymentOperationResponse(TochkaObject):
    """RefundPaymentOperationResponse response model.

    Attributes:
        data: AcquiringPaymentOperationRefundModel
        links: LinkModel
        meta: MetaModel
    """

    data: RefundPaymentOperationResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class RefundPaymentOperationResponseData(TochkaObject):
    """RefundPaymentOperationResponseData response model.

    Attributes:
        amount: Сумма платежа
        date_: Дата запроса на возврат
        is_refund: Оформлен ли возврат
        operation_id: Идентификатор платежа
        order_id: Идентификатор операции возрата
    """

    amount: float
    date_: date = Field(..., alias="date")
    is_refund: bool = Field(..., alias="isRefund")
    operation_id: str = Field(..., alias="operationId")
    order_id: str = Field(..., alias="orderId")


class RefundPaymentOperationData(TochkaObject):
    """RefundPaymentOperationData response model.

    Attributes:
        amount: Не больше суммы оплаты
    """

    amount: float = Field(..., gt=0)


class CreatePaymentOperationWithReceiptResponse(TochkaObject):
    """CreatePaymentOperationWithReceiptResponse response model.

    Attributes:
        data: AcquiringCreatePaymentOperationWithReceiptResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: CreatePaymentOperationWithReceiptResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreatePaymentOperationWithReceiptResponseData(TochkaObject):
    """CreatePaymentOperationWithReceiptResponseData response model.

    Attributes:
        client: Данные покупателя
        items: Список товаров в заказе
        supplier: Данные поставщика
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Назначение платежа
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        status: Статус операции
        tax_system_code: Система налогообложения
        ttl: Время жизни платёжной ссылки в минутах
    """

    client: CreatePaymentOperationWithReceiptResponseDataClient = Field(..., alias="Client")
    items: list[CreatePaymentOperationWithReceiptResponseDataItems] = Field(..., min_length=1, alias="Items")
    supplier: CreatePaymentOperationWithReceiptResponseDataSupplier | None = Field(None, alias="Supplier")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[CreatePaymentOperationWithReceiptResponseDataPaymentMode] = Field(
        ..., min_length=1, alias="paymentMode"
    )
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    status: CreatePaymentOperationWithReceiptResponseDataStatus = (
        CreatePaymentOperationWithReceiptResponseDataStatus.CREATED
    )
    tax_system_code: CreatePaymentOperationWithReceiptResponseDataTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )
    ttl: int = Field(10080, ge=1, le=44640)


class CreatePaymentOperationWithReceiptResponseDataClient(TochkaObject):
    """CreatePaymentOperationWithReceiptResponseDataClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class CreatePaymentOperationWithReceiptResponseDataItems(TochkaObject):
    """CreatePaymentOperationWithReceiptResponseDataItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: CreatePaymentOperationWithReceiptResponseDataItemsSupplier | None = Field(
        None, alias="Supplier"
    )
    amount: float
    measure: CreatePaymentOperationWithReceiptResponseDataItemsMeasure = (
        CreatePaymentOperationWithReceiptResponseDataItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: CreatePaymentOperationWithReceiptResponseDataItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: CreatePaymentOperationWithReceiptResponseDataItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float
    vat_type: CreatePaymentOperationWithReceiptResponseDataItemsVatType | None = Field(None, alias="vatType")


class CreatePaymentOperationWithReceiptResponseDataItemsSupplier(TochkaObject):
    """CreatePaymentOperationWithReceiptResponseDataItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreatePaymentOperationWithReceiptResponseDataSupplier(TochkaObject):
    """CreatePaymentOperationWithReceiptResponseDataSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreatePaymentOperationWithReceiptData(TochkaObject):
    """CreatePaymentOperationWithReceiptData response model.

    Attributes:
        client: Данные покупателя
        items: Список товаров в заказе
        supplier: Данные поставщика
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        payment_link_id: Уникальный номер заказа
        payment_mode: Способ оплаты
        pre_authorization: Создать платёж с двухэтапной оплатой
        purpose: Назначение платежа
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        save_card: Предложить покупателю сохранить карту
        tax_system_code: Система налогообложения
        ttl: Время жизни платёжной ссылки в минутах
    """

    client: CreatePaymentOperationWithReceiptDataClient = Field(..., alias="Client")
    items: list[CreatePaymentOperationWithReceiptDataItems] = Field(..., min_length=1, alias="Items")
    supplier: CreatePaymentOperationWithReceiptDataSupplier | None = Field(None, alias="Supplier")
    amount: float = Field(..., gt=0)
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, min_length=15, max_length=15, alias="merchantId")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    payment_mode: list[CreatePaymentOperationWithReceiptDataPaymentMode] = Field(
        ..., min_length=1, alias="paymentMode"
    )
    pre_authorization: bool | None = Field(None, alias="preAuthorization")
    purpose: str = Field(..., min_length=1, max_length=140)
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    save_card: bool | None = Field(None, alias="saveCard")
    tax_system_code: CreatePaymentOperationWithReceiptDataTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )
    ttl: int = Field(10080, ge=1, le=44640)


class CreatePaymentOperationWithReceiptDataClient(TochkaObject):
    """CreatePaymentOperationWithReceiptDataClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class CreatePaymentOperationWithReceiptDataItems(TochkaObject):
    """CreatePaymentOperationWithReceiptDataItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: CreatePaymentOperationWithReceiptDataItemsSupplier | None = Field(None, alias="Supplier")
    amount: float = Field(..., gt=0)
    measure: CreatePaymentOperationWithReceiptDataItemsMeasure = (
        CreatePaymentOperationWithReceiptDataItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: CreatePaymentOperationWithReceiptDataItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: CreatePaymentOperationWithReceiptDataItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float = Field(..., gt=0)
    vat_type: CreatePaymentOperationWithReceiptDataItemsVatType | None = Field(None, alias="vatType")


class CreatePaymentOperationWithReceiptDataItemsSupplier(TochkaObject):
    """CreatePaymentOperationWithReceiptDataItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreatePaymentOperationWithReceiptDataSupplier(TochkaObject):
    """CreatePaymentOperationWithReceiptDataSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetPaymentRegistryResponse(TochkaObject):
    """GetPaymentRegistryResponse response model.

    Attributes:
        data: AcquiringPaymentRegistryModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetPaymentRegistryResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentRegistryResponseData(TochkaObject):
    """GetPaymentRegistryResponseData response model.

    Attributes:
        registry: Registry
    """

    registry: list[GetPaymentRegistryResponseDataRegistry] = Field(..., alias="Registry")


class GetPaymentRegistryResponseDataRegistry(TochkaObject):
    """GetPaymentRegistryResponseDataRegistry response model.

    Attributes:
        payment_id: Уникальный идентификатор платежа
        payment_type: Тип оплаты
        payments: Список товаров в заказе
        total_amount: Сумма всех позиций из этого блока
    """

    payment_id: str | None = Field(None, alias="paymentId")
    payment_type: GetPaymentRegistryResponseDataRegistryPaymentType = Field(..., alias="paymentType")
    payments: list[GetPaymentRegistryResponseDataRegistryPayments] = Field(..., min_length=1)
    total_amount: float = Field(..., alias="totalAmount")


class GetPaymentRegistryResponseDataRegistryPayments(TochkaObject):
    """GetPaymentRegistryResponseDataRegistryPayments response model.

    Attributes:
        amount: Сумма платежа
        commission: Комиссия за зачисление платежа
        enrollment_amount: Сумма за вычетом комиссии
        number: Номер платежа
        operation_id: Идентификатор платежа
        payment_link: Ссылка на оплату
        purpose: Назначение платежа
        status: Статус операции
        time: Дата и время создания операции. Используется стандарт ISO8601
    """

    amount: float
    commission: float
    enrollment_amount: float = Field(..., alias="enrollmentAmount")
    number: str
    operation_id: str = Field(..., alias="operationId")
    payment_link: str = Field(..., alias="paymentLink")
    purpose: str
    status: GetPaymentRegistryResponseDataRegistryPaymentsStatus = (
        GetPaymentRegistryResponseDataRegistryPaymentsStatus.CREATED
    )
    time: str


class GetRetailersResponse(TochkaObject):
    """GetRetailersResponse response model.

    Attributes:
        data: AcquiringRetailerListModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetRetailersResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRetailersResponseData(TochkaObject):
    """GetRetailersResponseData response model.

    Attributes:
        retailer: Retailer
    """

    retailer: list[GetRetailersResponseDataRetailer] = Field(..., alias="Retailer")


class GetRetailersResponseDataRetailer(TochkaObject):
    """GetRetailersResponseDataRetailer response model.

    Attributes:
        cashbox: Название подключённой кассы
        is_active: Статус готовности к работе
        mcc: Код МСС
        merchant_id: Может отсутствовать при значениях поля status: NEW, ADDRESS_DADATA и OPEN_ACCOUNT
        name: Наименование
        payment_modes: Способ оплаты
        rate: Комиссия
        status: Статус регистрации
        terminal_id: Будет заполнен при значениях поля status: TERMINAL_CREATED, FILE_SENT, REG
        url: Сайт регистрации
    """

    cashbox: str | None = None
    is_active: bool = Field(..., alias="isActive")
    mcc: str
    merchant_id: str | None = Field(None, alias="merchantId")
    name: str
    payment_modes: list[GetRetailersResponseDataRetailerPaymentModes] = Field(
        ..., min_length=0, alias="paymentModes"
    )
    rate: float
    status: GetRetailersResponseDataRetailerStatus
    terminal_id: str | None = Field(None, alias="terminalId")
    url: str | None = None
