# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с ЮЛ — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import Field

from ..enums.sbp_legal_entities import (
    GetAccountsListResponseDataAccountListStatus,
    GetCustomerInfoResponseDataAccountListStatus,
    GetCustomerInfoResponseDataMerchantListCapabilities,
    GetCustomerInfoResponseDataMerchantListStatus,
    GetCustomerInfoResponseDataStatus,
    GetLegalEntityResponseDataStatus,
    SetLegalEntityStatusDataStatus,
)
from ._base import TochkaObject
from ._shared import ResultResponse, SelfResponse, TotalPagesResponse

if TYPE_CHECKING:
    from ..methods.sbp_legal_entities import GetAccountsList, GetLegalEntity, SetLegalEntityStatus


class GetAccountsListResponse(TochkaObject):
    """GetAccountsListResponse response model.

    Attributes:
        data: AccountListResponse
        links: LinkModel
        meta: MetaModel
    """

    data: GetAccountsListResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetAccountsListResponseData(TochkaObject):
    """GetAccountsListResponseData response model.

    Attributes:
        account_list: Accountlist
    """

    account_list: list[GetAccountsListResponseDataAccountList] = Field(..., alias="AccountList")


class GetAccountsListResponseDataAccountList(TochkaObject):
    """GetAccountsListResponseDataAccountList response model.

    Attributes:
        account_id: Уникальный и неизменный идентификатор счёта
        created_at: Время регистрации
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        status: Статус объекта
    """

    account_id: str = Field(..., alias="accountId")
    created_at: str = Field(..., alias="createdAt")
    legal_id: str = Field(..., alias="legalId")
    status: GetAccountsListResponseDataAccountListStatus


class GetCustomerInfoResponse(TochkaObject):
    """GetCustomerInfoResponse response model.

    Attributes:
        data: CustomerInfoResponseV3
        links: LinkModel
        meta: MetaModel
    """

    data: GetCustomerInfoResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetCustomerInfoResponseData(TochkaObject):
    """GetCustomerInfoResponseData response model.

    Attributes:
        account_list: Accountlist
        merchant_list: Merchantlist
        address: Юридический адрес
        bank_code: БИК банка клиента
        city: Город
        country_code: код страны-регистрации юридического лица, в формате \"ISO 3166, Alpha-2\"
        country_sub_division_code: Код региона-регистрации юридического лица, первые две цифры кода ОКТМО
        created_at: Время регистрации
        customer_code: Уникальный код клиента
        entity_type: Организационно-правовая форма юридического лица
        inn: ИНН
        kpp: КПП
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        name: Полное наименование юридического лица
        ogrn: ОГРН
        status: Статус объекта
        zip_code: Индекс
    """

    account_list: list[GetCustomerInfoResponseDataAccountList] | None = Field(None, alias="AccountList")
    merchant_list: list[GetCustomerInfoResponseDataMerchantList] | None = Field(None, alias="MerchantList")
    address: str | None = None
    bank_code: str = Field(..., alias="bankCode")
    city: str | None = None
    country_code: str = Field(..., alias="countryCode")
    country_sub_division_code: str | None = Field(None, alias="countrySubDivisionCode")
    created_at: str = Field(..., alias="createdAt")
    customer_code: str = Field(..., alias="customerCode")
    entity_type: str | None = Field(None, alias="entityType")
    inn: str
    kpp: str | None = None
    legal_id: str = Field(..., alias="legalId")
    name: str
    ogrn: str
    status: GetCustomerInfoResponseDataStatus
    zip_code: str | None = Field(None, alias="zipCode")


class GetCustomerInfoResponseDataAccountList(TochkaObject):
    """GetCustomerInfoResponseDataAccountList response model.

    Attributes:
        account_id: Уникальный и неизменный идентификатор счёта
        created_at: Время регистрации
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        status: Статус объекта
    """

    account_id: str = Field(..., alias="accountId")
    created_at: str = Field(..., alias="createdAt")
    legal_id: str = Field(..., alias="legalId")
    status: GetCustomerInfoResponseDataAccountListStatus


class GetCustomerInfoResponseDataMerchantList(TochkaObject):
    """GetCustomerInfoResponseDataMerchantList response model.

    Attributes:
        additional_contacts: Дополнительные контакты
        address: Юридический адрес
        brand_name: Название ТСП (имя по вывеске)
        capabilities: `001` - только QR Static `010` - только QR Dynamic `011` - QR Static и QR Dynamic
            `100` - Только QR Subscription `101` - QR Subscription и QR Static `110` - QR Subscription и QR
            Dynamic `111` - QR Static, QR Dynamic и QR Subscription
        city: Город
        contact_phone_number: \"Контактный номер телефона ТСП
        country_code: код страны-регистрации юридического лица, в формате \"ISO 3166, Alpha-2\"
        country_sub_division_code: Код региона-регистрации юридического лица, первые две цифры кода ОКТМО
        created_at: Время регистрации
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        mcc: MCC код
        merchant_id: Идентификатор ТСП
        status: Статус объекта
        zip_code: Индекс
    """

    additional_contacts: list[dict[str, Any]] | None = Field(None, alias="additionalContacts")
    address: str | None = None
    brand_name: str = Field(..., alias="brandName")
    capabilities: GetCustomerInfoResponseDataMerchantListCapabilities
    city: str | None = None
    contact_phone_number: str | None = Field(None, alias="contactPhoneNumber")
    country_code: str = Field(..., alias="countryCode")
    country_sub_division_code: str | None = Field(None, alias="countrySubDivisionCode")
    created_at: str = Field(..., alias="createdAt")
    legal_id: str = Field(..., alias="legalId")
    mcc: str
    merchant_id: str = Field(..., max_length=12, alias="merchantId")
    status: GetCustomerInfoResponseDataMerchantListStatus
    zip_code: str | None = Field(None, alias="zipCode")


class GetLegalEntityResponse(TochkaObject):
    """GetLegalEntityResponse response model.

    Attributes:
        data: LegalEntity
        links: LinkModel
        meta: MetaModel
    """

    data: GetLegalEntityResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetLegalEntityResponseData(TochkaObject):
    """GetLegalEntityResponseData response model.

    Attributes:
        address: Юридический адрес
        city: Город
        country_code: код страны-регистрации юридического лица, в формате \"ISO 3166, Alpha-2\"
        country_sub_division_code: Код региона-регистрации юридического лица, первые две цифры кода ОКТМО
        created_at: Время регистрации
        customer_code: Уникальный код клиента
        entity_type: Организационно-правовая форма юридического лица
        inn: ИНН
        kpp: КПП
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        name: Полное наименование юридического лица
        ogrn: ОГРН
        status: Статус объекта
        zip_code: Индекс
    """

    address: str | None = None
    city: str | None = None
    country_code: str = Field(..., alias="countryCode")
    country_sub_division_code: str | None = Field(None, alias="countrySubDivisionCode")
    created_at: str = Field(..., alias="createdAt")
    customer_code: str = Field(..., alias="customerCode")
    entity_type: str | None = Field(None, alias="entityType")
    inn: str
    kpp: str | None = None
    legal_id: str = Field(..., alias="legalId")
    name: str
    ogrn: str
    status: GetLegalEntityResponseDataStatus
    zip_code: str | None = Field(None, alias="zipCode")

    def get_accounts_list(self) -> GetAccountsList:
        """Build an awaitable :class:`GetAccountsList` bound to this object (await to execute)."""
        from ..methods.sbp_legal_entities import GetAccountsList

        return GetAccountsList(legal_id=self.legal_id).as_(self._client)

    def get_legal_entity(self) -> GetLegalEntity:
        """Build an awaitable :class:`GetLegalEntity` bound to this object (await to execute)."""
        from ..methods.sbp_legal_entities import GetLegalEntity

        return GetLegalEntity(legal_id=self.legal_id).as_(self._client)

    def set_legal_entity_status(self, data: SetLegalEntityStatusData) -> SetLegalEntityStatus:
        """Build an awaitable :class:`SetLegalEntityStatus` bound to this object (await to execute)."""
        from ..methods.sbp_legal_entities import SetLegalEntityStatus

        return SetLegalEntityStatus(legal_id=self.legal_id, data=data).as_(self._client)


class SetLegalEntityStatusResponse(TochkaObject):
    """SetLegalEntityStatusResponse response model.

    Attributes:
        data: BooleanResponse
        links: LinkModel
        meta: MetaModel
    """

    data: ResultResponse = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class SetLegalEntityStatusData(TochkaObject):
    """SetLegalEntityStatusData response model.

    Attributes:
        status: Статус объекта
    """

    status: SetLegalEntityStatusDataStatus


class RegisterLegalEntityResponse(TochkaObject):
    """RegisterLegalEntityResponse response model.

    Attributes:
        data: OptionalLegalId
        links: LinkModel
        meta: MetaModel
    """

    data: RegisterLegalEntityResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class RegisterLegalEntityResponseData(TochkaObject):
    """RegisterLegalEntityResponseData response model.

    Attributes:
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
    """

    legal_id: str = Field(..., alias="legalId")


class RegisterLegalEntityData(TochkaObject):
    """RegisterLegalEntityData response model.

    Attributes:
        bank_code: БИК банка
        customer_code: Уникальный код клиента
    """

    bank_code: str = Field(..., min_length=9, max_length=9, alias="bankCode")
    customer_code: str = Field(..., max_length=9, alias="customerCode")
