# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с возвратами — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from ..enums.sbp_refunds import (
    GetPaymentsResponseDataPaymentsStatus,
    GetRefundDataResponseDataStatus,
    StartRefundResponseDataStatus,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse

if TYPE_CHECKING:
    from ..methods.sbp_refunds import GetRefundData


class GetPaymentsResponse(TochkaObject):
    """GetPaymentsResponse response model.

    Attributes:
        data: SBPPaymentList
        links: LinkModel
        meta: MetaModel
    """

    data: GetPaymentsResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetPaymentsResponseData(TochkaObject):
    """GetPaymentsResponseData response model.

    Attributes:
        payments: Payments
    """

    payments: list[GetPaymentsResponseDataPayments] = Field(..., alias="Payments")


class GetPaymentsResponseDataPayments(TochkaObject):
    """GetPaymentsResponseDataPayments response model.

    Attributes:
        message: Текстовое представление статуса
        qrc_id: Идентификатор QR-кода в СБП
        ref_transaction_id: Идентификатор операции, инициированной Dynamic QR-кодом
        status: **Описание возможных статусов платежа** - `Confirming` - операция в процессе подтверждения
            ОПКЦ СБП - `Confirmed` - операция подтверждена - `Initiated` - операция отправлена на обработку -
            `Accepting` - операция в обработке ОПКЦ СБП - `Accepted` - операция успешно завершена -
            `InProgress` - операция в обработке РЦ СБП - `Rejected` - операция отклонена - `Error` - ошибка
            выполнения операции - `Timeout` - тайм-аут выполнения операции
    """

    message: str
    qrc_id: str = Field(..., alias="qrcId")
    ref_transaction_id: str = Field(..., alias="refTransactionId")
    status: GetPaymentsResponseDataPaymentsStatus


class StartRefundResponse(TochkaObject):
    """StartRefundResponse response model.

    Attributes:
        data: SBPRefundRequestResponse
        links: LinkModel
        meta: MetaModel
    """

    data: StartRefundResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class StartRefundResponseData(TochkaObject):
    """StartRefundResponseData response model.

    Attributes:
        request_id: ID запроса
        status: Статус по процессу возрата
    """

    request_id: str = Field(..., alias="requestId")
    status: StartRefundResponseDataStatus


class StartRefundData(TochkaObject):
    """StartRefundData response model.

    Attributes:
        account_code: Уникальный и неизменный идентификатор счёта
        amount: Cумма операции в рублях
        bank_code: БИК отправителя
        currency: Валюта операции
        purpose: Назначение платежа
        qrc_id: ID qr-кода, по которому был сделан платеж
        ref_transaction_id: Идентификатор транзакции, по которой осуществляется возврат
        trx_id: Идентификатор операции в НСПК, по которой можно осуществить возврат
    """

    account_code: str = Field(..., max_length=20, alias="accountCode")
    amount: str
    bank_code: str = Field(..., max_length=9, alias="bankCode")
    currency: str = "RUB"
    purpose: str | None = Field(None, max_length=140)
    qrc_id: str = Field(..., alias="qrcId")
    ref_transaction_id: str | None = Field(None, alias="refTransactionId")
    trx_id: str | None = Field(None, alias="trxId")


class GetRefundDataResponse(TochkaObject):
    """GetRefundDataResponse response model.

    Attributes:
        data: SBPRefundStatus
        links: LinkModel
        meta: MetaModel
    """

    data: GetRefundDataResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetRefundDataResponseData(TochkaObject):
    """GetRefundDataResponseData response model.

    Attributes:
        request_id: ID запроса
        status: Статус по процессу возрата
        status_description: Описание статуса (причина ошибки или сообщение об успехе)
    """

    request_id: str = Field(..., alias="requestId")
    status: GetRefundDataResponseDataStatus
    status_description: str | None = Field(None, alias="statusDescription")

    def get_refund_data(self) -> GetRefundData:
        """Build an awaitable :class:`GetRefundData` bound to this object (await to execute)."""
        from ..methods.sbp_refunds import GetRefundData

        return GetRefundData(request_id=self.request_id).as_(self._client)
