# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: работа с B2B QR-кодами — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from ..enums.sbp_b2b_qr_codes import GetB2bQrCodeResponseDataImageMediaType
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse

if TYPE_CHECKING:
    from ..methods.sbp_b2b_qr_codes import GetB2bQrCode


class RegisterB2bQrCodeResponse(TochkaObject):
    """RegisterB2bQrCodeResponse response model.

    Attributes:
        data: RegisteredB2BQrCode
        links: LinkModel
        meta: MetaModel
    """

    data: RegisterB2bQrCodeResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class RegisterB2bQrCodeResponseData(TochkaObject):
    """RegisterB2bQrCodeResponseData response model.

    Attributes:
        payload: Payload зарегистрированного QR-кода в СБП
        qrc_id: Идентификатор QR-кода в СБП
    """

    payload: str
    qrc_id: str = Field(..., alias="qrcId")


class RegisterB2bQrCodeData(TochkaObject):
    """RegisterB2bQrCodeData response model.

    Attributes:
        amount: Сумма в копейках
        payment_purpose: Назначение платежа
        redirect_url: Ссылка для автоматического возврата плательщика из приложения банка в приложение или
            на сайт ТСП
        source_name: Система, создавшая QR-код
        take_tax: Наличие НДС
        total_tax_amount: Сумма НДС в копейках
        ttl: Период использования в минутах
        uip: Уникальный идентификатор платежа, назначаемый получателем
    """

    amount: int = Field(..., ge=1, le=100000000)
    payment_purpose: str = Field(..., max_length=140, alias="paymentPurpose")
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    source_name: str = Field(..., max_length=50, alias="sourceName")
    take_tax: bool = Field(..., alias="takeTax")
    total_tax_amount: int | None = Field(None, alias="totalTaxAmount")
    ttl: int = Field(4320, ge=1, le=129600)
    uip: str | None = Field(None, max_length=35)


class GetB2bQrCodeResponse(TochkaObject):
    """GetB2bQrCodeResponse response model.

    Attributes:
        data: B2BQrCode
        links: LinkModel
        meta: MetaModel
    """

    data: GetB2bQrCodeResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetB2bQrCodeResponseData(TochkaObject):
    """GetB2bQrCodeResponseData response model.

    Attributes:
        account_id: Уникальный и неизменный идентификатор счёта
        amount: Сумма в копейках
        created_at: Время регистрации
        image: QrCodeContent
        legal_id: Идентификатор зарегистрированного юрлица в СБП (12 символов)
        merchant_id: Идентификатор ТСП
        payload: Payload зарегистрированного QR-кода в СБП
        payment_purpose: Назначение платежа
        qrc_id: Идентификатор QR-кода в СБП
        redirect_url: Ссылка для автоматического возврата плательщика из приложения банка в приложение или
            на сайт ТСП
        take_tax: Наличие НДС
        total_tax_amount: Сумма НДС в копейках
        ttl: Период использования в минутах
        uip: Уникальный идентификатор платежа, назначаемый получателем
    """

    account_id: str = Field(..., alias="accountId")
    amount: int | None = None
    created_at: str = Field(..., alias="createdAt")
    image: GetB2bQrCodeResponseDataImage | None = None
    legal_id: str = Field(..., alias="legalId")
    merchant_id: str = Field(..., max_length=12, alias="merchantId")
    payload: str
    payment_purpose: str | None = Field(None, max_length=140, alias="paymentPurpose")
    qrc_id: str = Field(..., alias="qrcId")
    redirect_url: str | None = Field(None, alias="redirectUrl")
    take_tax: bool = Field(..., alias="takeTax")
    total_tax_amount: int | None = Field(None, alias="totalTaxAmount")
    ttl: str | None = None
    uip: str | None = None

    def get_b2b_qr_code(self, width: int | None = None, height: int | None = None) -> GetB2bQrCode:
        """Build an awaitable :class:`GetB2bQrCode` bound to this object (await to execute)."""
        from ..methods.sbp_b2b_qr_codes import GetB2bQrCode

        return GetB2bQrCode(qrc_id=self.qrc_id, width=width, height=height).as_(self._client)


class GetB2bQrCodeResponseDataImage(TochkaObject):
    """GetB2bQrCodeResponseDataImage response model.

    Attributes:
        content: содержимое изображения (для image/png - в кодировке base64)
        height: Высота изображения (>=200, по умолчанию: 300)
        media_type: Тип контента
        width: Ширина изображения (>=200, по умолчанию: 300)
    """

    content: str
    height: int
    media_type: GetB2bQrCodeResponseDataImageMediaType = Field(
        GetB2bQrCodeResponseDataImageMediaType.IMAGE_PNG, alias="mediaType"
    )
    width: int
