# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с выписками — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from datetime import date
from typing import Any

from pydantic import Field

from ..enums.statements import (
    GetStatementResponseDataStatementStatus,
    GetStatementResponseDataStatementTransactionCreditDebitIndicator,
    GetStatementResponseDataStatementTransactionCreditorAccountSchemeName,
    GetStatementResponseDataStatementTransactionCreditorAgentSchemeName,
    GetStatementResponseDataStatementTransactionDebtorAccountSchemeName,
    GetStatementResponseDataStatementTransactionDebtorAgentSchemeName,
    GetStatementResponseDataStatementTransactionStatus,
    GetStatementResponseDataStatementTransactionTransactionTypeCode,
    GetStatementsListResponseDataStatementStatus,
    GetStatementsListResponseDataStatementTransactionCreditDebitIndicator,
    GetStatementsListResponseDataStatementTransactionCreditorAccountSchemeName,
    GetStatementsListResponseDataStatementTransactionCreditorAgentSchemeName,
    GetStatementsListResponseDataStatementTransactionDebtorAccountSchemeName,
    GetStatementsListResponseDataStatementTransactionDebtorAgentSchemeName,
    GetStatementsListResponseDataStatementTransactionStatus,
    GetStatementsListResponseDataStatementTransactionTransactionTypeCode,
    InitStatementResponseDataStatementStatus,
)
from ._base import TochkaObject
from ._shared import SelfResponse, TotalPagesResponse


class GetStatementResponse(TochkaObject):
    """Метод получения выписки по счету

    Attributes:
        data: StatementListModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetStatementResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetStatementResponseData(TochkaObject):
    """GetStatementResponseData response model.

    Attributes:
        statement: Statement
    """

    statement: list[GetStatementResponseDataStatement] = Field(..., alias="Statement")


class GetStatementResponseDataStatement(TochkaObject):
    """GetStatementResponseDataStatement response model.

    Attributes:
        transaction: Transaction
        account_id: Уникальный и неизменный идентификатор счёта
        creation_date_time: Дата и время создания ресурса. Используется стандарт ISO8601
        end_date_balance: Баланс на конец запрашиваемого периода выписки в валюте счета
        end_date_time: Дата окончания выписки. Используется стандарт ISO8601
        start_date_balance: Баланс на начало запрашиваемого периода выписки в валюте счета
        start_date_time: Дата начала выписки. Используется стандарт ISO8601
        statement_id: Идентификатор ресурса выписки
        status: Статус готовности выписки
    """

    transaction: list[GetStatementResponseDataStatementTransaction] | None = Field(None, alias="Transaction")
    account_id: str = Field(..., max_length=40, alias="accountId")
    creation_date_time: str = Field(..., alias="creationDateTime")
    end_date_balance: float | None = Field(None, alias="endDateBalance")
    end_date_time: date = Field(..., alias="endDateTime")
    start_date_balance: float | None = Field(None, alias="startDateBalance")
    start_date_time: date = Field(..., alias="startDateTime")
    statement_id: str | None = Field(None, max_length=40, alias="statementId")
    status: GetStatementResponseDataStatementStatus


class GetStatementResponseDataStatementTransaction(TochkaObject):
    """GetStatementResponseDataStatementTransaction response model.

    Attributes:
        amount: TransactionAmountModel
        creditor_account: Идентификация счета кредитора, в случае дебетовой транзакции
        creditor_agent: Финансовое организация, обслуживающая счет кредитора
        creditor_party: Информация о контрагенте в случае дебетовой транзакции
        debtor_account: Идентификация счета дебитора, в случае кредитной операции
        debtor_agent: Финансовое организация, обслуживающая счет дебитора
        debtor_party: Информация о контрагенте в случае кредитной операции
        tax_fields: Налоговые поля
        credit_debit_indicator: Приход/Уход
        description: Назначение платежа
        document_number: Номер платежного документа
        document_process_date: Дата отражения на балансе
        payment_id: Уникальный идентификатор платежа, по которому произошла транзакция
        status: Статус транзакции
        transaction_id: Уникальный идентификатор транзакции
        transaction_type_code: Код типа транзакции (Вид платежного документа)
    """

    amount: GetStatementResponseDataStatementTransactionAmount = Field(..., alias="Amount")
    creditor_account: GetStatementResponseDataStatementTransactionCreditorAccount | None = Field(
        None, alias="CreditorAccount"
    )
    creditor_agent: GetStatementResponseDataStatementTransactionCreditorAgent | None = Field(
        None, alias="CreditorAgent"
    )
    creditor_party: GetStatementResponseDataStatementTransactionCreditorParty | None = Field(
        None, alias="CreditorParty"
    )
    debtor_account: GetStatementResponseDataStatementTransactionDebtorAccount | None = Field(
        None, alias="DebtorAccount"
    )
    debtor_agent: GetStatementResponseDataStatementTransactionDebtorAgent | None = Field(
        None, alias="DebtorAgent"
    )
    debtor_party: GetStatementResponseDataStatementTransactionDebtorParty | None = Field(
        None, alias="DebtorParty"
    )
    tax_fields: GetStatementResponseDataStatementTransactionTaxFields | None = Field(None, alias="TaxFields")
    credit_debit_indicator: GetStatementResponseDataStatementTransactionCreditDebitIndicator = Field(
        ..., alias="creditDebitIndicator"
    )
    description: str | None = None
    document_number: str | None = Field(None, max_length=12, alias="documentNumber")
    document_process_date: date | None = Field(None, alias="documentProcessDate")
    payment_id: str | None = Field(None, alias="paymentId")
    status: GetStatementResponseDataStatementTransactionStatus
    transaction_id: str | None = Field(None, max_length=210, alias="transactionId")
    transaction_type_code: GetStatementResponseDataStatementTransactionTransactionTypeCode | None = Field(
        None, alias="transactionTypeCode"
    )


class GetStatementResponseDataStatementTransactionAmount(TochkaObject):
    """GetStatementResponseDataStatementTransactionAmount response model.

    Attributes:
        amount: Сумма транзакции запроса в валюте счета
        amount_nat: Сумма транзакции по счету запроса в рублях по курсу ЦБ на дату транзакции
        currency: Валюта ведения счета. Используется стандарт ISO 4217
    """

    amount: float
    amount_nat: float | None = Field(None, alias="amountNat")
    currency: str


class GetStatementResponseDataStatementTransactionCreditorAccount(TochkaObject):
    """GetStatementResponseDataStatementTransactionCreditorAccount response model.

    Attributes:
        identification: Идентификатор счета(может отсутствовать в валютном платеже)
        scheme_name: Название схемы
    """

    identification: str | None = Field(None, max_length=256)
    scheme_name: GetStatementResponseDataStatementTransactionCreditorAccountSchemeName = Field(
        ..., alias="schemeName"
    )


class GetStatementResponseDataStatementTransactionCreditorAgent(TochkaObject):
    """GetStatementResponseDataStatementTransactionCreditorAgent response model.

    Attributes:
        account_identification: Номер кор. счета банка агента
        identification: БИК/SWIFT банка агента
        name: Наименование банка агента
        scheme_name: БИК/SWIFT банка агента
    """

    account_identification: str | None = Field(None, alias="accountIdentification")
    identification: str | None = Field(None, max_length=35)
    name: str | None = Field(None, max_length=160)
    scheme_name: GetStatementResponseDataStatementTransactionCreditorAgentSchemeName | None = Field(
        None, alias="schemeName"
    )


class GetStatementResponseDataStatementTransactionCreditorParty(TochkaObject):
    """GetStatementResponseDataStatementTransactionCreditorParty response model.

    Attributes:
        inn: ИНН контрагента
        kpp: КПП контрагента
        name: Наименование контрагента
    """

    inn: str | None = Field(None, max_length=12)
    kpp: str | None = Field(None, max_length=9)
    name: str | None = None


class GetStatementResponseDataStatementTransactionDebtorAccount(TochkaObject):
    """GetStatementResponseDataStatementTransactionDebtorAccount response model.

    Attributes:
        identification: Идентификатор счета(может отсутствовать в валютном платеже)
        scheme_name: Название схемы
    """

    identification: str | None = Field(None, max_length=256)
    scheme_name: GetStatementResponseDataStatementTransactionDebtorAccountSchemeName = Field(
        ..., alias="schemeName"
    )


class GetStatementResponseDataStatementTransactionDebtorAgent(TochkaObject):
    """GetStatementResponseDataStatementTransactionDebtorAgent response model.

    Attributes:
        account_identification: Номер кор. счета банка агента
        identification: БИК/SWIFT банка агента
        name: Наименование банка агента
        scheme_name: БИК/SWIFT банка агента
    """

    account_identification: str | None = Field(None, alias="accountIdentification")
    identification: str | None = Field(None, max_length=35)
    name: str | None = Field(None, max_length=160)
    scheme_name: GetStatementResponseDataStatementTransactionDebtorAgentSchemeName | None = Field(
        None, alias="schemeName"
    )


class GetStatementResponseDataStatementTransactionDebtorParty(TochkaObject):
    """GetStatementResponseDataStatementTransactionDebtorParty response model.

    Attributes:
        inn: ИНН контрагента
        kpp: КПП контрагента
        name: Наименование контрагента
    """

    inn: str | None = Field(None, max_length=12)
    kpp: str | None = Field(None, max_length=9)
    name: str | None = None


class GetStatementResponseDataStatementTransactionTaxFields(TochkaObject):
    """GetStatementResponseDataStatementTransactionTaxFields response model.

    Attributes:
        base: Основание налогового платежа
        document_date: Дата налогового документа
        document_number: Номер налогового документа
        field107: Налоговой период / код таможенного органа
        kbk: КБК
        oktmo: ОКТМО
        originator_status: Статус плательщика бюджетного платежа
        type_: Вид платежа
    """

    base: str | None = None
    document_date: Any | None = Field(None, alias="documentDate")
    document_number: str | None = Field(None, alias="documentNumber")
    field107: str | None = None
    kbk: str | None = None
    oktmo: str | None = None
    originator_status: str | None = Field(None, alias="originatorStatus")
    type_: str | None = Field(None, alias="type")


class GetStatementsListResponse(TochkaObject):
    """Метод получения выписки по счету

    Attributes:
        data: StatementListModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetStatementsListResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetStatementsListResponseData(TochkaObject):
    """GetStatementsListResponseData response model.

    Attributes:
        statement: Statement
    """

    statement: list[GetStatementsListResponseDataStatement] = Field(..., alias="Statement")


class GetStatementsListResponseDataStatement(TochkaObject):
    """GetStatementsListResponseDataStatement response model.

    Attributes:
        transaction: Transaction
        account_id: Уникальный и неизменный идентификатор счёта
        creation_date_time: Дата и время создания ресурса. Используется стандарт ISO8601
        end_date_balance: Баланс на конец запрашиваемого периода выписки в валюте счета
        end_date_time: Дата окончания выписки. Используется стандарт ISO8601
        start_date_balance: Баланс на начало запрашиваемого периода выписки в валюте счета
        start_date_time: Дата начала выписки. Используется стандарт ISO8601
        statement_id: Идентификатор ресурса выписки
        status: Статус готовности выписки
    """

    transaction: list[GetStatementsListResponseDataStatementTransaction] | None = Field(
        None, alias="Transaction"
    )
    account_id: str = Field(..., max_length=40, alias="accountId")
    creation_date_time: str = Field(..., alias="creationDateTime")
    end_date_balance: float | None = Field(None, alias="endDateBalance")
    end_date_time: date = Field(..., alias="endDateTime")
    start_date_balance: float | None = Field(None, alias="startDateBalance")
    start_date_time: date = Field(..., alias="startDateTime")
    statement_id: str | None = Field(None, max_length=40, alias="statementId")
    status: GetStatementsListResponseDataStatementStatus


class GetStatementsListResponseDataStatementTransaction(TochkaObject):
    """GetStatementsListResponseDataStatementTransaction response model.

    Attributes:
        amount: TransactionAmountModel
        creditor_account: Идентификация счета кредитора, в случае дебетовой транзакции
        creditor_agent: Финансовое организация, обслуживающая счет кредитора
        creditor_party: Информация о контрагенте в случае дебетовой транзакции
        debtor_account: Идентификация счета дебитора, в случае кредитной операции
        debtor_agent: Финансовое организация, обслуживающая счет дебитора
        debtor_party: Информация о контрагенте в случае кредитной операции
        tax_fields: Налоговые поля
        credit_debit_indicator: Приход/Уход
        description: Назначение платежа
        document_number: Номер платежного документа
        document_process_date: Дата отражения на балансе
        payment_id: Уникальный идентификатор платежа, по которому произошла транзакция
        status: Статус транзакции
        transaction_id: Уникальный идентификатор транзакции
        transaction_type_code: Код типа транзакции (Вид платежного документа)
    """

    amount: GetStatementsListResponseDataStatementTransactionAmount = Field(..., alias="Amount")
    creditor_account: GetStatementsListResponseDataStatementTransactionCreditorAccount | None = Field(
        None, alias="CreditorAccount"
    )
    creditor_agent: GetStatementsListResponseDataStatementTransactionCreditorAgent | None = Field(
        None, alias="CreditorAgent"
    )
    creditor_party: GetStatementsListResponseDataStatementTransactionCreditorParty | None = Field(
        None, alias="CreditorParty"
    )
    debtor_account: GetStatementsListResponseDataStatementTransactionDebtorAccount | None = Field(
        None, alias="DebtorAccount"
    )
    debtor_agent: GetStatementsListResponseDataStatementTransactionDebtorAgent | None = Field(
        None, alias="DebtorAgent"
    )
    debtor_party: GetStatementsListResponseDataStatementTransactionDebtorParty | None = Field(
        None, alias="DebtorParty"
    )
    tax_fields: GetStatementsListResponseDataStatementTransactionTaxFields | None = Field(
        None, alias="TaxFields"
    )
    credit_debit_indicator: GetStatementsListResponseDataStatementTransactionCreditDebitIndicator = Field(
        ..., alias="creditDebitIndicator"
    )
    description: str | None = None
    document_number: str | None = Field(None, max_length=12, alias="documentNumber")
    document_process_date: date | None = Field(None, alias="documentProcessDate")
    payment_id: str | None = Field(None, alias="paymentId")
    status: GetStatementsListResponseDataStatementTransactionStatus
    transaction_id: str | None = Field(None, max_length=210, alias="transactionId")
    transaction_type_code: GetStatementsListResponseDataStatementTransactionTransactionTypeCode | None = (
        Field(None, alias="transactionTypeCode")
    )


class GetStatementsListResponseDataStatementTransactionAmount(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionAmount response model.

    Attributes:
        amount: Сумма транзакции запроса в валюте счета
        amount_nat: Сумма транзакции по счету запроса в рублях по курсу ЦБ на дату транзакции
        currency: Валюта ведения счета. Используется стандарт ISO 4217
    """

    amount: float
    amount_nat: float | None = Field(None, alias="amountNat")
    currency: str


class GetStatementsListResponseDataStatementTransactionCreditorAccount(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionCreditorAccount response model.

    Attributes:
        identification: Идентификатор счета(может отсутствовать в валютном платеже)
        scheme_name: Название схемы
    """

    identification: str | None = Field(None, max_length=256)
    scheme_name: GetStatementsListResponseDataStatementTransactionCreditorAccountSchemeName = Field(
        ..., alias="schemeName"
    )


class GetStatementsListResponseDataStatementTransactionCreditorAgent(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionCreditorAgent response model.

    Attributes:
        account_identification: Номер кор. счета банка агента
        identification: БИК/SWIFT банка агента
        name: Наименование банка агента
        scheme_name: БИК/SWIFT банка агента
    """

    account_identification: str | None = Field(None, alias="accountIdentification")
    identification: str | None = Field(None, max_length=35)
    name: str | None = Field(None, max_length=160)
    scheme_name: GetStatementsListResponseDataStatementTransactionCreditorAgentSchemeName | None = Field(
        None, alias="schemeName"
    )


class GetStatementsListResponseDataStatementTransactionCreditorParty(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionCreditorParty response model.

    Attributes:
        inn: ИНН контрагента
        kpp: КПП контрагента
        name: Наименование контрагента
    """

    inn: str | None = Field(None, max_length=12)
    kpp: str | None = Field(None, max_length=9)
    name: str | None = None


class GetStatementsListResponseDataStatementTransactionDebtorAccount(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionDebtorAccount response model.

    Attributes:
        identification: Идентификатор счета(может отсутствовать в валютном платеже)
        scheme_name: Название схемы
    """

    identification: str | None = Field(None, max_length=256)
    scheme_name: GetStatementsListResponseDataStatementTransactionDebtorAccountSchemeName = Field(
        ..., alias="schemeName"
    )


class GetStatementsListResponseDataStatementTransactionDebtorAgent(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionDebtorAgent response model.

    Attributes:
        account_identification: Номер кор. счета банка агента
        identification: БИК/SWIFT банка агента
        name: Наименование банка агента
        scheme_name: БИК/SWIFT банка агента
    """

    account_identification: str | None = Field(None, alias="accountIdentification")
    identification: str | None = Field(None, max_length=35)
    name: str | None = Field(None, max_length=160)
    scheme_name: GetStatementsListResponseDataStatementTransactionDebtorAgentSchemeName | None = Field(
        None, alias="schemeName"
    )


class GetStatementsListResponseDataStatementTransactionDebtorParty(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionDebtorParty response model.

    Attributes:
        inn: ИНН контрагента
        kpp: КПП контрагента
        name: Наименование контрагента
    """

    inn: str | None = Field(None, max_length=12)
    kpp: str | None = Field(None, max_length=9)
    name: str | None = None


class GetStatementsListResponseDataStatementTransactionTaxFields(TochkaObject):
    """GetStatementsListResponseDataStatementTransactionTaxFields response model.

    Attributes:
        base: Основание налогового платежа
        document_date: Дата налогового документа
        document_number: Номер налогового документа
        field107: Налоговой период / код таможенного органа
        kbk: КБК
        oktmo: ОКТМО
        originator_status: Статус плательщика бюджетного платежа
        type_: Вид платежа
    """

    base: str | None = None
    document_date: Any | None = Field(None, alias="documentDate")
    document_number: str | None = Field(None, alias="documentNumber")
    field107: str | None = None
    kbk: str | None = None
    oktmo: str | None = None
    originator_status: str | None = Field(None, alias="originatorStatus")
    type_: str | None = Field(None, alias="type")


class InitStatementResponse(TochkaObject):
    """Метод создания выписки по счету

    Attributes:
        data: StatementInitResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: InitStatementResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class InitStatementResponseData(TochkaObject):
    """InitStatementResponseData response model.

    Attributes:
        statement: InitStatementModel
    """

    statement: InitStatementResponseDataStatement = Field(..., alias="Statement")


class InitStatementResponseDataStatement(TochkaObject):
    """InitStatementResponseDataStatement response model.

    Attributes:
        account_id: Уникальный и неизменный идентификатор счёта
        creation_date_time: Дата и время создания ресурса. Используется стандарт ISO8601
        end_date_time: Дата окончания выписки. Используется стандарт ISO8601
        start_date_time: Дата начала выписки. Используется стандарт ISO8601
        statement_id: Идентификатор ресурса выписки
        status: Статус готовности выписки
    """

    account_id: str = Field(..., max_length=40, alias="accountId")
    creation_date_time: str = Field(..., alias="creationDateTime")
    end_date_time: date = Field(..., alias="endDateTime")
    start_date_time: date = Field(..., alias="startDateTime")
    statement_id: str | None = Field(None, max_length=40, alias="statementId")
    status: InitStatementResponseDataStatementStatus


class InitStatementData(TochkaObject):
    """InitStatementData response model.

    Attributes:
        statement: StatementInitReqModel
    """

    statement: InitStatementDataStatement = Field(..., alias="Statement")


class InitStatementDataStatement(TochkaObject):
    """InitStatementDataStatement response model.

    Attributes:
        account_id: Уникальный и неизменный идентификатор счёта
        end_date_time: Дата окончания выписки. Используется стандарт ISO8601
        start_date_time: Дата начала выписки. Используется стандарт ISO8601
    """

    account_id: str = Field(..., max_length=40, alias="accountId")
    end_date_time: date = Field(..., alias="endDateTime")
    start_date_time: date = Field(..., alias="startDateTime")
