# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с подписками — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from pydantic import Field

from ..enums.subscriptions import (
    CreateSubscriptionDataOptionsPeriod,
    CreateSubscriptionResponseDataOptionsPeriod,
    CreateSubscriptionResponseDataStatus,
    CreateSubscriptionWithReceiptDataItemsMeasure,
    CreateSubscriptionWithReceiptDataItemsPaymentMethod,
    CreateSubscriptionWithReceiptDataItemsPaymentObject,
    CreateSubscriptionWithReceiptDataItemsVatType,
    CreateSubscriptionWithReceiptDataOptionsPeriod,
    CreateSubscriptionWithReceiptDataTaxSystemCode,
    CreateSubscriptionWithReceiptResponseDataItemsMeasure,
    CreateSubscriptionWithReceiptResponseDataItemsPaymentMethod,
    CreateSubscriptionWithReceiptResponseDataItemsPaymentObject,
    CreateSubscriptionWithReceiptResponseDataItemsVatType,
    CreateSubscriptionWithReceiptResponseDataOptionsPeriod,
    CreateSubscriptionWithReceiptResponseDataStatus,
    CreateSubscriptionWithReceiptResponseDataTaxSystemCode,
    GetSubscriptionListResponseDataSubscriptionItemsMeasure,
    GetSubscriptionListResponseDataSubscriptionItemsPaymentMethod,
    GetSubscriptionListResponseDataSubscriptionItemsPaymentObject,
    GetSubscriptionListResponseDataSubscriptionItemsVatType,
    GetSubscriptionListResponseDataSubscriptionOptionsPeriod,
    GetSubscriptionListResponseDataSubscriptionStatus,
    GetSubscriptionListResponseDataSubscriptionTaxSystemCode,
    GetSubscriptionStatusResponseDataStatus,
    SetSubscriptionStatusDataStatus,
)
from ._base import TochkaObject
from ._shared import ResultResponse, SelfResponse, TotalPagesResponse


class GetSubscriptionListResponse(TochkaObject):
    """GetSubscriptionListResponse response model.

    Attributes:
        data: AcquiringSubscriptionListResponseModel
        links: PaginatedLinkModel
        meta: MetaModel
    """

    data: GetSubscriptionListResponseData = Field(..., alias="Data")
    links: GetSubscriptionListResponseLinks = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetSubscriptionListResponseData(TochkaObject):
    """GetSubscriptionListResponseData response model.

    Attributes:
        subscription: Subscription
    """

    subscription: list[GetSubscriptionListResponseDataSubscription] = Field(..., alias="Subscription")


class GetSubscriptionListResponseDataSubscription(TochkaObject):
    """GetSubscriptionListResponseDataSubscription response model.

    Attributes:
        client: Данные покупателя
        cof_token: Информация о карте плательщика
        items: Список товаров в заказе
        options: Опции подписки
        supplier: Данные поставщика
        amount: Сумма платежа
        consumer_id: Идентификатор покупателя
        created_at: Дата и время создания операции. Используется стандарт ISO8601
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        payment_id: Идентификатор платежа в процессинге или СБП
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        purpose: Отсутствует, если при создании платежа назначение не было указано
        recurring: Создание рекуррентной оплаты
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        status: Статус платежа
        tax_system_code: Перечисление для выдачи результатов из openapi.
        transaction_id: Используется для возврата при оплате по СБП
    """

    client: GetSubscriptionListResponseDataSubscriptionClient | None = Field(None, alias="Client")
    cof_token: GetSubscriptionListResponseDataSubscriptionCofToken | None = Field(None, alias="CofToken")
    items: list[GetSubscriptionListResponseDataSubscriptionItems] = Field(..., min_length=1, alias="Items")
    options: GetSubscriptionListResponseDataSubscriptionOptions | None = Field(None, alias="Options")
    supplier: GetSubscriptionListResponseDataSubscriptionSupplier | None = Field(None, alias="Supplier")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    created_at: str = Field(..., alias="createdAt")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    payment_id: str | None = Field(None, alias="paymentId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    purpose: str | None = None
    recurring: bool | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    status: GetSubscriptionListResponseDataSubscriptionStatus
    tax_system_code: GetSubscriptionListResponseDataSubscriptionTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )
    transaction_id: str | None = Field(None, alias="transactionId")


class GetSubscriptionListResponseDataSubscriptionClient(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class GetSubscriptionListResponseDataSubscriptionCofToken(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionCofToken response model.

    Attributes:
        card_type: Тип платёжной системы
        masked_pan: Маскированный номер карты
        token_card_id: Токен карты покупателя
    """

    card_type: str | None = Field(None, alias="cardType")
    masked_pan: str | None = Field(None, alias="maskedPan")
    token_card_id: str | None = Field(None, alias="tokenCardId")


class GetSubscriptionListResponseDataSubscriptionItems(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: GetSubscriptionListResponseDataSubscriptionItemsSupplier | None = Field(None, alias="Supplier")
    amount: float
    measure: GetSubscriptionListResponseDataSubscriptionItemsMeasure = (
        GetSubscriptionListResponseDataSubscriptionItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: GetSubscriptionListResponseDataSubscriptionItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: GetSubscriptionListResponseDataSubscriptionItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float
    vat_type: GetSubscriptionListResponseDataSubscriptionItemsVatType | None = Field(None, alias="vatType")


class GetSubscriptionListResponseDataSubscriptionItemsSupplier(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetSubscriptionListResponseDataSubscriptionOptions(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionOptions response model.

    Attributes:
        days_in_period: Длина периодичности в днях. Работает только с периодом Day
        period: Периодичность списания
        tranche_count: Количество списаний по подписке
    """

    days_in_period: int | None = Field(None, alias="daysInPeriod")
    period: GetSubscriptionListResponseDataSubscriptionOptionsPeriod | None = None
    tranche_count: int | None = Field(None, alias="trancheCount")


class GetSubscriptionListResponseDataSubscriptionSupplier(TochkaObject):
    """GetSubscriptionListResponseDataSubscriptionSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class GetSubscriptionListResponseLinks(TochkaObject):
    """GetSubscriptionListResponseLinks response model.

    Attributes:
        first: First
        last: Last
        next: Next
        prev: Prev
        self: Self
    """

    first: str | None = Field(None, min_length=1, max_length=2083)
    last: str | None = Field(None, min_length=1, max_length=2083)
    next: str | None = Field(None, min_length=1, max_length=2083)
    prev: str | None = Field(None, min_length=1, max_length=2083)
    self: str = Field(..., min_length=1, max_length=2083)


class CreateSubscriptionResponse(TochkaObject):
    """CreateSubscriptionResponse response model.

    Attributes:
        data: AcquiringCreateSubscriptionResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: CreateSubscriptionResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateSubscriptionResponseData(TochkaObject):
    """CreateSubscriptionResponseData response model.

    Attributes:
        options: Опции подписки
        amount: Сумма платежа, которая будет списываться в указанный клиентом период
        consumer_id: Идентификатор покупателя
        operation_id: Идентификатор платежа
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        purpose: Назначение платежа
        recurring: Рекуррентная подписка
        status: Статус платежа
    """

    options: CreateSubscriptionResponseDataOptions | None = Field(None, alias="Options")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    operation_id: str = Field(..., alias="operationId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    purpose: str = Field(..., min_length=1, max_length=140)
    recurring: bool | None = None
    status: CreateSubscriptionResponseDataStatus = CreateSubscriptionResponseDataStatus.CREATED


class CreateSubscriptionResponseDataOptions(TochkaObject):
    """CreateSubscriptionResponseDataOptions response model.

    Attributes:
        days_in_period: Длина периодичности в днях. Работает только с периодом Day
        period: Периодичность списания
        tranche_count: Количество списаний по подписке
    """

    days_in_period: int | None = Field(None, alias="daysInPeriod")
    period: CreateSubscriptionResponseDataOptionsPeriod | None = None
    tranche_count: int | None = Field(None, alias="trancheCount")


class CreateSubscriptionData(TochkaObject):
    """CreateSubscriptionData response model.

    Attributes:
        options: Опции подписки
        amount: Сумма платежа, которая будет списываться в указанный клиентом период
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        payment_link_id: Уникальный номер заказа
        purpose: Назначение платежа
        recurring: Создание рекуррентной оплаты
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        save_card: Предложить покупателю сохранить карту
    """

    options: CreateSubscriptionDataOptions | None = Field(None, alias="Options")
    amount: float = Field(..., gt=0)
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    purpose: str = Field(..., min_length=1, max_length=140)
    recurring: bool | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    save_card: bool | None = Field(None, alias="saveCard")


class CreateSubscriptionDataOptions(TochkaObject):
    """CreateSubscriptionDataOptions response model.

    Attributes:
        days_in_period: Длина периодичности в днях. Работает только с периодом Day
        period: Периодичность списания
        tranche_count: Количество списаний по подписке
    """

    days_in_period: int | None = Field(None, gt=0, alias="daysInPeriod")
    period: CreateSubscriptionDataOptionsPeriod = CreateSubscriptionDataOptionsPeriod.MONTH
    tranche_count: int = Field(12, gt=0, alias="trancheCount")


class ChargeSubscriptionResponse(TochkaObject):
    """ChargeSubscriptionResponse response model.

    Attributes:
        data: BooleanResponse
    """

    data: ResultResponse = Field(..., alias="Data")


class ChargeSubscriptionData(TochkaObject):
    """ChargeSubscriptionData response model.

    Attributes:
        amount: Сумма платежа
    """

    amount: float


class GetSubscriptionStatusResponse(TochkaObject):
    """GetSubscriptionStatusResponse response model.

    Attributes:
        data: AcquiringGetSubscriptionStatusResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: GetSubscriptionStatusResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class GetSubscriptionStatusResponseData(TochkaObject):
    """GetSubscriptionStatusResponseData response model.

    Attributes:
        status: AcquiringSubscriptionStatus
    """

    status: GetSubscriptionStatusResponseDataStatus


class SetSubscriptionStatusResponse(TochkaObject):
    """SetSubscriptionStatusResponse response model.

    Attributes:
        data: BooleanResponse
        links: LinkModel
        meta: MetaModel
    """

    data: ResultResponse = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class SetSubscriptionStatusData(TochkaObject):
    """SetSubscriptionStatusData response model.

    Attributes:
        status: Статус подписки
    """

    status: SetSubscriptionStatusDataStatus


class CreateSubscriptionWithReceiptResponse(TochkaObject):
    """CreateSubscriptionWithReceiptResponse response model.

    Attributes:
        data: AcquiringCreateSubscriptionWithReceiptResponseModel
        links: LinkModel
        meta: MetaModel
    """

    data: CreateSubscriptionWithReceiptResponseData = Field(..., alias="Data")
    links: SelfResponse = Field(..., alias="Links")
    meta: TotalPagesResponse = Field(..., alias="Meta")


class CreateSubscriptionWithReceiptResponseData(TochkaObject):
    """CreateSubscriptionWithReceiptResponseData response model.

    Attributes:
        client: Данные покупателя
        items: Список товаров в заказе
        options: Опции подписки
        supplier: Данные поставщика
        amount: Сумма платежа, которая будет списываться в указанный клиентом период
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        operation_id: Идентификатор платежа
        payment_link: Ссылка на оплату
        payment_link_id: Уникальный номер заказа
        purpose: Назначение платежа
        recurring: Рекуррентная подписка
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        status: Статус платежа
        tax_system_code: Система налогообложения
    """

    client: CreateSubscriptionWithReceiptResponseDataClient = Field(..., alias="Client")
    items: list[CreateSubscriptionWithReceiptResponseDataItems] = Field(..., min_length=1, alias="Items")
    options: CreateSubscriptionWithReceiptResponseDataOptions | None = Field(None, alias="Options")
    supplier: CreateSubscriptionWithReceiptResponseDataSupplier | None = Field(None, alias="Supplier")
    amount: float
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    operation_id: str = Field(..., alias="operationId")
    payment_link: str = Field(..., alias="paymentLink")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    purpose: str = Field(..., min_length=1, max_length=140)
    recurring: bool | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    status: CreateSubscriptionWithReceiptResponseDataStatus = (
        CreateSubscriptionWithReceiptResponseDataStatus.CREATED
    )
    tax_system_code: CreateSubscriptionWithReceiptResponseDataTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )


class CreateSubscriptionWithReceiptResponseDataClient(TochkaObject):
    """CreateSubscriptionWithReceiptResponseDataClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class CreateSubscriptionWithReceiptResponseDataItems(TochkaObject):
    """CreateSubscriptionWithReceiptResponseDataItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: CreateSubscriptionWithReceiptResponseDataItemsSupplier | None = Field(None, alias="Supplier")
    amount: float
    measure: CreateSubscriptionWithReceiptResponseDataItemsMeasure = (
        CreateSubscriptionWithReceiptResponseDataItemsMeasure.SHT
    )
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: CreateSubscriptionWithReceiptResponseDataItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: CreateSubscriptionWithReceiptResponseDataItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float
    vat_type: CreateSubscriptionWithReceiptResponseDataItemsVatType | None = Field(None, alias="vatType")


class CreateSubscriptionWithReceiptResponseDataItemsSupplier(TochkaObject):
    """CreateSubscriptionWithReceiptResponseDataItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreateSubscriptionWithReceiptResponseDataOptions(TochkaObject):
    """CreateSubscriptionWithReceiptResponseDataOptions response model.

    Attributes:
        days_in_period: Длина периодичности в днях. Работает только с периодом Day
        period: Периодичность списания
        tranche_count: Количество списаний по подписке
    """

    days_in_period: int | None = Field(None, alias="daysInPeriod")
    period: CreateSubscriptionWithReceiptResponseDataOptionsPeriod | None = None
    tranche_count: int | None = Field(None, alias="trancheCount")


class CreateSubscriptionWithReceiptResponseDataSupplier(TochkaObject):
    """CreateSubscriptionWithReceiptResponseDataSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreateSubscriptionWithReceiptData(TochkaObject):
    """CreateSubscriptionWithReceiptData response model.

    Attributes:
        client: Данные покупателя
        items: Список товаров в заказе
        options: Опции подписки
        supplier: Данные поставщика
        amount: Сумма платежа, которая будет списываться в указанный клиентом период
        consumer_id: Идентификатор покупателя
        customer_code: Уникальный код клиента
        fail_redirect_url: URL адрес, куда будет переправлен клиент в случае неуспешной оплаты
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        payment_link_id: Уникальный номер заказа
        purpose: Назначение платежа
        recurring: Создание рекуррентной оплаты
        redirect_url: URL адрес, куда будет переправлен клиент после оплаты услуги
        save_card: Предложить покупателю сохранить карту
        tax_system_code: Система налогообложения
    """

    client: CreateSubscriptionWithReceiptDataClient = Field(..., alias="Client")
    items: list[CreateSubscriptionWithReceiptDataItems] = Field(..., min_length=1, alias="Items")
    options: CreateSubscriptionWithReceiptDataOptions | None = Field(None, alias="Options")
    supplier: CreateSubscriptionWithReceiptDataSupplier | None = Field(None, alias="Supplier")
    amount: float = Field(..., gt=0)
    consumer_id: str | None = Field(None, alias="consumerId")
    customer_code: str = Field(..., min_length=9, max_length=9, alias="customerCode")
    fail_redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="failRedirectUrl")
    merchant_id: str | None = Field(None, alias="merchantId")
    payment_link_id: str | None = Field(None, min_length=1, max_length=45, alias="paymentLinkId")
    purpose: str = Field(..., min_length=1, max_length=140)
    recurring: bool | None = None
    redirect_url: str | None = Field(None, min_length=1, max_length=2083, alias="redirectUrl")
    save_card: bool | None = Field(None, alias="saveCard")
    tax_system_code: CreateSubscriptionWithReceiptDataTaxSystemCode | None = Field(
        None, alias="taxSystemCode"
    )


class CreateSubscriptionWithReceiptDataClient(TochkaObject):
    """CreateSubscriptionWithReceiptDataClient response model.

    Attributes:
        email: Email покупателя, на который будет отправлен чек
        name: Для юрлица — название организации, для ИП и физического лица — ФИО
        phone: Телефон пользователя для отправки чека.
    """

    email: str
    name: str | None = None
    phone: str | None = None


class CreateSubscriptionWithReceiptDataItems(TochkaObject):
    """CreateSubscriptionWithReceiptDataItems response model.

    Attributes:
        supplier: Данные поставщика
        amount: Цена за единицу товара
        measure: Единица измерения. По умолчанию - штуки
        name: Название товара
        payment_method: Тип оплаты
        payment_object: Признак предмета расчёта
        quantity: Количество товара
        vat_type: Ставка НДС
    """

    supplier: CreateSubscriptionWithReceiptDataItemsSupplier | None = Field(None, alias="Supplier")
    amount: float = Field(..., gt=0)
    measure: CreateSubscriptionWithReceiptDataItemsMeasure = CreateSubscriptionWithReceiptDataItemsMeasure.SHT
    name: str = Field(..., min_length=1, max_length=256)
    payment_method: CreateSubscriptionWithReceiptDataItemsPaymentMethod | None = Field(
        None, alias="paymentMethod"
    )
    payment_object: CreateSubscriptionWithReceiptDataItemsPaymentObject | None = Field(
        None, alias="paymentObject"
    )
    quantity: float = Field(..., gt=0)
    vat_type: CreateSubscriptionWithReceiptDataItemsVatType | None = Field(None, alias="vatType")


class CreateSubscriptionWithReceiptDataItemsSupplier(TochkaObject):
    """CreateSubscriptionWithReceiptDataItemsSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")


class CreateSubscriptionWithReceiptDataOptions(TochkaObject):
    """CreateSubscriptionWithReceiptDataOptions response model.

    Attributes:
        days_in_period: Длина периодичности в днях. Работает только с периодом Day
        period: Периодичность списания
        tranche_count: Количество списаний по подписке
    """

    days_in_period: int | None = Field(None, gt=0, alias="daysInPeriod")
    period: CreateSubscriptionWithReceiptDataOptionsPeriod = (
        CreateSubscriptionWithReceiptDataOptionsPeriod.MONTH
    )
    tranche_count: int = Field(12, gt=0, alias="trancheCount")


class CreateSubscriptionWithReceiptDataSupplier(TochkaObject):
    """CreateSubscriptionWithReceiptDataSupplier response model.

    Attributes:
        name: Наименование поставщика
        phone: Номер телефона поставщика
        tax_code: ИНН поставщика
    """

    name: str
    phone: str = Field(..., min_length=11, max_length=15, pattern="^\\+?\\d+$")
    tax_code: str = Field(..., min_length=10, max_length=12, pattern="^\\d+$", alias="taxCode")
