# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Виртуальные счета — domain models (auto-generated from the Tochka OpenAPI spec).

See: https://developers.tochka.com/docs"""

from __future__ import annotations

from datetime import date

from pydantic import Field

from ..enums.virtual_accounts import (
    CreateVirtualAccountV2ParamsVirtualAccountType,
    ListVirtualAccountV2ParamsFiltersBeneficiaryLegalType,
    ListVirtualAccountV2ParamsFiltersType,
    ListVirtualTransactionV2ParamsFiltersOperationType,
)
from ._base import TochkaObject


class CreateVirtualAccountV2Params(TochkaObject):
    """CreateVirtualAccountV2Params response model.

    Attributes:
        beneficiary_id: Идентификатор бенефициара
        inn: 10 или 12 цифр, по реквизитам из банка; Необязательный для счетов, начинающихся на 40817,
            423, 40820, 40803, 40813, 426
        nominal_account_bic: БИК номинального счёта
        nominal_account_code: Номер номинального счёта
        virtual_account_type: Типы виртуальных счетов.
    """

    beneficiary_id: str | None = None
    inn: str | None = Field(None, min_length=10, max_length=12)
    nominal_account_bic: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    nominal_account_code: str | None = Field(None, min_length=20, max_length=20, pattern="^\\d{20}$")
    virtual_account_type: CreateVirtualAccountV2ParamsVirtualAccountType = (
        CreateVirtualAccountV2ParamsVirtualAccountType.STANDARD
    )


class GetVirtualAccountV2Params(TochkaObject):
    """GetVirtualAccountV2Params response model.

    Attributes:
        virtual_account: Уникальный идентификатор виртуального счёта
    """

    virtual_account: str


class GetVirtualAccountsTransferV2Params(TochkaObject):
    """GetVirtualAccountsTransferV2Params response model.

    Attributes:
        transfer_id: Идентификатор перевода между виртуальными счетами
    """

    transfer_id: str


class ListVirtualAccountV2Params(TochkaObject):
    """ListVirtualAccountV2Params response model.

    Attributes:
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    filters: ListVirtualAccountV2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListVirtualAccountV2ParamsFilters(TochkaObject):
    """ListVirtualAccountV2ParamsFilters response model.

    Attributes:
        beneficiary: Фильтры по бенефициару
        nominal_bic: БИК номинального счёта
        nominal_code: Номер номинального счёта
        type_: Типы виртуальных счетов.
    """

    beneficiary: ListVirtualAccountV2ParamsFiltersBeneficiary | None = None
    nominal_bic: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    nominal_code: str | None = None
    type_: ListVirtualAccountV2ParamsFiltersType | None = Field(None, alias="type")


class ListVirtualAccountV2ParamsFiltersBeneficiary(TochkaObject):
    """ListVirtualAccountV2ParamsFiltersBeneficiary response model.

    Attributes:
        id: Уникальный идентификатор бенефициара
        inn: 10 или 12 цифр, по реквизитам из банка; Необязательный для счетов, начинающихся на 40817,
            423, 40820, 40803, 40813, 426
        is_active: Статус бенефициара (активен/неактивен)
        legal_type: Тип бенефициара
    """

    id: str | None = None
    inn: str | None = Field(None, min_length=10, max_length=12)
    is_active: bool | None = None
    legal_type: ListVirtualAccountV2ParamsFiltersBeneficiaryLegalType | None = None


class ListVirtualTransactionV2Params(TochkaObject):
    """ListVirtualTransactionV2Params response model.

    Attributes:
        filters: Фильтры
        page: Страница
        per_page: Количество элементов на странице
    """

    filters: ListVirtualTransactionV2ParamsFilters | None = None
    page: int = Field(1, ge=1)
    per_page: int = Field(100, ge=1, le=1000)


class ListVirtualTransactionV2ParamsFilters(TochkaObject):
    """ListVirtualTransactionV2ParamsFilters response model.

    Attributes:
        created_date_from: Дата создания от
        created_date_to: Дата создания до
        deal_id: Уникальный идентификатор сделки
        include_block_operations: Включать операции блокировки/разблокировки средств
        incoming: Тип платежа
        operation_type: Тип операции
        payment_id: Идентификатор платежа
        virtual_account: Виртуальный счёт бенефициара
    """

    created_date_from: date | None = None
    created_date_to: date | None = None
    deal_id: str | None = None
    include_block_operations: bool = False
    incoming: bool | None = None
    operation_type: ListVirtualTransactionV2ParamsFiltersOperationType | None = None
    payment_id: str | None = None
    virtual_account: str | None = None


class RefundVirtualAccountV2Params(TochkaObject):
    """RefundVirtualAccountV2Params response model.

    Attributes:
        ext_key: Внешний уникальный идентификатор операции для идемпотентности
        identifier: Уникальный идентификатор получателя
        purpose: Назначение платежа
        recipient: Реквизиты получателя
        virtual_account: Виртуальный счёт бенефициара, типа standard
    """

    ext_key: str | None = Field(None, min_length=1, max_length=50)
    identifier: str | None = Field(None, min_length=1, max_length=60)
    purpose: str | None = Field(None, min_length=5, max_length=210, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")
    recipient: RefundVirtualAccountV2ParamsRecipient
    virtual_account: str


class RefundVirtualAccountV2ParamsRecipient(TochkaObject):
    """RefundVirtualAccountV2ParamsRecipient response model.

    Attributes:
        account: Счёт получателя
        amount: Сумма перевода
        bank_code: БИК получателя
        document_number: Номер платёжного документа
        inn: 10 или 12 цифр, по реквизитам из банка; Необязательный для счетов, начинающихся на 40817,
            423, 40820, 40803, 40813, 426
        kpp: КПП получателя (по реквизитам из банка)
        name: Наименование получателя (по реквизитам из банка)
        purpose: Назначение платежа
    """

    account: str = Field(..., min_length=20, max_length=20, pattern="^\\d{20}$")
    amount: float
    bank_code: str = Field(..., min_length=9, max_length=9, pattern="^\\d{9}$")
    document_number: str | None = Field(None, min_length=1, max_length=6)
    inn: str | None = Field(None, min_length=10, max_length=12)
    kpp: str | None = Field(None, min_length=9, max_length=9, pattern="^\\d{9}$")
    name: str = Field(..., min_length=1, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")
    purpose: str | None = Field(None, min_length=5, max_length=210, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")


class TransferBetweenVirtualAccountsV2Params(TochkaObject):
    """TransferBetweenVirtualAccountsV2Params response model.

    Attributes:
        amount: Сумма перевода
        from_virtual_account: Виртуальный счёт с которого списать
        to_virtual_account: Виртуальный счёт на который перевести
    """

    amount: float
    from_virtual_account: str
    to_virtual_account: str


class TransferBetweenVirtualAccountsV2V2Params(TochkaObject):
    """TransferBetweenVirtualAccountsV2V2Params response model.

    Attributes:
        amount: Сумма перевода
        ext_key: Ключ идемпотентности
        from_virtual_account: Виртуальный счёт с которого списать
        purpose: Назначение платежа
        to_virtual_account: Виртуальный счёт на который перевести
    """

    amount: float
    ext_key: str | None = None
    from_virtual_account: str
    purpose: str | None = Field(None, min_length=5, max_length=210, pattern="^[ -~№А-яёЁ\\t\\n\\r]*$")
    to_virtual_account: str
