# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Завершение аутентификации — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..enums.acquiring_authentication import CompletePaymentApiVersion
from ..models.acquiring_authentication import CompletePaymentResponse
from ._base import BaseMethod


class CompletePayment(BaseMethod[CompletePaymentResponse]):
    """После успешного прохождения дополнительной аутентификации, ТСП необходимо отправить запрос с
    параметрами соответствующими типу дополнительной аутентификации для завершения проверки via ``POST
    /{api_version}/sites/{site_uid}/payments/{payment_uid}/complete``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
        api_version: Версия API
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/payments/{payment_uid}/complete"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")
    api_version: CompletePaymentApiVersion = Field(..., alias="apiVersion")
    data: Any = Field(..., alias="Data")
