# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Кассовые ссылки СБП — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..enums.acquiring_cashbox_links import (
    ActivateCashRegisterQrCodeApiVersion,
    ActivateCashRegisterQrCodeQrcIdType,
    CreateCashRegisterQrCodeApiVersion,
    DeactivateCashRegisterQrCodeApiVersion,
    DeactivateCashRegisterQrCodeQrcIdType,
    GetCashRegisterQrCodeStatusApiVersion,
    GetCashRegisterQrCodeStatusQrcIdType,
    GetPaymentByCashRegisterQrcActivationUidApiVersion,
    GetPaymentByCashRegisterQrcActivationUidQrcIdType,
)
from ..models.acquiring_cashbox_links import (
    ActivateCashRegisterQrCodeData,
    ActivateCashRegisterQrCodeResponse,
    CreateCashRegisterQrCodeData,
    CreateCashRegisterQrCodeResponse,
    DeactivateCashRegisterQrCodeResponse,
    GetCashRegisterQrCodeStatusResponse,
    GetPaymentByCashRegisterQrcActivationUidResponse,
)
from ._base import BaseMethod


class CreateCashRegisterQrCode(BaseMethod[CreateCashRegisterQrCodeResponse]):
    """Создать Кассовую ссылку СБП via ``POST /{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        api_version: Версия API
        data: Кассовая ссылка СБП
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    api_version: CreateCashRegisterQrCodeApiVersion = Field(..., alias="apiVersion")
    data: CreateCashRegisterQrCodeData = Field(..., alias="Data")


class ActivateCashRegisterQrCode(BaseMethod[ActivateCashRegisterQrCodeResponse]):
    """Активировать Кассовую ссылку СБП via ``POST
    /{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Кассовой ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
        data: Параметры активации Кассовой ссылки СБП
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = (
        "/{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations"
    )
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: ActivateCashRegisterQrCodeApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: ActivateCashRegisterQrCodeQrcIdType = Field(..., alias="qrcIdType")
    data: ActivateCashRegisterQrCodeData = Field(..., alias="Data")


class DeactivateCashRegisterQrCode(BaseMethod[DeactivateCashRegisterQrCodeResponse]):
    """Деактивировать Кассовую ссылку СБП via ``DELETE
    /{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations/current``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Кассовой ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
    """

    __http_method__: ClassVar[str] = "DELETE"
    __endpoint__: ClassVar[str] = (
        "/{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations/current"
    )
    __product__: ClassVar[str] = "pay-gateway"
    __idempotent_mutation__: ClassVar[bool] = True

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: DeactivateCashRegisterQrCodeApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: DeactivateCashRegisterQrCodeQrcIdType = Field(..., alias="qrcIdType")


class GetPaymentByCashRegisterQrcActivationUid(BaseMethod[GetPaymentByCashRegisterQrcActivationUidResponse]):
    """Получить платёж по активации Кассовой ссылки СБП via ``GET
    /{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations/{activation_uid}/payment``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Кассовой ссылки СБП
        activation_uid: Уникальный идентификатор активации Кассовой ссылки СБП в информационной системе
            ТСП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = (
        "/{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/activations/{activation_uid}/payment"
    )
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    activation_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="activationUid")
    api_version: GetPaymentByCashRegisterQrcActivationUidApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: GetPaymentByCashRegisterQrcActivationUidQrcIdType = Field(..., alias="qrcIdType")


class GetCashRegisterQrCodeStatus(BaseMethod[GetCashRegisterQrCodeStatusResponse]):
    """Получить статус Кассовой ссылки СБП via ``GET
    /{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/status``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Кассовой ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc/cash-register-qrc/{qrc_id}/status"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: GetCashRegisterQrCodeStatusApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: GetCashRegisterQrCodeStatusQrcIdType = Field(..., alias="qrcIdType")
