# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Функциональные ссылки СБП — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..enums.acquiring_functional_links import (
    CreateQrCodeApiVersion,
    GetPaymentsByQrcIdApiVersion,
    GetPaymentsByQrcIdQrcIdType,
    GetQrCodeApiVersion,
    GetQrCodeMediaType,
    GetQrCodeQrcIdType,
    GetTokenizationResultApiVersion,
    GetTokenizationResultQrcIdType,
)
from ..models.acquiring_functional_links import (
    CreateQrCodeResponse,
    GetPaymentsByQrcIdResponse,
    GetQrCodeResponse,
    GetTokenizationResultResponse,
)
from ..pagination import PageMethod
from ._base import BaseMethod


class CreateQrCode(BaseMethod[CreateQrCodeResponse]):
    """Создать Функциональную ссылку СБП via ``POST /{api_version}/sites/{site_uid}/sbp/qrc``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        api_version: Версия API
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    api_version: CreateQrCodeApiVersion = Field(..., alias="apiVersion")
    data: Any = Field(..., alias="Data")


class GetQrCode(BaseMethod[GetQrCodeResponse]):
    """Получить содержимое ранее зарегистрированной Функциональной ссылки СБП via ``GET
    /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
        media_type: Формат изображения QR-кода
        width: Ширина изображения QR-кода
        height: Высота изображения QR-кода
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: GetQrCodeApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: GetQrCodeQrcIdType = Field(..., alias="qrcIdType")
    media_type: GetQrCodeMediaType | None = Field(None, alias="mediaType")
    width: int = Field(300, ge=200, le=1000)
    height: int = Field(300, ge=200, le=1000)


class GetPaymentsByQrcId(PageMethod[GetPaymentsByQrcIdResponse]):
    """Получить платежи по ранее зарегистрированной Функциональной ссылке СБП via ``GET
    /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/payments``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/payments"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: GetPaymentsByQrcIdApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: GetPaymentsByQrcIdQrcIdType = Field(..., alias="qrcIdType")


class GetTokenizationResult(BaseMethod[GetTokenizationResultResponse]):
    """Получить результат выполнения привязки счёта по ранее зарегистрированной Функциональной ссылке СБП via
    ``GET /{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/tokenization/result``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        qrc_id: Идентификатор зарегистрированной Функциональной ссылки СБП
        api_version: Версия API
        qrc_id_type: Тип идентификатора
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/sbp/qrc/{qrc_id}/tokenization/result"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    qrc_id: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="qrcId")
    api_version: GetTokenizationResultApiVersion = Field(..., alias="apiVersion")
    qrc_id_type: GetTokenizationResultQrcIdType = Field(..., alias="qrcIdType")
