# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платёж через форму мерчанта — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..enums.acquiring_merchant_form import CreatePaymentApiVersion, GetPaymentApiVersion
from ..models.acquiring_merchant_form import CreatePaymentData, CreatePaymentResponse, GetPaymentResponse
from ._base import BaseMethod


class CreatePayment(BaseMethod[CreatePaymentResponse]):
    """Создать платёжную транзакцию via ``POST /{api_version}/sites/{site_uid}/payments``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        api_version: Версия API
        data: CreatePaymentRequestDTO
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/payments"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    api_version: CreatePaymentApiVersion = Field(..., alias="apiVersion")
    data: CreatePaymentData = Field(..., alias="Data")


class GetPayment(BaseMethod[GetPaymentResponse]):
    """Получить информацию о платёжной транзакции via ``GET
    /{api_version}/sites/{site_uid}/payments/{payment_uid}``.

    See: https://developers.tochka.com/docs

    Args:
        site_uid: ID Сайта
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
        api_version: Версия API
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/{api_version}/sites/{site_uid}/payments/{payment_uid}"
    __product__: ClassVar[str] = "pay-gateway"

    site_uid: str = Field(..., pattern="^[0-9a-zA-Z-_]{1,64}$", alias="siteUid")
    payment_uid: str = Field(..., pattern="^[0-9a-zA-Z-]{1,64}$", alias="paymentUid")
    api_version: GetPaymentApiVersion = Field(..., alias="apiVersion")
