# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Вебхуки — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..enums.acquiring_webhooks import (
    CaptureNotificationEvent,
    CaptureNotificationPayloadType,
    CaptureNotificationVersion,
    PaymentNotificationEvent,
    PaymentNotificationPayloadType,
    PaymentNotificationVersion,
    RefundNotificationEvent,
    RefundNotificationPayloadType,
    RefundNotificationVersion,
    TokenizationDecisionNotificationEvent,
    TokenizationDecisionNotificationPayloadType,
    TokenizationDecisionNotificationVersion,
)
from ..models.acquiring_webhooks import (
    CaptureNotificationPayload,
    PaymentNotificationPayload,
    RefundNotificationPayload,
)
from ._base import BaseMethod


class CaptureNotification(BaseMethod[None]):
    """Уведомление об изменении статуса подтверждения via ``POST /merchant-notifications-url/capture``.

    See: https://developers.tochka.com/docs

    Args:
        created_at: Дата создания уведомления
        event: Тип уведомления
        invoice_uid: ID счёта
        payload: CaptureResponseDTO
        payload_type: Тип тела уведомления
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
        site_uid: ID Сайта
        version: Версия формата уведомления
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/merchant-notifications-url/capture"
    __product__: ClassVar[str] = "pay-gateway"

    created_at: str = Field(..., alias="createdAt")
    event: CaptureNotificationEvent
    invoice_uid: str | None = Field(None, alias="invoiceUid")
    payload: CaptureNotificationPayload
    payload_type: CaptureNotificationPayloadType = Field(..., alias="payloadType")
    payment_uid: str = Field(..., alias="paymentUid")
    site_uid: str = Field(..., alias="siteUid")
    version: CaptureNotificationVersion


class PaymentNotification(BaseMethod[None]):
    """Уведомление об изменении статуса платежа via ``POST /merchant-notifications-url/payment``.

    See: https://developers.tochka.com/docs

    Args:
        created_at: Дата создания уведомления
        event: Тип уведомления
        invoice_uid: ID счёта
        payload: PaymentResponseDTO
        payload_type: Тип тела уведомления
        site_uid: ID сайта
        version: Версия формата уведомления
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/merchant-notifications-url/payment"
    __product__: ClassVar[str] = "pay-gateway"

    created_at: str = Field(..., alias="createdAt")
    event: PaymentNotificationEvent
    invoice_uid: str | None = Field(None, alias="invoiceUid")
    payload: PaymentNotificationPayload
    payload_type: PaymentNotificationPayloadType = Field(..., alias="payloadType")
    site_uid: str = Field(..., alias="siteUid")
    version: PaymentNotificationVersion


class RefundNotification(BaseMethod[None]):
    """Уведомление об изменении статуса возврата via ``POST /merchant-notifications-url/refund``.

    See: https://developers.tochka.com/docs

    Args:
        created_at: Дата создания уведомления
        event: Тип уведомления
        invoice_uid: ID счёта
        payload: RefundResponseDTO
        payload_type: Тип тела уведомления
        payment_uid: Уникальный идентификатор платежа в информационной системе ТСП
        site_uid: ID Сайта
        version: Версия формата уведомления
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/merchant-notifications-url/refund"
    __product__: ClassVar[str] = "pay-gateway"

    created_at: str = Field(..., alias="createdAt")
    event: RefundNotificationEvent
    invoice_uid: str | None = Field(None, alias="invoiceUid")
    payload: RefundNotificationPayload
    payload_type: RefundNotificationPayloadType = Field(..., alias="payloadType")
    payment_uid: str = Field(..., alias="paymentUid")
    site_uid: str = Field(..., alias="siteUid")
    version: RefundNotificationVersion


class TokenizationDecisionNotification(BaseMethod[None]):
    """Уведомление о результате выполнения привязки счёта via ``POST
    /merchant-notifications-url/tokenization-decision``.

    See: https://developers.tochka.com/docs

    Args:
        created_at: Дата создания уведомления
        event: Тип уведомления
        payload_type: Тип тела уведомления
        site_uid: ID Сайта
        version: Версия формата уведомления
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/merchant-notifications-url/tokenization-decision"
    __product__: ClassVar[str] = "pay-gateway"

    created_at: str = Field(..., alias="createdAt")
    event: TokenizationDecisionNotificationEvent
    payload: Any
    payload_type: TokenizationDecisionNotificationPayloadType = Field(..., alias="payloadType")
    site_uid: str = Field(..., alias="siteUid")
    version: TokenizationDecisionNotificationVersion
