# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с балансами счетов — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.balances import (
    GetAuthorizedCardTransactionsResponse,
    GetBalanceInfoResponse,
    GetBalancesListResponse,
)
from ._base import BaseMethod


class GetAuthorizedCardTransactions(BaseMethod[GetAuthorizedCardTransactionsResponse]):
    """Метод для получения авторизованных карточных транзакций конкретного счёта via ``GET
    /open-banking/v1.0/accounts/{account_id}/authorized-card-transactions``.

    See: https://developers.tochka.com/docs

    Args:
        account_id: Идентификатор счета
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/open-banking/v1.0/accounts/{account_id}/authorized-card-transactions"
    __product__: ClassVar[str] = "tochka-api"

    account_id: str = Field(..., alias="accountId")


class GetBalanceInfo(BaseMethod[GetBalanceInfoResponse]):
    """Метод для получения информации о балансе конкретного счёта via ``GET
    /open-banking/v1.0/accounts/{account_id}/balances``.

    See: https://developers.tochka.com/docs

    Args:
        account_id: Идентификатор счета
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/open-banking/v1.0/accounts/{account_id}/balances"
    __product__: ClassVar[str] = "tochka-api"

    account_id: str = Field(..., alias="accountId")


class GetBalancesList(BaseMethod[GetBalancesListResponse]):
    """Метод для получения баланса по нескольким счетам via ``GET /open-banking/v1.0/balances``.

    See: https://developers.tochka.com/docs
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/open-banking/v1.0/balances"
    __product__: ClassVar[str] = "tochka-api"
