# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с закрывающими документами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.closing_documents import (
    CreateClosingDocumentData,
    CreateClosingDocumentResponse,
    DeleteClosingDocumentsResponse,
    SendClosingDocumentsToEmailData,
    SendClosingDocumentsToEmailResponse,
)
from ._base import BaseMethod


class CreateClosingDocument(BaseMethod[CreateClosingDocumentResponse]):
    """Метод для создания закрывающего документа via ``POST /invoice/v1.0/closing-documents``.

    See: https://developers.tochka.com/docs

    Args:
        data: ClosingDocumentCreateRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/invoice/v1.0/closing-documents"
    __product__: ClassVar[str] = "tochka-api"

    data: CreateClosingDocumentData = Field(..., alias="Data")


class DeleteClosingDocuments(BaseMethod[DeleteClosingDocumentsResponse]):
    """Метод для удаления закрывающего документа via ``DELETE
    /invoice/v1.0/closing-documents/{customer_code}/{document_id}``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        document_id: Уникальный идентификатор документа
    """

    __http_method__: ClassVar[str] = "DELETE"
    __endpoint__: ClassVar[str] = "/invoice/v1.0/closing-documents/{customer_code}/{document_id}"
    __product__: ClassVar[str] = "tochka-api"
    __idempotent_mutation__: ClassVar[bool] = True

    customer_code: str = Field(..., alias="customerCode")
    document_id: str = Field(..., alias="documentId")


class SendClosingDocumentsToEmail(BaseMethod[SendClosingDocumentsToEmailResponse]):
    """Метод для отправки закрывающего документа на почту via ``POST
    /invoice/v1.0/closing-documents/{customer_code}/{document_id}/email``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        document_id: Уникальный идентификатор документа
        data: SendDocumentToEmailRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/invoice/v1.0/closing-documents/{customer_code}/{document_id}/email"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
    document_id: str = Field(..., alias="documentId")
    data: SendClosingDocumentsToEmailData = Field(..., alias="Data")


class GetClosingDocument(BaseMethod[bytes]):
    """Метод для получения файла закрывающего документа via ``GET
    /invoice/v1.0/closing-documents/{customer_code}/{document_id}/file``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        document_id: Уникальный идентификатор документа
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/invoice/v1.0/closing-documents/{customer_code}/{document_id}/file"
    __product__: ClassVar[str] = "tochka-api"
    __binary_response__: ClassVar[bool] = True

    customer_code: str = Field(..., alias="customerCode")
    document_id: str = Field(..., alias="documentId")
