# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.customers import GetCustomerInfoResponse, GetCustomersListResponse
from ._base import BaseMethod


class GetCustomersList(BaseMethod[GetCustomersListResponse]):
    """Метод для получения списка доступных клиентов via ``GET /open-banking/v1.0/customers``.

    See: https://developers.tochka.com/docs
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/open-banking/v1.0/customers"
    __product__: ClassVar[str] = "tochka-api"


class GetCustomerInfo(BaseMethod[GetCustomerInfoResponse]):
    """Метод для получения информации по конкретному клиенту via ``GET
    /open-banking/v1.0/customers/{customer_code}``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Идентификатор клиента
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/open-banking/v1.0/customers/{customer_code}"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
