# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с клиентами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.customer_info import GetCustomerInfoResponse
from ._base import BaseMethod


class GetCustomerInfo(BaseMethod[GetCustomerInfoResponse]):
    """Метод получения информации по конкретному клиенту via ``GET /info/v1.0/customers/{customer_code}``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Идентификатор клиента
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/info/v1.0/customers/{customer_code}"
    __product__: ClassVar[str] = "info"

    customer_code: str = Field(..., alias="customerCode")
