# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Заказы — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.marketplace_orders import (
    CreateOrderData,
    CreateOrderResponse,
    CreateOrderV2Data,
    CreateOrderV2Response,
    CreateOrderV3Data,
    CreateOrderV3Response,
    GetOrderListResponse,
    GetOrderReportResponse,
    GetOrderResponse,
    GetOrderV2Response,
    GetOrderV3Response,
    MakeOrderServicesDecisionData,
    MakeOrderServicesDecisionResponse,
    UpdateOrderData,
    UpdateOrderResponse,
)
from ..pagination import OffsetMethod
from ._base import BaseMethod


class GetOrderList(OffsetMethod[GetOrderListResponse]):
    """Получить список заказов via ``GET /medusa/v1.0/orders``.

    See: https://developers.tochka.com/docs
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders"
    __product__: ClassVar[str] = "medusa"


class CreateOrder(BaseMethod[CreateOrderResponse]):
    """Создать заказ via ``POST /medusa/v1.0/orders``.

    See: https://developers.tochka.com/docs

    Args:
        data: CreateOrderRequest
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders"
    __product__: ClassVar[str] = "medusa"

    data: CreateOrderData = Field(..., alias="Data")


class GetOrderReport(BaseMethod[GetOrderReportResponse]):
    """Получить отчет по заказам via ``GET /medusa/v1.0/orders/report``.

    See: https://developers.tochka.com/docs

    Args:
        finished_at_gte: Finishedatgte
        finished_at_lte: Finishedatlte
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders/report"
    __product__: ClassVar[str] = "medusa"

    finished_at_gte: str = Field(..., alias="finishedAtGte")
    finished_at_lte: str = Field(..., alias="finishedAtLte")


class GetOrder(BaseMethod[GetOrderResponse]):
    """Получить заказ via ``GET /medusa/v1.0/orders/{order_ext_id}``.

    See: https://developers.tochka.com/docs

    Args:
        order_ext_id: Внешний идентификатор заказа
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders/{order_ext_id}"
    __product__: ClassVar[str] = "medusa"

    order_ext_id: str = Field(..., alias="orderExtId")


class UpdateOrder(BaseMethod[UpdateOrderResponse]):
    """Изменить услуги в заказе via ``PATCH /medusa/v1.0/orders/{order_ext_id}``.

    See: https://developers.tochka.com/docs

    Args:
        order_ext_id: Идентификатор заказа
        data: UpdateOrderRequest
    """

    __http_method__: ClassVar[str] = "PATCH"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders/{order_ext_id}"
    __product__: ClassVar[str] = "medusa"
    __idempotent_mutation__: ClassVar[bool] = True

    order_ext_id: str = Field(..., alias="orderExtId")
    data: UpdateOrderData = Field(..., alias="Data")


class MakeOrderServicesDecision(BaseMethod[MakeOrderServicesDecisionResponse]):
    """Подтвердить оказание услуги via ``POST /medusa/v1.0/orders/{order_ext_id}/decisions``.

    See: https://developers.tochka.com/docs

    Args:
        order_ext_id: Идентификатор заказа
        data: MakeOrderServicesDecisionRequest
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/medusa/v1.0/orders/{order_ext_id}/decisions"
    __product__: ClassVar[str] = "medusa"

    order_ext_id: str = Field(..., alias="orderExtId")
    data: MakeOrderServicesDecisionData = Field(..., alias="Data")


class CreateOrderV2(BaseMethod[CreateOrderV2Response]):
    """Создать заказ v2 via ``POST /medusa/v2.0/orders``.

    See: https://developers.tochka.com/docs

    Args:
        data: CreateOrderRequestV2
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/medusa/v2.0/orders"
    __product__: ClassVar[str] = "medusa"

    data: CreateOrderV2Data = Field(..., alias="Data")


class GetOrderV2(BaseMethod[GetOrderV2Response]):
    """Получить заказ v2 via ``GET /medusa/v2.0/orders/{order_ext_id}``.

    See: https://developers.tochka.com/docs

    Args:
        order_ext_id: Внешний идентификатор заказа
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/medusa/v2.0/orders/{order_ext_id}"
    __product__: ClassVar[str] = "medusa"

    order_ext_id: str = Field(..., alias="orderExtId")


class CreateOrderV3(BaseMethod[CreateOrderV3Response]):
    """Создать заказ v3 via ``POST /medusa/v3.0/orders``.

    See: https://developers.tochka.com/docs

    Args:
        data: CreateOrderRequestV3
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/medusa/v3.0/orders"
    __product__: ClassVar[str] = "medusa"

    data: CreateOrderV3Data = Field(..., alias="Data")


class GetOrderV3(BaseMethod[GetOrderV3Response]):
    """Получить заказ v3 via ``GET /medusa/v3.0/orders/{order_ext_id}``.

    See: https://developers.tochka.com/docs

    Args:
        order_ext_id: Внешний идентификатор заказа
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/medusa/v3.0/orders/{order_ext_id}"
    __product__: ClassVar[str] = "medusa"

    order_ext_id: str = Field(..., alias="orderExtId")
