# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Доступность сервиса — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from ..models.nominal_health import EchoV3Params
from ._base import BaseMethod


class EchoV3(BaseMethod[None]):
    """Проверить доступность сервиса via ``POST /v3/jsonrpc/echo``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v3/jsonrpc/echo"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: EchoV3Params
