# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Загрузка документов — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from datetime import date
from typing import ClassVar

from ..enums.nominal_document_uploads import (
    UploadDocumentBeneficiaryDocumentType,
    UploadDocumentDealDocumentType,
)
from ..models.nominal_document_uploads import UploadDocumentBeneficiaryResponse, UploadDocumentDealResponse
from ._base import BaseMethod


class UploadDocumentBeneficiary(BaseMethod[UploadDocumentBeneficiaryResponse]):
    """Загрузка документов для API.  Информацию по загруженным документам можно посмотреть в api_v2.  Все
    запросы должны содержать заголовок Content-Type  Важно: Загружаемые файлы не должны превышать размер 25
    МБ.  Документы добавляются в систему не сразу, и после вызова метода может произойти ошибка. Понять,
    что документ загрузился успешно, можно через вызов метода api_v2_get_document.  Некоторые фреймворки по
    умолчанию отправляют файл в формате multipart/form-data, наша система не воспринимает такие запросы.
    Файл в запросе должен передаваться сразу в теле сообщения. via ``POST /upload_document/beneficiary``.

    See: https://developers.tochka.com/docs

    Args:
        beneficiary_id: Идентификатор бенефициара
        document_type: Тип документа
        document_date: Дата документа
        document_number: Номер документа
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/upload_document/beneficiary"
    __product__: ClassVar[str] = "cyclops"

    beneficiary_id: str
    document_type: UploadDocumentBeneficiaryDocumentType
    document_date: date
    document_number: str


class UploadDocumentDeal(BaseMethod[UploadDocumentDealResponse]):
    """Загрузка документов для API.  Информацию по загруженным документам можно посмотреть в api_v2.  Все
    запросы должны содержать заголовок Content-Type  Важно: Загружаемые файлы не должны превышать размер 25
    МБ. *Документы добавляются в систему не сразу, и после вызова метода может произойти ошибка. Понять,
    что документ загрузился успешно, можно через вызов метода api_v2_get_document*. *Некоторые фреймворки
    по умолчанию отправляют файл в формате multipart/form-data, наша система не воспринимает такие запросы.
    Файл в запросе должен передаваться сразу в теле сообщения.* via ``POST /upload_document/deal``.

    See: https://developers.tochka.com/docs

    Args:
        beneficiary_id: Идентификатор бенефициара
        deal_id: Идентификатор сделки
        document_type: Тип документа
        document_date: Дата документа
        document_number: Номер документа
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/upload_document/deal"
    __product__: ClassVar[str] = "cyclops"

    beneficiary_id: str
    deal_id: str
    document_type: UploadDocumentDealDocumentType
    document_date: date
    document_number: str
