# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Платежи — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from ..models.nominal_payments import (
    ComplianceCheckPaymentV2Params,
    GeneratePaymentOrderV2Params,
    GetPaymentV2Params,
    IdentificationPaymentV2Params,
    IdentificationReturnedPaymentByDealV2Params,
    ListPaymentsV2Params,
    ListPaymentsV2V2Params,
    PaymentOfTaxesV2Params,
    RefundPaymentV2Params,
)
from ._base import BaseMethod


class ComplianceCheckPaymentV2(BaseMethod[None]):
    """Метод позволяет заранее проверить платежи типа payment_contract и ndfl на соответствие требованиям
    законодательства. Если не передать реквизиты номинального счёта, с которого планируется выплата, будет
    использован счёт по умолчанию. via ``POST /v2/jsonrpc/compliance_check_payment``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/compliance_check_payment"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: ComplianceCheckPaymentV2Params


class GeneratePaymentOrderV2(BaseMethod[None]):
    """Метод позволяет создать платёжное поручение, которое в т.ч. можно передавать своим
    бенефициарам/клиентам.Особенности работы на тестовых слоях: На pre слое реальной генерации платежного
    поручения производиться не будет. Будет возвращаться заранее подготовленный документ с ненастоящими
    данными. via ``POST /v2/jsonrpc/generate_payment_order``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/generate_payment_order"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: GeneratePaymentOrderV2Params


class GetPaymentV2(BaseMethod[None]):
    """Метод возвращает информацию по выбранному платежу via ``POST /v2/jsonrpc/get_payment``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/get_payment"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: GetPaymentV2Params


class IdentificationPaymentV2(BaseMethod[None]):
    """Метод позволяет идентифицировать деньги, т.е. сопоставить их с нужным виртуальным счётом via ``POST
    /v2/jsonrpc/identification_payment``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/identification_payment"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: IdentificationPaymentV2Params


class IdentificationReturnedPaymentByDealV2(BaseMethod[None]):
    """Метод используется для случаев идентификации денег, когда исходящий платеж по сделке был возвращен
    банком-получателем via ``POST /v2/jsonrpc/identification_returned_payment_by_deal``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/identification_returned_payment_by_deal"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: IdentificationReturnedPaymentByDealV2Params


class ListPaymentsV2(BaseMethod[None]):
    """Метод возвращает список платежей по заданным фильтрам via ``POST /v2/jsonrpc/list_payments``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/list_payments"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: ListPaymentsV2Params


class ListPaymentsV2V2(BaseMethod[None]):
    """Метод возвращает список платежей по заданным фильтрам via ``POST /v2/jsonrpc/list_payments_v2``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/list_payments_v2"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: ListPaymentsV2V2Params


class PaymentOfTaxesV2(BaseMethod[None]):
    """Метод позволяет выводить деньги с виртуального счёта типа for_ndfl via ``POST
    /v2/jsonrpc/payment_of_taxes``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/payment_of_taxes"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: PaymentOfTaxesV2Params


class RefundPaymentV2(BaseMethod[None]):
    """Возврат неидентифицированных платежей и идентифицированных платежей по СБП via ``POST
    /v2/jsonrpc/refund_payment``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/refund_payment"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: RefundPaymentV2Params
