# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платежами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.payments import (
    CreatePaymentForSignData,
    CreatePaymentForSignResponse,
    GetPaymentForSignListResponse,
    GetPaymentStatusResponse,
)
from ._base import BaseMethod


class GetPaymentForSignList(BaseMethod[GetPaymentForSignListResponse]):
    """Метод получения списка платежей на подпись via ``GET /payment/v1.0/for-sign``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/payment/v1.0/for-sign"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")


class CreatePaymentForSign(BaseMethod[CreatePaymentForSignResponse]):
    """Метод для создания платежа.  Чтобы платёж прошёл, его нужно будет подписать в интернет-банке.  Если вы
    создаёте платёж за третье лицо, поля `payerINN` и `payerKPP` обязательные для заполнения. Если платите
    за себя в бюджет, поле `payerKPP` становится обязательным.  **Обратите внимание:** *paymentDate* нужно
    заполнить по часовому поясу Москвы. via ``POST /payment/v1.0/for-sign``.

    See: https://developers.tochka.com/docs

    Args:
        data: PaymentForSignRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/payment/v1.0/for-sign"
    __product__: ClassVar[str] = "tochka-api"

    data: CreatePaymentForSignData = Field(..., alias="Data")


class GetPaymentStatus(BaseMethod[GetPaymentStatusResponse]):
    """Метод для получения статуса платежа via ``GET /payment/v1.0/status/{request_id}``.

    See: https://developers.tochka.com/docs

    Args:
        request_id: Идентификатор запроса
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/payment/v1.0/status/{request_id}"
    __product__: ClassVar[str] = "tochka-api"

    request_id: str = Field(..., alias="requestId")
