# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с платёжными ссылками — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..enums.payment_links import GetPaymentOperationListStatus
from ..models.payment_links import (
    CapturePaymentResponse,
    CreatePaymentOperationData,
    CreatePaymentOperationResponse,
    CreatePaymentOperationWithReceiptData,
    CreatePaymentOperationWithReceiptResponse,
    GetPaymentOperationInfoResponse,
    GetPaymentOperationListResponse,
    GetPaymentRegistryResponse,
    GetRetailersResponse,
    RefundPaymentOperationData,
    RefundPaymentOperationResponse,
)
from ..pagination import PageMethod
from ._base import BaseMethod


class GetPaymentOperationList(PageMethod[GetPaymentOperationListResponse]):
    """Метод для получения списка операций  - *CREATED* - Операция создана - *APPROVED* - Операция одобрена
    (оплата прошла успешно) - *ON-REFUND* - Операция заблокирована на время выполнения возврата -
    *REFUNDED* - Осуществлен возврат - *EXPIRED* - Истек срок действия via ``GET
    /acquiring/v1.0/payments``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        from_date: Начало периода создания операций
        to_date: Конец периода создания операций
        status: Статус операции
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
    from_date: str | None = Field(None, alias="fromDate")
    to_date: str | None = Field(None, alias="toDate")
    status: GetPaymentOperationListStatus | None = None


class CreatePaymentOperation(BaseMethod[CreatePaymentOperationResponse]):
    """Метод для создания ссылки на оплату via ``POST /acquiring/v1.0/payments``.

    See: https://developers.tochka.com/docs

    Args:
        data: AcquiringCreatePaymentOperationRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments"
    __product__: ClassVar[str] = "tochka-api"

    data: CreatePaymentOperationData = Field(..., alias="Data")


class GetPaymentOperationInfo(BaseMethod[GetPaymentOperationInfoResponse]):
    """Метод для получения информации о конкретной операции  - *CREATED* - Операция создана - *APPROVED* -
    Операция одобрена (оплата прошла успешно) - *ON-REFUND* - Операция заблокирована на время выполнения
    возврата - *REFUNDED* - Осуществлен возврат - *EXPIRED* - Истек срок действия via ``GET
    /acquiring/v1.0/payments/{operation_id}``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор платежа
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments/{operation_id}"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")


class CapturePayment(BaseMethod[CapturePaymentResponse]):
    """Метод для списания средств при двухэтапной оплате via ``POST
    /acquiring/v1.0/payments/{operation_id}/capture``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор подписки
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments/{operation_id}/capture"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")


class RefundPaymentOperation(BaseMethod[RefundPaymentOperationResponse]):
    """Метод для возврата платежей, созданных через платёжную ссылку Возврат возможен только для платежа со
    статусом APPROVED via ``POST /acquiring/v1.0/payments/{operation_id}/refund``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор платежа
        data: AcquiringPaymentOrderRefundRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments/{operation_id}/refund"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")
    data: RefundPaymentOperationData = Field(..., alias="Data")


class CreatePaymentOperationWithReceipt(BaseMethod[CreatePaymentOperationWithReceiptResponse]):
    """Метод для создания ссылки на оплату и отправки чека via ``POST /acquiring/v1.0/payments_with_receipt``.

    See: https://developers.tochka.com/docs

    Args:
        data: AcquiringCreatePaymentOperationWithReceiptRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/payments_with_receipt"
    __product__: ClassVar[str] = "tochka-api"

    data: CreatePaymentOperationWithReceiptData = Field(..., alias="Data")


class GetPaymentRegistry(BaseMethod[GetPaymentRegistryResponse]):
    """Метод для получения реестра платежей по интернет-эквайрингу via ``GET /acquiring/v1.0/registry``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        merchant_id: Идентификатор торговой точки в интернет-эквайринге
        payment_id: Уникальный идентификатор платежа, по которому произошла транзакция
        date_: Дата реестра
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/registry"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
    merchant_id: str = Field(..., alias="merchantId")
    payment_id: str | None = Field(None, alias="paymentId")
    date_: str = Field(..., alias="date")


class GetRetailers(BaseMethod[GetRetailersResponse]):
    """Метод для получения информации о ретейлере  - *NEW* - Ретейлер создан - *ADDRESS_DADATA* - Адрес
    уточнен - *OPEN_ACCOUNT* - Счёт открыт - *TWPG_SENDED* - Данные мерчанта и терминала отправлены в
    процессинг - *RETAILER_CREATED* - Мерчант создан в процессинге - *TERMINAL_CREATED* - Терминал создан в
    процессинге - *FILE_SENT* - файл отправлен в НСПК - *REG* - Зарегистрирован - *CLOSE* - Закрыт via
    ``GET /acquiring/v1.0/retailers``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/retailers"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
