# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с разрешениями — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..models.permissions import (
    CreateNewConsentData,
    CreateNewConsentResponse,
    GetAllChildConsentsResponse,
    GetAllConsentsListResponse,
    GetConsentInfoResponse,
)
from ._base import BaseMethod


class GetAllConsentsList(BaseMethod[GetAllConsentsListResponse]):
    """Метод для получения списка разрешений. via ``GET /consent/v1.0/consents``.

    See: https://developers.tochka.com/docs
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/consent/v1.0/consents"
    __product__: ClassVar[str] = "tochka-api"


class CreateNewConsent(BaseMethod[CreateNewConsentResponse]):
    """Метод для создания разрешения. via ``POST /consent/v1.0/consents``.

    See: https://developers.tochka.com/docs

    Args:
        data: ConsentCreateRequestModel
        risks: Risks
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/consent/v1.0/consents"
    __product__: ClassVar[str] = "tochka-api"

    data: CreateNewConsentData = Field(..., alias="Data")
    risks: dict[str, Any] | None = Field(None, alias="Risks")


class GetConsentInfo(BaseMethod[GetConsentInfoResponse]):
    """Метод для получения информации о списке разрешений via ``GET /consent/v1.0/consents/{consent_id}``.

    See: https://developers.tochka.com/docs

    Args:
        consent_id: Уникальный идентификатор, предназначенный для идентификации разрешения
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/consent/v1.0/consents/{consent_id}"
    __product__: ClassVar[str] = "tochka-api"

    consent_id: str = Field(..., alias="consentId")


class GetAllChildConsents(BaseMethod[GetAllChildConsentsResponse]):
    """Метод для получения всех дочерних разрешений via ``GET /consent/v1.0/consents/{consent_id}/child``.

    See: https://developers.tochka.com/docs

    Args:
        consent_id: Уникальный идентификатор, предназначенный для идентификации разрешения
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/consent/v1.0/consents/{consent_id}/child"
    __product__: ClassVar[str] = "tochka-api"

    consent_id: str = Field(..., alias="consentId")
