# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: работа с B2B QR-кодами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.sbp_b2b_qr_codes import GetB2bQrCodeResponse, RegisterB2bQrCodeData, RegisterB2bQrCodeResponse
from ._base import BaseMethod


class RegisterB2bQrCode(BaseMethod[RegisterB2bQrCodeResponse]):
    """Метод для регистрации B2B QR-кода в Системе быстрых платежей via ``POST
    /sbp/v1.0/b2b-qr-code/merchant/{merchant_id}/{account_id}``.

    See: https://developers.tochka.com/docs

    Args:
        account_id: Уникальный и неизменный идентификатор счёта юрлица
        merchant_id: Идентификатор ТСП
        data: RegisterB2BQRCode
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/b2b-qr-code/merchant/{merchant_id}/{account_id}"
    __product__: ClassVar[str] = "tochka-api"

    account_id: str = Field(..., max_length=40, alias="accountId")
    merchant_id: str = Field(..., max_length=12, alias="merchantId")
    data: RegisterB2bQrCodeData = Field(..., alias="Data")


class GetB2bQrCode(BaseMethod[GetB2bQrCodeResponse]):
    """Метод для получения информации о B2B QR-коде via ``GET /sbp/v1.0/b2b-qr-code/{qrc_id}``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
        width: Ширина изображения (по умолчанию: 300)
        height: Высота изображения (по умолчанию: 300)
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/b2b-qr-code/{qrc_id}"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
    width: int | None = None
    height: int | None = None
