# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с кассовыми QR-кодами — domain endpoints (auto-generated from the Tochka OpenAPI
spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.sbp_cashbox_qr_codes import (
    ActivateCashboxQrcodeData,
    ActivateCashboxQrcodeResponse,
    ChangeCashboxQrcodeAccountData,
    ChangeCashboxQrcodeAccountResponse,
    DeactivateCashboxQrcodeResponse,
    GetCashboxQrcodeData,
    GetCashboxQrcodeListResponse,
    GetCashboxQrcodeOperationInfoResponse,
    GetCashboxQrcodeResponse,
    GetCashboxQrcodeStatusResponse,
    RegisterCashboxQrcodeData,
    RegisterCashboxQrcodeResponse,
)
from ._base import BaseMethod


class RegisterCashboxQrcode(BaseMethod[RegisterCashboxQrcodeResponse]):
    """Метод для регистрации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code``.

    See: https://developers.tochka.com/docs

    Args:
        data: RegisterCashboxQrCodeRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code"
    __product__: ClassVar[str] = "tochka-api"

    data: RegisterCashboxQrcodeData = Field(..., alias="Data")


class GetCashboxQrcodeList(BaseMethod[GetCashboxQrcodeListResponse]):
    """Метод для получения списка кассовых QR-кодов via ``GET
    /sbp/v1.0/cashbox-qr-code/merchant/{merchant_id}/{account_id}``.

    See: https://developers.tochka.com/docs

    Args:
        merchant_id: Идентификатор ТСП
        account_id: Уникальный и неизменный идентификатор счёта
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/merchant/{merchant_id}/{account_id}"
    __product__: ClassVar[str] = "tochka-api"

    merchant_id: str = Field(..., alias="merchantId")
    account_id: str = Field(..., alias="accountId")


class GetCashboxQrcode(BaseMethod[GetCashboxQrcodeResponse]):
    """Метод для получения информации о кассовом QR-коде via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
        data: GetCashboxQRCodeRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
    data: GetCashboxQrcodeData = Field(..., alias="Data")


class ChangeCashboxQrcodeAccount(BaseMethod[ChangeCashboxQrcodeAccountResponse]):
    """Метод для смены счёта зачисления кассового QR-кода via ``POST
    /sbp/v1.0/cashbox-qr-code/{qrc_id}/account``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
        data: ChangeCashboxQRCodeAccountRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}/account"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
    data: ChangeCashboxQrcodeAccountData = Field(..., alias="Data")


class ActivateCashboxQrcode(BaseMethod[ActivateCashboxQrcodeResponse]):
    """Метод для активации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}/activate``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
        data: ActivateCashboxQrCodeRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}/activate"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
    data: ActivateCashboxQrcodeData = Field(..., alias="Data")


class DeactivateCashboxQrcode(BaseMethod[DeactivateCashboxQrcodeResponse]):
    """Метод для деактивации кассового QR-кода via ``POST /sbp/v1.0/cashbox-qr-code/{qrc_id}/deactivate``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}/deactivate"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")


class GetCashboxQrcodeOperationInfo(BaseMethod[GetCashboxQrcodeOperationInfoResponse]):
    """Метод для получения статуса кассового QR-кода. via ``GET
    /sbp/v1.0/cashbox-qr-code/{qrc_id}/operation``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
        params_id: Идентификатор активных значений параметров QR-кода
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}/operation"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
    params_id: str = Field(..., alias="paramsId")


class GetCashboxQrcodeStatus(BaseMethod[GetCashboxQrcodeStatusResponse]):
    """Метод для получения статуса кассового QR-кода. via ``GET /sbp/v1.0/cashbox-qr-code/{qrc_id}/status``.

    See: https://developers.tochka.com/docs

    Args:
        qrc_id: Идентификатор QR-кода в СБП
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/cashbox-qr-code/{qrc_id}/status"
    __product__: ClassVar[str] = "tochka-api"

    qrc_id: str = Field(..., alias="qrcId")
