# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Сервис СБП: Работа с возвратами — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.sbp_refunds import (
    GetPaymentsResponse,
    GetRefundDataResponse,
    StartRefundData,
    StartRefundResponse,
)
from ..pagination import PageMethod
from ._base import BaseMethod


class GetPayments(PageMethod[GetPaymentsResponse]):
    """Метод для получения списка платежей в Системе быстрых платежей  Обратите внимание: при поиске платежей
    за прошедшие дни обязательно передавать атрибут `fromDate` с указанием начальной даты периода. Если
    этот атрибут не передать, поиск выдаст результаты только за вчерашний и сегодняшний дни. via ``GET
    /sbp/v1.0/get-sbp-payments``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        qrc_id: ID qr-кода для фильтрации
        from_date: Начало периода для запроса статусов платежей. При отсутствии параметра в запросе будет
            задано дефолтное значение
        to_date: Конец периода для запроса статусов платежей
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/get-sbp-payments"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
    qrc_id: str | None = Field(None, alias="qrcId")
    from_date: str = Field("Вчера и сегодня", alias="fromDate")
    to_date: str | None = Field(None, alias="toDate")


class StartRefund(BaseMethod[StartRefundResponse]):
    """Метод запрашивает возврат платежа через Систему быстрых платежей  Если нужно вернуть деньги
    нерезиденту, назначение платежа должно начинаться с «{VO99020} Возврат ошибочно полученной суммы
    transactionId», где `transactionId` — это идентификатор оригинальной операции. via ``POST
    /sbp/v1.0/refund``.

    See: https://developers.tochka.com/docs

    Args:
        data: SBPRefund
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/refund"
    __product__: ClassVar[str] = "tochka-api"

    data: StartRefundData = Field(..., alias="Data")


class GetRefundData(BaseMethod[GetRefundDataResponse]):
    """Метод для получения информация о платеже-возврате по Системе быстрых платежей via ``GET
    /sbp/v1.0/refund/{request_id}``.

    See: https://developers.tochka.com/docs

    Args:
        request_id: ID запроса
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/sbp/v1.0/refund/{request_id}"
    __product__: ClassVar[str] = "tochka-api"

    request_id: str
