# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Работа с подписками — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.subscriptions import (
    ChargeSubscriptionData,
    ChargeSubscriptionResponse,
    CreateSubscriptionData,
    CreateSubscriptionResponse,
    CreateSubscriptionWithReceiptData,
    CreateSubscriptionWithReceiptResponse,
    GetSubscriptionListResponse,
    GetSubscriptionStatusResponse,
    SetSubscriptionStatusData,
    SetSubscriptionStatusResponse,
)
from ..pagination import PageMethod
from ._base import BaseMethod


class GetSubscriptionList(PageMethod[GetSubscriptionListResponse]):
    """Метод для получения всех подписок via ``GET /acquiring/v1.0/subscriptions``.

    See: https://developers.tochka.com/docs

    Args:
        customer_code: Уникальный код клиента
        recurring: Получить платежи по рекуррентным подпискам
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions"
    __product__: ClassVar[str] = "tochka-api"

    customer_code: str = Field(..., alias="customerCode")
    recurring: bool = False


class CreateSubscription(BaseMethod[CreateSubscriptionResponse]):
    """Метод для создания подписки по карте via ``POST /acquiring/v1.0/subscriptions``.

    See: https://developers.tochka.com/docs

    Args:
        data: AcquiringCreateSubscriptionRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions"
    __product__: ClassVar[str] = "tochka-api"

    data: CreateSubscriptionData = Field(..., alias="Data")


class ChargeSubscription(BaseMethod[ChargeSubscriptionResponse]):
    """Метод для списания средств по рекуррентной подписке via ``POST
    /acquiring/v1.0/subscriptions/{operation_id}/charge``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор подписки
        data: AcquiringChargeSubscriptionRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions/{operation_id}/charge"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")
    data: ChargeSubscriptionData = Field(..., alias="Data")


class GetSubscriptionStatus(BaseMethod[GetSubscriptionStatusResponse]):
    """Метод для получения актуального статуса подписки via ``GET
    /acquiring/v1.0/subscriptions/{operation_id}/status``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор подписки
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions/{operation_id}/status"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")


class SetSubscriptionStatus(BaseMethod[SetSubscriptionStatusResponse]):
    """Метод для установки статуса подписки via ``POST /acquiring/v1.0/subscriptions/{operation_id}/status``.

    See: https://developers.tochka.com/docs

    Args:
        operation_id: Идентификатор подписки
        data: AcquiringSetSubscriptionStatusRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions/{operation_id}/status"
    __product__: ClassVar[str] = "tochka-api"

    operation_id: str = Field(..., alias="operationId")
    data: SetSubscriptionStatusData = Field(..., alias="Data")


class CreateSubscriptionWithReceipt(BaseMethod[CreateSubscriptionWithReceiptResponse]):
    """Метод для создания подписки по карте и отправке чека via ``POST
    /acquiring/v1.0/subscriptions_with_receipt``.

    See: https://developers.tochka.com/docs

    Args:
        data: AcquiringCreateSubscriptionWithReceiptRequestModel
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/acquiring/v1.0/subscriptions_with_receipt"
    __product__: ClassVar[str] = "tochka-api"

    data: CreateSubscriptionWithReceiptData = Field(..., alias="Data")
