# AUTO-GENERATED by tochka.codegen — regenerate, do not hand-edit.
"""Виртуальные счета — domain endpoints (auto-generated from the Tochka OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from ..models.virtual_accounts import (
    CreateVirtualAccountV2Params,
    GetVirtualAccountsTransferV2Params,
    GetVirtualAccountV2Params,
    ListVirtualAccountV2Params,
    ListVirtualTransactionV2Params,
    RefundVirtualAccountV2Params,
    TransferBetweenVirtualAccountsV2Params,
    TransferBetweenVirtualAccountsV2V2Params,
)
from ._base import BaseMethod


class CreateVirtualAccountV2(BaseMethod[None]):
    """Метод создаёт виртуальный счет для бенефициара. via ``POST /v2/jsonrpc/create_virtual_account``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/create_virtual_account"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: CreateVirtualAccountV2Params


class GetVirtualAccountV2(BaseMethod[None]):
    """Метод возвращает информацию по выбранному виртуальному счёту via ``POST
    /v2/jsonrpc/get_virtual_account``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/get_virtual_account"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: GetVirtualAccountV2Params


class GetVirtualAccountsTransferV2(BaseMethod[None]):
    """Метод возвращает информацию о выбранном переводе между виртуальными счётами via ``POST
    /v2/jsonrpc/get_virtual_accounts_transfer``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/get_virtual_accounts_transfer"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: GetVirtualAccountsTransferV2Params


class ListVirtualAccountV2(BaseMethod[None]):
    """Метод возвращает список виртуальных счетов, соответствующих заданным фильтрам via ``POST
    /v2/jsonrpc/list_virtual_account``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/list_virtual_account"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: ListVirtualAccountV2Params


class ListVirtualTransactionV2(BaseMethod[None]):
    """Метод возвращает движение денег у выбранного виртуального счёта по заданным фильтрам via ``POST
    /v2/jsonrpc/list_virtual_transaction``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/list_virtual_transaction"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: ListVirtualTransactionV2Params


class RefundVirtualAccountV2(BaseMethod[None]):
    """Метод поможет вывести идентифицированные деньги с виртуального счёта. Вывод по реквизитам. Документы
    при такой операции подгружать не нужно. Метод нужен, например, для вывода ошибочно-зачисленных денежных
    средств. При добавлении ext_key в запрос метод станет идемпотентным. В случае повторного запроса с
    одним и тем же ext_key будет возвращен ответ оригинального запроса. via ``POST
    /v2/jsonrpc/refund_virtual_account``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/refund_virtual_account"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: RefundVirtualAccountV2Params


class TransferBetweenVirtualAccountsV2(BaseMethod[None]):
    """Метод используется для перевода денег в рамках одного номинального счёта. Может быть использован только
    для перевода денег в рамках одного номинального счёта. via ``POST
    /v2/jsonrpc/transfer_between_virtual_accounts``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/transfer_between_virtual_accounts"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: TransferBetweenVirtualAccountsV2Params


class TransferBetweenVirtualAccountsV2V2(BaseMethod[None]):
    """Данный метод был реализован для целей миграции с одного банка на другой. Сейчас неактуален. Но всё ещё
    может использоваться для переводов в рамках одного номинального счета. Метод переводит деньги между
    виртуальными счетами. Если счета находятся на одном номинальном счёте, то перевод происходит мгновенно.
    В противном случае перевод осуществляется с помощью банковского платежа между номинальными счетами и
    завершается, когда платёж исполнен. Платёж идентифицируется автоматически согласно информации в
    запросе. Для получения статуса перевода необходимо использовать метод get_virtual_accounts_transfer.
    via ``POST /v2/jsonrpc/transfer_between_virtual_accounts_v2``.

    See: https://developers.tochka.com/docs

    Args:
        id: JsonRPC id
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/v2/jsonrpc/transfer_between_virtual_accounts_v2"
    __product__: ClassVar[str] = "cyclops"

    id: Any
    jsonrpc: str
    method: str
    params: TransferBetweenVirtualAccountsV2V2Params
